/** Generated from the legacy i18n module during the directory migration. */
export default {
// 通用
  'auth.login': '登录',
  'auth.register': '注册',
  'auth.backToLogin': '返回登录',
  'auth.goToLogin': '前往登录',
  'auth.emailLabel': '邮箱',
  'auth.passwordLabel': '密码',
  'auth.passkeyLabel': '通行密钥',
  'auth.showPassword': '显示密码',
  'auth.or': '或',
  'auth.termsOfService': '服务条款',
  'auth.privacyPolicy': '隐私政策',
  'auth.checkEmailTitle': '请查收邮箱',
  'auth.verificationLinkSentTo': '验证链接已发送到',
  'auth.resendLinkPrefix': '重新发送 (',
  'auth.resendLinkSuffix': 's)',
  'auth.keepSignedIn30Days': '30 天内保持登录',
  'auth.verifyingEmail': '正在验证邮箱...',
  'auth.emailVerifiedTitle': '邮箱验证成功',
  'auth.emailInputPlaceholder': '输入邮箱地址',
  'auth.passkeyUsageHint': '使用指纹、面部识别或设备 PIN',
  'auth.immediateRegister': '立即注册',
  'auth.immediateLogin': '立即登录',

  // 登录页
  'auth.seoLoginTitle': '账号登录入口',
  'auth.seoLoginDescription': '登录社区账号后，可继续参与帖子讨论、访问资源下载、查看私信通知、管理收藏记录与进入个人中心。',
  'auth.loginEmailIntro': '输入邮箱后可选择密码、邮箱验证码或通行密钥；也可以直接使用第三方账号登录。',
  'auth.emailOrUsernameLabel': '邮箱或用户名',
  'auth.emailOrUsernamePlaceholder': '输入邮箱或用户名',
  'auth.nextStep': '下一步',
  'auth.loginWithPasskey': '使用通行密钥登录',
  'auth.continueWithThirdParty': '使用第三方账号继续',
  'auth.thirdPartyNoEmailHint': '第三方登录无需先输入邮箱',
  'auth.noAccountYet': '还没有账号？',
  'auth.backToEmail': '← 返回邮箱',
  'auth.chooseLoginMethod': '选择登录方式',
  'auth.currentEmail': '当前邮箱：',
  'auth.passwordLoginTitle': '密码登录',
  'auth.passwordLoginDesc': '使用邮箱和密码登录',
  'auth.emailLoginTitle': '邮箱验证登录',
  'auth.emailLoginDesc': '通过邮箱链接免密码登录',
  'auth.thirdPartyLoginTitle': '第三方账号登录',
  'auth.thirdPartyLoginDesc': '使用 GitHub、Google、Discord 等账号',
  'auth.backToChoose': '← 返回选择',
  'auth.passwordPlaceholder': '输入密码',
  'auth.forgotPasswordLink': '忘记密码?',
  'auth.passkeyDialogHint': '请在弹窗中完成通行密钥验证',
  'auth.startVerification': '开始验证',
  'auth.emailLinkIntro': '将向以下邮箱发送登录链接：',
  'auth.sendVerificationLink': '发送验证链接',
  'auth.emailLinkSentHint': '点击邮件中的链接即可完成登录，链接 10 分钟内有效。',
  'auth.verifyingLoginLink': '正在验证登录链接...',
  'auth.chooseThirdPartyLogin': '选择第三方账号登录',
  'auth.emailVerificationRequiredTitle': '需要先验证邮箱',
  'auth.emailVerificationRequiredDesc': '此第三方账号关联的邮箱尚未验证。完成邮箱验证后即可继续登录。',
  'auth.resendEmail': '重新发送邮件',
  'auth.iHaveVerified': '我已完成验证',
  'auth.handleLater': '稍后处理',
  'auth.closeEmailVerificationPrompt': '关闭邮箱验证提示',

  // 注册页
  'auth.seoRegisterTitle': '创建社区账号',
  'auth.seoRegisterDescription': '注册社区账号并完成邮箱验证后，即可加入 Minecraft 中文资源分享与交流社区，发布内容、参与讨论并管理个人主页。',
  'auth.registerEmailStepIntro': '输入邮箱并完成人机验证，我们将发送验证链接',
  'auth.emailPlaceholder': '输入邮箱',
  'auth.referralEntryBanner': '你正在通过推广链接注册，完成注册后将为分享者计入邀请记录。',
  'auth.haveAccountYet': '已有账号？',
  'auth.registerWithThirdParty': '使用第三方账号注册',
  'auth.backToEmailRegister': '← 返回邮箱注册',
  'auth.chooseThirdPartyRegister': '选择第三方账号注册',
  'auth.registerEmailSentHint': '请点击邮件中的链接完成验证，链接 30 分钟内有效。',
  'auth.backToEditEmail': '返回修改邮箱',
  'auth.registerProfileIntro': '邮箱验证成功！请设置用户名并选择一种安全方式完成注册',
  'auth.oauthRegisterNoEmailBanner': '当前第三方账号没有返回邮箱。请先绑定一个常用邮箱，再继续完成注册。',
  'auth.geeIdNoticePrefix': '当前注册流程会同步联动创建你的 GeeID 账户。继续完成注册即表示你已知悉并同意',
  'auth.geeIdTerms': 'GeeID 服务条款',
  'auth.geeIdAnd': '与',
  'auth.geeIdPrivacy': 'GeeID 隐私政策',
  'auth.geeIdNoticeSuffix': '。',
  'auth.bindEmailLabel': '绑定邮箱',
  'auth.bindEmailPlaceholder': '输入常用邮箱',
  'auth.bindEmailHint': '用于找回密码、接收通知以及后续账号安全操作。',
  'auth.referralStepBanner': '当前注册包含推广邀请关系，完成后会自动记录到分享者名下。',
  'auth.displayNameLabel': '显示昵称',
  'auth.displayNamePlaceholder': '输入站内显示昵称（支持中文）',
  'auth.usernameLabel': '英文用户名',
  'auth.usernamePlaceholder': '3-16 位，仅限英文、数字和下划线',
  'auth.referralCodeLabel': '推广码（可选）',
  'auth.referralCodePlaceholder': '填写他人分享的推广码',
  'auth.referralCodeHint': '如果你是通过他人的推广链接来到这里，这里通常会自动填好，也可以手动修改。',
  'auth.referralCodeRequiredHint': '当前访问地区注册需要填写有效推广码。',
  'auth.referralDisabledHint': '当前站点暂未开启推广码功能，注册页不会处理推广码或推广奖励。',
  'auth.phoneBindTitle': '手机号绑定',
  'auth.phoneBindCopy': '可在注册时一并完成 Gee ID 手机号绑定。',
  'auth.phoneLabel': '手机号',
  'auth.phonePlaceholder': '请输入 11 位手机号',
  'auth.sendCode': '发送验证码',
  'auth.smsCodeLabel': '短信验证码',
  'auth.smsCodePlaceholder': '请输入 6 位短信验证码',
  'auth.phoneUnavailableHint': '当前注册地区暂不支持 Gee ID 中国大陆手机号绑定，完成注册后相关内容将进入人工审核。',
  'auth.emailOptIn': '通过电子邮件接收我们的消息和通知',
  'auth.agreeTermsPrefix': '我同意',
  'auth.agreeTermsAnd': '和',
  'auth.securityMethodLabel': '选择账号安全方式',
  'auth.setPassword': '设置密码',
  'auth.passwordPlaceholderMin6': '输入密码（至少 6 位）',
  'auth.passwordMin6Hint': '密码至少 6 个字符',
  'auth.completeRegister': '完成注册',
  'auth.passkeyCreateHint': '点击下方按钮，使用指纹、面部识别或设备 PIN 创建通行密钥',
  'auth.createPasskeyAndRegister': '创建通行密钥并完成注册',

  // 找回密码
  'auth.seoForgotPasswordTitle': '找回账号密码',
  'auth.seoForgotPasswordDescription': '通过注册邮箱接收重置链接，重新设置社区账号密码并恢复登录。',
  'auth.forgotPasswordTitle': '找回密码',
  'auth.forgotPasswordIntro': '输入注册邮箱，我们将发送重置链接',
  'auth.emailAddressLabel': '邮箱地址',
  'auth.registeredEmailPlaceholder': '输入注册时使用的邮箱',
  'auth.sendResetLink': '发送重置链接',
  'auth.newPasswordLabel': '新密码',
  'auth.newPasswordPlaceholder': '至少 6 位',
  'auth.confirmPasswordLabel': '确认密码',
  'auth.confirmPasswordPlaceholder': '再次输入新密码',
  'auth.resetPassword': '重置密码',
  'auth.emailRequired': '请输入邮箱',
  'auth.captchaRequired': '请先完成人机验证',
  'auth.sending': '发送中...',
  'auth.resetLinkSent': '重置链接已发送到你的邮箱，请查收',
  'auth.sendFailed': '发送失败',
  'auth.fieldsRequired': '请填写完整',
  'auth.passwordsDoNotMatch': '两次密码不一致',
  'auth.resetting': '重置中...',
  'auth.passwordResetSuccess': '密码重置成功，请使用新密码登录',
  'auth.resetFailed': '重置失败',
  'auth.verifyingResetToken': '验证中...',
  'auth.setNewPasswordIntro': '请设置新密码',
  'auth.resetLinkInvalid': '链接已失效或已被使用',

  // 两步验证
  'auth.seoLogin2faTitle': '二步验证安全确认',
  'auth.seoLogin2faDescription': '完成二步验证登录或首次绑定 2FA，保护账号与登录安全。',
  'auth.twoFactorTitle': '二步验证',
  'auth.twoFactorIntro': '请输入 6 位动态验证码，或备用码（例如 `ABCDE-FGHIJ`）',
  'auth.codeOrBackupLabel': '验证码 / 备用码',
  'auth.codeOrBackupPlaceholder': '123456 或 ABCDE-FGHIJ',
  'auth.verifyAndLogin': '验证并登录',
  'auth.newDeviceDetected': '检测到新设备登录，请完成一次安全验证后继续。',
  'auth.twoFactorCodeLabel': '2FA 验证码 / 备用码',
  'auth.verify2faAndLogin': '验证 2FA 并登录',
  'auth.passkeyConfirmHint': '使用已绑定的通行密钥确认这次新设备登录。',
  'auth.verifyWithPasskey': '使用通行密钥验证',
  'auth.doublePasswordLabel': '双层密码',
  'auth.doublePasswordPlaceholder': '输入双层密码',
  'auth.verifyDoublePasswordAndLogin': '验证双层密码并登录',
  'auth.twoFactorNotBound': '你的账号尚未绑定 2FA，请先完成绑定。',
  'auth.scanQrHint': '使用身份验证器扫描二维码',
  'auth.manualSecretLabel': '手动输入密钥',
  'auth.copy': '复制',
  'auth.authenticatorTroubleshootHint': '如果 Microsoft Authenticator 扫码后一直无效，请选择手动输入密钥，并确认手机时间已自动同步。',
  'auth.setupCodeLabel': '输入应用中显示的 6 位验证码',
  'auth.setupCodePlaceholder': '123456',
  'auth.completeBinding': '完成绑定并生成备用码',
  'auth.saveBackupCodesTitle': '请先保存备用码',
  'auth.backupCodesCopy': '备用码仅在验证器不可用时使用，每个只能使用一次。建议至少保存到 2 个安全位置。',
  'auth.copyBackupCodes': '复制备用码',
  'auth.downloadBackupCodes': '下载备用码.txt',
  'auth.backupCodesConfirm': '我已下载或复制这些备用码，并会离线妥善保存',
  'auth.finishAndEnterSite': '完成并进入站点',

  // 邮箱验证结果页
  'auth.seoVerifyEmailTitle': '邮箱验证结果页',
  'auth.seoVerifyEmailDescription': '验证账号邮箱地址、查看验证结果，并在失败时重新发送验证邮件。',
  'auth.verifyingEmailHint': '请稍候，验证完成后会自动显示结果。',
  'auth.emailVerifiedDesc': '邮箱已经验证完成，你现在可以直接返回登录并继续进入站点了。',
  'auth.verifyFailedTitle': '验证没有完成',
  'auth.verifyFailedDesc': '这个验证链接已失效、已使用，或与你当前邮箱不匹配。',
  'auth.resendVerifyEmailHint': '输入注册邮箱，我们会重新发送一封新的验证邮件：',
  'auth.send': '发送',

  // OAuth 授权页
  'auth.seoOAuthAuthorizeTitle': '授权第三方站点',
  'auth.seoOAuthAuthorizeDescription': '确认是否允许第三方应用读取本站账号资料并完成登录。',
  'auth.oauthAuthorizeHeading': '授权第三方站点',
  'auth.oauthAuthorizeIntro': '你即将决定是否允许第三方站点读取本站账号资料，并用它完成登录。',
  'auth.oauthLoadingRequest': '正在读取授权请求...',
  'auth.thirdPartyApp': '第三方应用',
  'auth.oauthAppNumber': 'OAuth 应用编号',
  'auth.copyAppNumberTitle': '复制应用编号',
  'auth.copyOAuthAppNumberAria': '复制 OAuth 应用编号',
  'auth.scopesToRead': '本次将读取',
  'auth.reportApp': '举报此应用',
  'auth.deny': '拒绝',
  'auth.allowAndContinue': '允许并继续',

  // OAuth 安全验证页
  'auth.seoOAuthVerifyTitle': '第三方登录安全验证',
  'auth.seoOAuthVerifyDescription': '完成人机验证后继续第三方账号登录流程，保护登录安全。',
  'auth.securityVerifyTitle': '安全验证',
  'auth.securityVerifyIntro': '完成这一步后，将继续回到第三方登录流程，不需要重新开始。',
  'auth.completeVerifyAndContinue': '完成验证并继续',

  // OAuth 回调页
  'auth.seoOAuthCallbackTitle': '登录中...',
  'auth.oauthCallbackProcessing': '登录处理中，请稍候...',
} as const;
