/** Generated from the legacy i18n module during the directory migration. */
export default {
'common.language': '语言',
  'common.search': '搜索',
  'common.login': '登录',
  'common.register': '注册',
  'common.home': '首页',
  'common.menu': '菜单',
  'common.close': '关闭',
  'nav.forum': '论坛',
  'nav.resources': '资源',
  'nav.community': '社区',
  'nav.explore': '探索',
  'nav.shop': '商店',
  'nav.rankings': '排行榜',
  'nav.hotTags': '热门标签',
  'nav.authors': '创作者',
  'nav.collections': '合集',
  'nav.docs': '文档库',
  'nav.campaigns': '活动',
  'nav.discover': '发现',
  'nav.players': '找服玩',
  'nav.video': '视频区',
  'nav.organizations': '组织',
  'nav.verificationCenter': '认证中心',
  'nav.notifications': '通知',
  'nav.messageCenter': '消息',
  'nav.latestDiscussions': '最新讨论',
  'nav.newPost': '发布帖子',
  'nav.allBoards': '查看全部板块',
  'nav.resourceArea': '资源区',
  'nav.allResources': '查看全部资源',
  'nav.javaResources': 'Java 资源',
  'nav.bedrockResources': '基岩版资源',
  'nav.universalResources': '通用资源',
  'nav.publishResource': '发布资源',
  'nav.manageMyResources': '管理我的资源',
  'nav.premiumServers': '正版验证服务器',
  'nav.offlineServers': '离线可进服务器',
  'nav.publishServer': '发布服务器',
  'nav.allServers': '查看全部服务器',
  'nav.videoArea': '视频区',
  'nav.allVideos': '查看全部视频',
  'nav.organizationSquare': '组织广场',
  'nav.createOrganization': '创建组织',
  'nav.myOrganizations': '我的组织',
  'nav.allOrganizations': '查看全部组织',
  'nav.publish': '投稿',
  'nav.submitVideo': '投稿视频',
  'nav.personal': '个人',
  'nav.myProfile': '我的主页',
  'nav.myFavorites': '我的收藏',
  'nav.history': '浏览历史',
  'nav.creationMessages': '创作与消息',
  'nav.creatorWorkbench': '创作者工作台',
  'nav.pendingContent': '待审核内容',
  'nav.myTasks': '我的任务',
  'nav.abilityCenter': '能力中心',
  'nav.messages': '私信',
  'nav.settings': '设置',
  'nav.appearance': '外观设置',
  'nav.accountSettings': '账号设置',
  'nav.adminPanel': '管理面板',
  'nav.viewProfile': '查看主页',
  'nav.logout': '退出登录',
  'nav.pending': '待完成',
  'nav.member': '社区成员',
  'nav.admin': '管理员',
  'nav.moderator': '版主',
  'nav.resourceModerator': '资源版主',
  'nav.forumModerator': '论坛版主',
  'nav.playerModerator': '服务器版主',
  'search.placeholder': '搜索帖子、资源或用户...',
  'search.recent': '最近搜索',
  'search.clear': '清空',
  'search.empty': '暂无搜索记录',
  'footer.brandCopy': '一个面向 Minecraft 创作者与玩家的社区。',
  'footer.currentLanguage': '当前语言',
  'footer.sections': '页脚导航',
  'footer.subscribe': '订阅',
  'footer.subscriptionCenter': '订阅中心',
  'footer.sitemap': '站点地图',
  'footer.extra': '页脚扩展信息',
  'footer.backHome': '返回首页',
  'footer.backToTop': '返回顶部',
  'footer.poweredBy': '由',
  'footer.legal': '"Minecraft" 以及 "我的世界" 为 Mojang Synergies AB 的商标，本站与 Mojang 以及 Microsoft 没有从属关系',
  'cookie.learn': '您可以了解为什么需要 cookie 并阅读',
  'cookie.rulesHere': '规则在这里',
  'cookie.text': '我们使用 Cookie 来改善浏览体验并分析站点流量。',
  'cookie.acceptAll': '全部接受',
  'cookie.essentialOnly': '仅必要',
  'seo.defaultSiteName': 'MC 论坛',
  'seo.defaultDescription': 'Minecraft 资源分享社区',
  'common.loading': '加载中...',
  'common.loadFailed': '加载失败',
  'common.retry': '重试',
  'common.save': '保存',
  'common.saving': '保存中...',
  'common.cancel': '取消',
  'common.confirm': '确认',
  'common.submit': '提交',
  'common.delete': '删除',
  'common.edit': '编辑',
  'common.back': '返回',
  'common.more': '查看更多',
  'common.empty': '暂无数据',
  'common.prevPage': '上一页',
  'common.nextPage': '下一页',
  'common.total': '共 {count} 条',
  'common.filter': '筛选',
  'common.reset': '重置',
  'common.all': '全部',
  'common.required': '必填',
  'common.optional': '可选',
} as const;
