/** Generated from the legacy i18n module during the directory migration. */
export default {
// ===== 通用 =====
  'forum.apply': '应用',
  'forum.loadMore': '加载更多',
  'forum.remove': '移除',
  'forum.clear': '清除',
  'forum.unnamed': '未命名',
  'forum.unset': '未设置',
  'forum.boardFallback': '板块',
  'forum.unnamedBoard': '未命名板块',
  'forum.unnamedPost': '未命名帖子',
  'forum.noDescription': '暂无描述',
  'forum.unknownUser': '未知用户',
  'forum.communityUser': '社区用户',
  'forum.organizationFallback': '组织',
  'forum.viewAll': '查看全部',
  'forum.pinned': '置顶',
  'forum.highlighted': '精华',
  'forum.featured': '精选',
  'forum.homeFeatured': '首页精选',
  'forum.enterBoard': '进入板块',
  'forum.postsUnit': '帖子',
  'forum.postsCountSuffix': '个帖子',
  'forum.reply': '回复',
  'forum.viewsCount': '{count} 浏览',
  'forum.repliesCount': '{count} 回复',
  'forum.publishedAt': '发布于 {time}',
  'forum.updatedAt': '更新于 {time}',
  'forum.activityAt': '活跃于 {time}',
  'forum.newPostsNotice': '查看 {count} 个新的或更新的帖子',
  'forum.newTopicsNotice': '查看 {count} 个新的或更新的主题',
  'forum.topicsUnit': '主题',
  'forum.breadcrumbHome': '首页',
  'forum.breadcrumbForum': '论坛',
  'forum.relativeTime.justNow': '刚刚',
  'forum.relativeTime.minutes': '{count} 分钟前',
  'forum.relativeTime.hours': '{count} 小时前',
  'forum.relativeTime.days': '{count} 天前',
  'forum.reportStatus.pending': '待处理',
  'forum.reportStatus.investigating': '处理中',
  'forum.reportStatus.resolved': '已处理',
  'forum.reportStatus.rejected': '已驳回',
  'forum.role.admin': '管理员',
  'forum.role.moderator': '版主',
  'forum.role.player_mod': '找服玩版主',
  'forum.role.resource_mod': '资源版主',
  'forum.role.forum_mod': '论坛版主',
  'forum.role.video_mod': '视频版主',
  'forum.role.user': '会员',

  // ===== 分页 / 合集筛选 =====
  'forum.collectionLabel': '收录合集：',
  'forum.collectionFilterTitle': '帖子收录筛选',
  'forum.collectionEmpty': '暂无包含帖子的合集',

  // ===== 论坛首页 SEO =====
  'forum.seo.homeTitle': '论坛',
  'forum.seo.homeDesc1': '进入 Minecraft 中文论坛',
  'forum.seo.homeDesc2': '浏览推荐板块、最新帖子与持续更新的社区讨论',
  'forum.seo.homeDesc3': '讨论游戏经验、服务器运营、插件模组和其他玩家话题',
  'forum.seo.homeDescFallback': 'Minecraft 中文论坛，浏览推荐板块与最新帖子。',
  'forum.seo.homeKeywords': 'Minecraft 论坛,MC 社区论坛,我的世界论坛,MC 讨论区,服务器交流,插件模组讨论',
  'forum.seo.jsonLdFeaturedBoards': '论坛精选板块',
  'forum.seo.jsonLdLatestTopics': '论坛最新话题',
  'forum.seo.keywordMinecraftForum': 'Minecraft 论坛',
  'forum.seo.keywordCommunityPost': '社区帖子',

  // ===== 论坛首页 =====
  'forum.featuredBoards': '精选板块',
  'forum.featuredBoardsDesc': '浏览推荐板块，选择合适的讨论区查看或发布话题。',
  'forum.viewNewTopics': '查看新话题',
  'forum.viewAllBoards': '查看全部板块',
  'forum.latestTopics': '最新话题',
  'forum.latestTopicsDesc': '按发布时间查看社区最新话题。',
  'forum.mcTip': 'MC 小贴士',
  'forum.mcTipRefresh': '刷新 MC 小贴士',
  'forum.mcTipAnother': '换一条小贴士',
  'forum.onlineUsers': '在线用户',
  'forum.communityStats': '社区统计',
  'forum.hotTags': '热门标签',

  // ===== 板块列表页 SEO =====
  'forum.seo.boardsTitle': '论坛板块',
  'forum.seo.boardsDesc1': '浏览完整的 Minecraft 论坛板块目录',
  'forum.seo.boardsDesc2': '快速进入你感兴趣的讨论区、技术区与社区专区',
  'forum.seo.boardsDesc3': '查看各板块定位、主题方向与发帖交流入口',
  'forum.seo.boardsDescFallback': 'Minecraft 论坛板块目录与讨论区总览',
  'forum.seo.boardsKeywords': 'Minecraft 论坛板块,MC 板块总览,我的世界论坛目录,MC 讨论区导航,论坛版块列表',
  'forum.seo.boardsJsonLdList': '论坛板块列表',

  // ===== 板块列表页 =====
  'forum.boardsOverviewTitle': '论坛板块总览',
  'forum.boardsOverviewDesc': '按板块浏览整个论坛目录，快速找到适合发帖与讨论的位置。',
  'forum.backToForumHome': '返回论坛首页',
  'forum.boardsSummaryFeatured': '当前共 {total} 个论坛板块，其中 {featured} 个会展示在论坛首页精选区域。',
  'forum.boardsSummaryNone': '当前共 {total} 个论坛板块，暂未设置首页精选板块。',
  'forum.boardsEmpty': '当前还没有可浏览的论坛板块。',
  'forum.boardsLoadFailed': '论坛板块加载失败，请稍后重试。',

  // ===== 板块详情页 SEO =====
  'forum.seo.boardPageTitle': '论坛板块 {board}',
  'forum.seo.boardBrowseTitle': '论坛板块浏览页',
  'forum.seo.boardDescDefault': '浏览论坛板块的最新帖子、热门讨论、发帖入口与持续更新的社区互动内容。',
  'forum.seo.boardDefaultKeywords': 'Minecraft 论坛板块,MC 讨论区,论坛帖子列表',
  'forum.seo.boardDiscussionSuffix': '{board}板块讨论区',
  'forum.seo.boardKeywordBoard': '{board}板块',
  'forum.seo.boardKeywordForum': '{board} 论坛',
  'forum.seo.boardKeywordDiscussion': '{board} 讨论',
  'forum.seo.boardKeywordExperience': '{board} 经验分享',
  'forum.seo.boardKeywordHotPosts': '{board} 热门帖子',
  'forum.seo.boardKeywordLatestPosts': '{board} 最新帖子',
  'forum.seo.keywordMcCommunityDiscussion': 'MC 社区讨论',
  'forum.seo.boardDescBrowse': '浏览{board}板块的帖子、经验分享与社区讨论',
  'forum.seo.boardDescHot': '当前按最多回复查看 {board} 板块热门讨论',
  'forum.seo.boardDescLatest': '当前按最新发布查看 {board} 板块主题更新',
  'forum.seo.boardDescPage': '当前为第 {page} 页板块列表',
  'forum.seo.boardDescOverview': '查看 {board} 板块的最新主题、热门回复与发帖入口',
  'forum.seo.boardDescFallback': '{board}板块的最新帖子与讨论内容',
  'forum.seo.boardJsonLdPosts': '{board}帖子列表',
  'forum.seo.boardJsonLdTopics': '{board}话题分类',
  'forum.seo.topicFallback': '话题 {index}',

  // ===== 板块详情页 =====
  'forum.boardInfo': '板块信息',
  'forum.postCount': '帖子总数',
  'forum.publishPost': '发布帖子',
  'forum.noPostPermission': '你当前的权限不能在该板块发帖',
  'forum.emptyPosts': '暂无帖子',
  'forum.emptyPostsInCollection': '该合集下暂无帖子',
  'forum.emptyTopics': '暂无主题',
  'forum.emptyTopicsInCollection': '该合集下暂无主题',
  'forum.emptyBoards': '暂无板块',
  'forum.sortLatest': '最新发布',
  'forum.sortMostReplies': '最多回复',
  'forum.viewNewPosts': '查看新帖子',
  'forum.rules': '板块规则',
  'forum.ruleFriendly': '保持友善，尊重他人',
  'forum.ruleNoIllegal': '禁止发布违法内容',
  'forum.ruleNoSpam': '禁止广告和垃圾信息',
  'forum.ruleGoodTitle': '使用合适的标题',

  // ===== 帖子详情页 SEO =====
  'forum.seo.postTitle': '帖子详情',
  'forum.seo.postBoard': '板块：{name}',
  'forum.seo.postTopicTags': '话题分类：{names}',
  'forum.seo.postTags': '话题：{names}',
  'forum.seo.postPublisher': '发布方：{name}',
  'forum.seo.postReplies': '{count} 条回复',
  'forum.seo.postViews': '{count} 次浏览',
  'forum.seo.postDescLine': '查看帖子全文、回复讨论与社区互动详情',
  'forum.seo.postDescFallback': '查看帖子全文、回复内容与社区讨论',
  'forum.seo.postUnavailableTitle': '帖子暂时不可用',
  'forum.seo.postNotFoundTitle': '帖子不存在',
  'forum.seo.postUnavailableDesc': '帖子详情暂时无法加载，请稍后重试。',
  'forum.seo.postNotFoundDesc': '该帖子不存在、已删除或暂不可公开访问。',
  'forum.seo.postJsonLdCollection': '论坛',

  // ===== 帖子详情页 =====
  'forum.postUnavailable': '该帖子暂时不可用。',
  'forum.quoteReply': '回复 {target}',
  'forum.quoteReplyWithPreview': '回复 {target}：{preview}',
  'forum.noReplies': '还没有评论和回复',
  'forum.noRepliesDesc': '现在还没有人参与讨论，来发表第一条回复吧。',
  'forum.moderationSubjectPost': '此帖子',
  'forum.moderationResubmitting': '此帖子已修改，正在重新提交审核中，仅你和管理员可见',
  'forum.continueEditing': '继续编辑',
  'forum.editAndResubmit': '编辑并重新提交',
  'forum.moderationResubmitFootnote': '修改保存后会自动重新提交审核流程。',
  'forum.publisherLabel': '发布方：{name}',
  'forum.authorLabel': '作者：{name}',
  'forum.repliesTitle': '评论和回复',
  'forum.replySortLabel': '评论排序',
  'forum.sortHot': '最热',
  'forum.sortNew': '最新',
  'forum.replyComposerLabel': '回复编辑器',
  'forum.replyComposerKicker': '回复主题',
  'forum.replyComposerKickerComment': '回复评论',
  'forum.replyComposerTitle': '写下你的回复',
  'forum.closeReplyComposer': '关闭回复编辑器',
  'forum.closePrompt': '关闭提示',
  'forum.discard': '舍弃',
  'forum.submitReply': '发表回复',
  'forum.relatedPosts': '相关帖子',
  'forum.loginPromptEyebrow': '登录后继续参与讨论',
  'forum.loginPromptTitle': '登录即可回复、接收通知，并继续上次阅读位置',
  'forum.loginPromptDesc': '账号登录后可以更顺畅地追帖互动，不会错过新的回复。',
  'forum.loginPromptBenefits': '登录后可用功能',
  'forum.loginBenefitHistory': '记录阅读进度',
  'forum.loginBenefitNotify': '接收新回复通知',
  'forum.loginBenefitJoin': '立即参与讨论',
  'forum.registerAccount': '注册账号',
  'forum.loginNow': '立即登录',
  'forum.postInfo': '帖子信息',
  'forum.tocTitle': '本页目录',
  'forum.resourceDocNav': '资源文档导航',
  'forum.resourceDocKicker': '资源文档',
  'forum.resourceDocTitle': '文档目录',
  'forum.resourceDocLoading': '正在加载资源文档...',
  'forum.reportTitle': '举报内容',
  'forum.reportReason': '举报原因',
  'forum.reportReasonPlaceholder': '选择举报原因',
  'forum.reportDetail': '具体详情（选填）',
  'forum.reportDetailPlaceholder': '可补充具体情况，方便管理员核查',
  'forum.submitReport': '提交举报',
  'forum.wechatShare': '微信分享',
  'forum.wechatShareDesc': '请复制链接后在微信中分享给好友',
  'forum.copy': '复制',
  'forum.editHistoryTitle': '帖子编辑历史',
  'forum.editHistoryDesc': '按时间倒序记录帖子内容、标题和发布设置的变化',
  'forum.editHistoryLoading': '正在加载编辑历史...',
  'forum.editHistoryEmpty': '暂时还没有记录到编辑历史',
  'forum.accessPasswordTitle': '本次访问需要验证口令',
  'forum.accessPasswordDesc': '请输入发布者设置的访问口令，验证通过后即可查看隐藏内容。',
  'forum.accessPasswordPlaceholder': '请输入访问口令',
  'forum.viewUserProfile': '查看 {user} 的主页',
  'forum.acceptedAnswer': '最终解答',
  'forum.floorTitle': '第 {floor} 楼',
  'forum.locateQuoteReply': '定位到引用回复 #{floor}',
  'forum.locateQuoteReplyAria': '定位到引用回复：{summary}',
  'forum.acceptAsAnswer': '采纳为最终解答',
  'forum.imageAltActivityCover': '活动封面预览',
  'forum.deletePostTitle': '删除帖子',
  'forum.confirmDeletePost': '确定要删除这篇帖子吗？',
  'forum.deleteReplyTitle': '删除回复',
  'forum.confirmDeleteReply': '确定要删除这条回复吗？',
  'forum.targetLabelReply': '回复',
  'forum.toastLoginToReply': '请先登录后回复',
  'forum.toastReplyNotAllowed': '当前帖子暂不允许回复',
  'forum.toastReplyContentRequired': '请输入回复内容',
  'forum.toastReplyFailed': '回复失败',
  'forum.toastReplyPending': '回复已提交审核',
  'forum.toastReplyPublished': '回复已发布',
  'forum.toastReplyDeleted': '回复已删除',
  'forum.toastRepliesLoadFailed': '评论加载失败，请重试',
  'forum.toastAnswerAccepted': '已采纳这条回复为最终解答',
  'forum.toastAcceptFailed': '采纳失败',
  'forum.toastDeleteFailed': '删除失败',
  'forum.toastActionFailed': '操作失败，请重试',
  'forum.submitting': '提交中...',
  'forum.toastPasswordRequired': '请输入访问口令',
  'forum.toastPasswordInvalid': '口令验证失败',
  'forum.toastDeleteSuccessBackToForum': '删除成功，正在返回论坛',

  // ===== 回复操作 / 举报 =====
  'forum.replyActions': '回复操作',
  'forum.like': '点赞',
  'forum.more': '更多',
  'forum.moreCommentActions': '更多评论操作',
  'forum.reportComment': '举报此评论或回复',
  'forum.deleteComment': '删除此评论',

  // ===== 发帖 / 编辑表单 =====
  'forum.seo.newTitle': '发布新帖子',
  'forum.seo.newDesc': '在选定板块中创建新帖子，填写标题、正文、标签与可见范围设置。',
  'forum.seo.editTitle': '编辑已有帖子',
  'forum.seo.editDesc': '修改帖子标题、正文、标签、可见范围与版权声明等发布内容。',
  'forum.publishActionLabel': '发布',
  'forum.editActionLabel': '编辑',
  'forum.contentLabelPost': '帖子',
  'forum.newPostHeading': '发布帖子',
  'forum.newPostSubtitle': '选择投稿入口，再填写帖子内容与发布设置。保存草稿后可以从创作者工作台继续完善。',
  'forum.editPostHeading': '编辑帖子',
  'forum.editReviewNotice': '已发布或已拒绝的帖子在保存修改后都会重新提交审核；审核中的帖子也可以继续完善内容。',
  'forum.editReviewNoticeAdmin': '你正在以管理身份编辑帖子，保存后不会进入审核队列，将直接保持或变为已通过状态。',
  'forum.toastNoEditPermission': '没有权限编辑此帖子',
  'forum.selectBoard': '选择板块',
  'forum.selectBoardPlaceholder': '请选择板块',
  'forum.topicCategory': '话题分类',
  'forum.topicCategoryHelp': '可从此板块启用的话题分类里自由选择，最多 5 个，会显示在标题前。',
  'forum.topicSelectedCount': '已选择 {count} / 5',
  'forum.toastTopicLimit': '最多只能选择 5 个话题分类',
  'forum.postType': '帖子形式',
  'forum.postTypeDefault': '默认帖子',
  'forum.postTypeQa': '问答帖',
  'forum.postTypePoll': '投票帖',
  'forum.postTypeReference': '引用资源/找服玩帖',
  'forum.postTypeBadgeQa': '问答',
  'forum.postTypeBadgePoll': '投票',
  'forum.postTypeBadgeReference': '引用',
  'forum.postTypeBadgeReferenceGuide': '引用教程',
  'forum.qaRewardLabel': '采纳奖励（硬币）',
  'forum.qaRewardPlaceholder': '不设置则填 0',
  'forum.qaRewardHelp': '提问者采纳最终解答时，会从自己账户扣除并发给回答者。',
  'forum.referenceTarget': '引用对象',
  'forum.referenceTypeResource': '资源',
  'forum.referenceTypePlayer': '找服玩',
  'forum.referenceSearchPlaceholder': '搜索要引用的资源或找服玩',
  'forum.referenceHelp': '发布后会先展示该引用对象，并自动收录到它的“教程”页签；资源或找服玩管理者可在编辑页移除该教程收录。',
  'forum.referenceHelpEdit': '修改引用对象后，会同步调整对应资源或找服玩的教程收录。',
  'forum.pollMode': '投票模式',
  'forum.pollModeSingle': '单选投票',
  'forum.pollModeMultiple': '多选投票',
  'forum.pollMaxChoices': '多选最多可选',
  'forum.pollOptions': '投票选项',
  'forum.pollAddOption': '新增选项',
  'forum.pollOptionPlaceholder': '选项 {index}',
  'forum.pollRevealAt': '投票公示时间',
  'forum.pollRevealHelp': '留空则默认立即公示投票结果。',
  'forum.pollRewardPerVoter': '每位参与奖励（硬币）',
  'forum.pollRewardBudget': '奖励总预算（硬币）',
  'forum.pollRewardHelp': '参与奖励会按首次投票发放，总预算耗尽后新参与者将不再获得奖励。',
  'forum.eventInfo': '活动信息',
  'forum.eventInfoHelp': '该板块用于发布活动，请填写活动时间、地点和展示信息。',
  'forum.eventStartsAt': '开始时间',
  'forum.eventEndsAt': '结束时间',
  'forum.eventTitle': '活动标题',
  'forum.eventTitlePlaceholder': '留空则使用帖子标题',
  'forum.eventLocation': '地点',
  'forum.eventLocationPlaceholder': '线上 / 服务器 / 城市地点',
  'forum.eventLocationUrl': '地点链接',
  'forum.eventCoverImage': '封面图链接',
  'forum.eventUploadImage': '上传图片',
  'forum.eventCoverHelp': '支持上传封面图，也可以继续填写外部图片链接。',
  'forum.eventCapacity': '名额',
  'forum.eventCapacityPlaceholder': '不限则留空',
  'forum.eventRsvpEnabled': '开启报名入口',
  'forum.eventRsvpHelp': '当前版本先展示标记，报名名单可后续继续接入。',
  'forum.eventSummary': '活动摘要',
  'forum.eventSummaryPlaceholder': '简短说明活动内容、参与方式或奖励',
  'forum.postTitleLabel': '帖子标题',
  'forum.postTitlePlaceholder': '输入帖子标题',
  'forum.postContentLabel': '帖子内容',
  'forum.tagsLabel': '标签',
  'forum.tagsHint': '(最多 20 个，按回车添加)',
  'forum.tagsPlaceholder': '输入标签名称，按回车添加',
  'forum.toastTagExists': '标签已存在',
  'forum.tagUsageCount': '{count} 次使用',
  'forum.visibility': '可见范围',
  'forum.visibilityPublic': '公开',
  'forum.visibilityVerify': '验证访问',
  'forum.visibilityPartial': '允许部分人可见',
  'forum.visibilityPrivate': '未公开（仅自己与管理组可见）',
  'forum.accessMode': '验证方式',
  'forum.accessModePassword': '口令认证',
  'forum.accessModeReply': '回复后可见',
  'forum.accessModeLogin': '登录后可见',
  'forum.accessModeHelp': '验证访问不会隐藏标题和回复区，只限制帖子正文查看。',
  'forum.accessPasswordLabel': '访问口令',
  'forum.accessPasswordNewPlaceholder': '请输入 4-64 位访问口令',
  'forum.accessPasswordTip': '只有输入正确口令后才能查看帖子正文。',
  'forum.accessPasswordKeepPlaceholder': '留空表示保持当前口令，重新填写则会更新口令',
  'forum.accessPasswordKeepTip': '如果帖子已启用口令认证，可以留空保持原口令。',
  'forum.visibilityAllowIds': '允许查看的用户 ID（逗号分隔）',
  'forum.visibilityAllowIdsPlaceholder': '例如：user-id-1,user-id-2',
  'forum.visibilityAllowIdsHelp': '管理员、总版主、论坛版主始终可见。',
  'forum.paidArticleSettings': '付费文章设置',
  'forum.paidArticleSettingsHelp': '付费文章与普通主题共用发布入口，购买后查看完整正文。',
  'forum.paidArticleEnable': '开启付费文章',
  'forum.paidArticleEnableHelp': '发布后价格和预览比例可以在管理员编辑页调整。',
  'forum.paidArticlePrice': '文章售价（元）',
  'forum.paidArticlePricePlaceholder': '例如：9.90',
  'forum.paidArticlePriceRange': '允许范围 ¥0.01 - ¥100000.00。',
  'forum.paidArticlePreviewPercent': '免费预览比例（%）',
  'forum.paidArticleAssetsHelp': '图片、视频、音频和附件仍需购买后查看。',
  'forum.paidArticleReaderAmount': '读者支付',
  'forum.paidArticlePlatformAmount': '用户收入',
  'forum.paidArticlePreviewLabel': '购买前说明',
  'forum.paidArticlePreviewPlaceholder': '简要说明文章内容和适合的读者',
  'forum.paidArticleTutorial': '发布小教程',
  'forum.paidArticleAgreement': '付费文章收费标准与发布协议',
  'forum.paidArticleAgreementCheckbox': '我已阅读并同意以上收费标准与付费文章发布协议',
  'forum.paidArticleNote': '付费文章必须保持公开可见，且不能同时启用其他正文访问验证。',
  'forum.copyrightEnable': '添加版权声明',
  'forum.copyrightEnableHelp': '在帖子底部显示版权信息和许可证',
  'forum.copyrightLicense': '许可证类型',
  'forum.licenseCcBy': '署名 4.0 国际 (CC BY 4.0)',
  'forum.licenseCcBySa': '署名-相同方式共享 4.0 国际 (CC BY-SA 4.0)',
  'forum.licenseCcByNc': '署名-非商业性使用 4.0 国际 (CC BY-NC 4.0)',
  'forum.licenseCcByNcSa': '署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)',
  'forum.licenseCcByNcSaShort': '署名-非商业性使用-相同方式共享 4.0 国际',
  'forum.licenseCcByNd': '署名-禁止演绎 4.0 国际 (CC BY-ND 4.0)',
  'forum.licenseCcByNcNd': '署名-非商业性使用-禁止演绎 4.0 国际 (CC BY-NC-ND 4.0)',
  'forum.licenseCcByNcNdShort': '署名-非商业性使用-禁止演绎 4.0 国际',
  'forum.licenseCc0': 'CC0 1.0 公共领域贡献',
  'forum.licenseArr': '保留所有权利 (All Rights Reserved)',
  'forum.copyrightPreviewTitle': '帖子标题',
  'forum.copyrightPreviewLink': '发布后生成链接',
  'forum.copyrightAuthor': '著者',
  'forum.copyrightAuthorFallback': '作者',
  'forum.copyrightDate': '公开日',
  'forum.copyrightToday': '今天',
  'forum.copyrightLicenseLabel': '许可证',
  'forum.saveDraft': '保存草稿',
  'forum.saveChanges': '保存修改',
  'forum.restoreDraft': '恢复草稿',
  'forum.discardDraft': '丢弃',
  'forum.draftDetectedPrefix': '检测到未发布的草稿（',
  'forum.draftDetectedSuffix': '）',
  'forum.selectDraftToRestore': '选择要恢复的草稿',
  'forum.unnamedDraft': '未命名草稿',
  'forum.draftBoardLabel': ' | 板块 {board}',
  'forum.toastDraftRestored': '草稿已恢复',
  'forum.toastDraftSaved': '草稿已保存，可继续编辑',
  'forum.toastDraftSaveFailed': '保存草稿失败',
  'forum.toastDraftDeleted': '草稿已删除',
  'forum.toastDraftCleared': '草稿已清除',
  'forum.draftCloudEqual': '当前已加载云端草稿。',
  'forum.draftLocalEqual': '当前本地缓存与云端草稿一致。',
  'forum.draftCloudFresh': '云端草稿比本地缓存更新，当前页面已加载云端版本。',
  'forum.draftLocalFresh': '检测到本地缓存比当前云端草稿更新，请留意是否需要手动恢复本地版本。',

  // ===== 发帖 / 编辑校验与提交 =====
  'forum.checking': '检查中...',
  'forum.publishing': '发布中...',
  'forum.toastSubmitChecking': '已收到发帖请求，正在检查内容与权限...',
  'forum.toastSaveChecking': '已收到保存请求，正在检查帖子内容...',
  'forum.toastProcessing': '正在处理',
  'forum.toastSavingTitle': '正在保存',
  'forum.toastPublishingTitle': '正在发布',
  'forum.toastPublishing': '帖子正在发布，我们会在完成后自动跳转。',
  'forum.toastEditSubmitting': '帖子修改正在提交，请稍候...',
  'forum.validationTitleRequired': '请填写标题',
  'forum.validationTitleMin': '标题至少需要 3 个字符',
  'forum.validationBoardRequired': '请选择板块',
  'forum.validationContentRequired': '请填写帖子内容',
  'forum.validationContentRequiredEdit': '请填写内容',
  'forum.validationContentMin': '帖子正文至少需要 {count} 个字',
  'forum.validationAllowIdsRequired': '请选择允许查看的用户 ID',
  'forum.validationEventStartRequired': '请填写活动开始时间',
  'forum.validationEventEndBeforeStart': '活动结束时间不能早于开始时间',
  'forum.validationPasswordRequired': '请输入访问口令',
  'forum.validationPaidMustBePublic': '付费文章必须设置为公开，且不能启用其他正文访问验证',
  'forum.validationPaidPriceInvalid': '请输入有效的文章售价，最多保留两位小数',
  'forum.validationPaidAgreement': '请阅读并同意付费文章收费标准与发布协议',
  'forum.validationPollMinOptions': '投票帖至少需要 2 个选项',
  'forum.validationPollMinChoices': '多选投票至少可选 2 项',
  'forum.validationPollBudget': '投票奖励总预算不能小于单次奖励',
  'forum.validationReferenceRequired': '请选择要引用的资源或找服玩',
  'forum.docTitleFormat': '[资源名]文档名',
  'forum.docTitleFormatError': '文档标题格式必须为「[资源名]文档名」',
  'forum.docTitleFormatHint': '标题格式：{format}，例如「[LuckPerms]安装与配置教程」',
  'forum.toastPostTooLarge': '帖子内容过大，请减少正文中直接粘贴的图片，或先把图片上传后再发布。',
  'forum.toastPublishSuccess': '发布成功，已进入审核队列',
  'forum.toastPublishFailed': '发布失败，请先登录',
  'forum.toastPostLoadFailed': '加载帖子失败',
  'forum.toastPostLoadFailedRetrySave': '{message}，请重新加载页面后再保存',
  'forum.toastPostUpdated': '帖子已更新',
  'forum.toastPostUpdatedApproved': '帖子已更新，状态已直接通过',
  'forum.toastPostResubmitted': '帖子已修改，正在重新提交审核中',
  'forum.toastSaveFailed': '保存失败',
  'forum.toastEditDataNotReady': '编辑数据尚未完整加载，请重新加载页面后再保存',
  'forum.toastPaidSettingsFailed': '正文已保存，但付费设置保存失败。当前输入已保留，请检查后重试付费设置。',
  'forum.toastPostTypeSwitched': '当前板块不允许该帖子类型，已自动切换为可用类型。',
  'forum.toastBoardPostDenied': '你当前的权限不能在该板块发帖，请选择其他板块。',
  'forum.toastBoardsLoadFailed': '加载板块列表失败',
  'forum.noBoardsAvailable': '暂无可发帖的板块',
  'forum.boardNoPermissionOption': '{board}（无发帖权限）',
  'forum.currentBoard': '当前板块',

  // ===== 投稿入口 =====
  'forum.submissionChannel': '投稿入口',
  'forum.submissionChannelSelect': '选择投稿入口',
  'forum.channelGeneral': '一般帖子',
  'forum.channelEvent': '活动',
  'forum.channelDocumentation': '文档',
  'forum.channelStatusGeneral': '普通板块投稿',
  'forum.channelStatusAuto': '自动发布到「{board}」板块',
  'forum.channelUnavailable': '当前入口暂不可投稿',

  // ===== 帖子编辑历史 =====
  'forum.historyField.title': '标题',
  'forum.historyField.content': '正文内容',
  'forum.historyField.boardId': '所属板块',
  'forum.historyField.tags': '标签',
  'forum.historyField.topicTags': '话题分类',
  'forum.historyField.topicTagId': '话题',
  'forum.historyField.topicTagName': '话题名称',
  'forum.historyField.visibility': '可见范围',
  'forum.historyField.visibilityAllowUserIds': '指定可见用户',
  'forum.historyField.accessMode': '访问方式',
  'forum.historyField.copyrightEnabled': '版权声明',
  'forum.historyField.copyrightLicense': '版权协议',
  'forum.historyDiffEmpty': '正文为空或未解析到可展示文本',
  'forum.historyDiffSkipped': '省略 {count} 行未变化内容',
  'forum.historyDiffAdd': '新增',
  'forum.historyDiffRemove': '删除',
  'forum.historyDiffUnchanged': '未变',
  'forum.historyCharNoChange': '字数无变化',
  'forum.historyCharDelta': '{delta} 字',
  'forum.historyContentTitle': '正文内容',
  'forum.historyContentNote': '可展开查看文本差异',
  'forum.historyContentStatsLabel': '正文变化摘要',
  'forum.historyBeforeChars': '修改前 {count} 字',
  'forum.historyAfterChars': '修改后 {count} 字',
  'forum.historyLineChanges': '新增 {added} 行 / 删除 {removed} 行',
  'forum.historyViewDiff': '查看正文差异',
  'forum.historyApproxChars': '约 {count} 字',
  'forum.historyEmptyContent': '空正文',
  'forum.historyNoTags': '未设置标签',
  'forum.historyUserCount': '{count} 个指定用户',
  'forum.historyNoUsers': '未指定用户',
  'forum.historyVisibilityPublic': '公开可见',
  'forum.historyVisibilityPartial': '指定用户可见',
  'forum.historyVisibilityPrivate': '仅自己可见',
  'forum.historyAccessNone': '无需额外验证',
  'forum.historyAccessLogin': '登录后可见',
  'forum.historyAccessReply': '回复后可见',
  'forum.historyAccessPassword': '口令访问',
  'forum.historyEnabled': '已开启',
  'forum.historyDisabled': '已关闭',
  'forum.historyNoLicense': '未设置协议',
  'forum.historyUpdatedPost': '更新了帖子',
  'forum.historyUpdatedOne': '更新了{field}',
  'forum.historyUpdatedMany': '更新了 {count} 项：{fields}',
  'forum.historyUpdatedManyMore': ' 等 {count} 项',
  'forum.historyNoDetail': '这条记录没有可展示的字段明细',
  'forum.historyBefore': '修改前',
  'forum.historyAfter': '修改后',
  'forum.historyContentDefaultNote': '正文内容默认显示摘要，展开后可查看修改前后的文本差异。',

  // ===== 问答 / 投票帖 =====
  'forum.postTypeSolved': '已解决',
  'forum.qaSolved': '已采纳最终解答',
  'forum.qaSolvedDesc': '提问者已经选择了一条回复作为最终解答。',
  'forum.qaOpenDesc': '提问者可以从回复中选择一条作为最终解答。',
  'forum.qaRewardValue': '采纳奖励：{value}',
  'forum.qaRewardCoins': '{count} 硬币',
  'forum.voteCount': '{count} 票',
  'forum.pollResultHidden': '结果将在公示时间后显示',
  'forum.pollMultipleDesc': '多选投票，最多可选 {count} 项',
  'forum.pollVoterCount': '参与人数：',
  'forum.pollRewardLine': '参与奖励：{value}',
  'forum.pollRewardDetail': '{amount} 硬币 / 总预算 {budget}',
  'forum.pollRevealTime': '公示时间：{time}',
  'forum.pollRevealNow': '立即公示结果',
  'forum.submitVote': '提交投票',
  'forum.toastLoginToVote': '请先登录后再参与投票',
  'forum.toastSelectVoteOption': '请先选择投票项',
  'forum.toastVoteSubmitted': '投票已提交',
  'forum.toastVoteFailed': '投票失败',

  // ===== 微信支付 =====
  'forum.wechatCreatingOrder': '正在创建微信支付订单…',
  'forum.wechatQrMissing': '未获取到微信支付二维码',
  'forum.wechatModalTitle': '微信扫码支付',
  'forum.wechatModalDesc': '请使用微信扫描二维码完成支付，支付成功后点击下方按钮检查到账。',
  'forum.wechatQrAlt': '微信支付二维码',
  'forum.wechatCheckButton': '支付完成，检查订单',
  'forum.wechatChecking': '检查中…',
  'forum.wechatQuerying': '正在查询支付结果…',
  'forum.wechatConfirmed': '支付已确认，正在打开全文…',
  'forum.wechatNotDetected': '尚未检测到支付，请稍等片刻后再次检查。',
  'forum.wechatCheckFailed': '检查失败，请稍后重试。',
  'forum.wechatScanToPay': '请扫码完成支付',
  'forum.wechatOrderFailed': '支付下单失败，请稍后重试',
  'forum.docModeTitle': '以文档模式阅读这篇内容',

  // ===== 引用卡片 / 引用选择器 =====
  'forum.referenceLabel': '引用{target}',
  'forum.referenceOnline': '{online}/{max} 在线',
  'forum.viewTarget': '查看{target}',
  'forum.referenceNotSelected': '尚未选择引用对象',
  'forum.referenceSelectedFallback': '已选{label}',
  'forum.toastReferenceLoadFailed': '加载引用对象失败',

  // ===== 活动卡片 / 封面图上传 =====
  'forum.eventStatus.cancelled': '已取消',
  'forum.eventStatus.ended': '已结束',
  'forum.eventStatus.ongoing': '进行中',
  'forum.eventStatus.upcoming': '即将开始',
  'forum.eventFallbackTitle': '活动',
  'forum.eventCapacityCount': '{count} 人名额',
  'forum.eventCoverCleared': '已清除封面图',
  'forum.toastImageOnly': '只能上传图片文件',
  'forum.uploading': '上传中...',
  'forum.uploadingPercent': '正在上传 {percent}%',
  'forum.eventCoverUploadFailed': '封面图上传失败',
  'forum.eventCoverUploaded': '封面图上传完成',
  'forum.toastEventCoverUploaded': '活动封面上传成功',
  'forum.uploadFailed': '上传失败',

  // ===== 反馈进度状态 =====
  'forum.feedback.pending_discussion': '待讨论',
  'forum.feedback.todo': '待完成',
  'forum.feedback.in_progress': '处理中',
  'forum.feedback.completed': '已完成',
  'forum.feedback.not_bug': '非 bug',
  'forum.feedback.wontfix': '不采纳',
  'forum.feedback.duplicate': '重复建议',
  'forum.feedback.closed': '已关闭',
} as const;
