/** Generated from the legacy i18n module during the directory migration. */
export default {
// SEO
  'home.seoTitle': 'Minecraft 我的世界中文社区',
  'home.seoDescription1': '浏览 Minecraft 中文社区的最新资源、热门讨论与活跃板块',
  'home.seoDescription2': '分享插件、模组、整合包、材质包与服务器经验',
  'home.seoDescription3': '支持浏览资源下载、论坛交流、服务器收录与社区动态',
  'home.seoDescriptionFallback': 'Minecraft 中文资源分享与玩家交流社区',
  'home.seoKeyword1': 'Minecraft 中文论坛',
  'home.seoKeyword2': 'MC 资源社区',
  'home.seoKeyword3': '我的世界论坛',
  'home.seoKeyword4': 'MC 插件模组',
  'home.seoKeyword5': '服务器交流',

  // 结构化数据（JSON-LD）
  'home.jsonLdShowcaseName': '首页{title}',
  'home.jsonLdLatestResources': '首页最新资源',
  'home.jsonLdHotPosts': '首页热门讨论',
  'home.jsonLdHotBoards': '首页热门板块',
  'home.jsonLdLatestPlayers': '首页最新找服玩',
  'home.jsonLdLatestVideos': '首页最新视频',
  'home.jsonLdOrganizations': '首页组织',
  'home.jsonLdResourceDocs': '首页资源文档',
  'home.jsonLdResourceDocName': '{post} - {resource}',
  'home.jsonLdFallbackResourceDoc': '资源文档',
  'home.jsonLdFallbackResource': '资源',

  // 未命名 / 未知兜底
  'home.untitledContent': '未命名内容',
  'home.untitledResource': '未命名资源',
  'home.untitledPost': '未命名帖子',
  'home.untitledBoard': '未命名板块',
  'home.untitledPlayer': '未命名服务器',
  'home.untitledVideo': '未命名视频',
  'home.untitledOrganization': '未命名组织',
  'home.untitledTopic': '未命名主题',
  'home.unknownUser': '未知用户',
  'home.userAvatarAlt': '用户头像',
  'home.playerCoverAlt': '服务器封面',
  'home.uncategorized': '未分类',
  'home.noDescription': '暂无描述',

  // 分类展示（showcase）
  'home.showcaseDefaultResource': '资源随机推荐',
  'home.showcaseDefaultPlayer': '服务器随机推荐',
  'home.showcaseDefaultVideo': '视频随机推荐',
  'home.showcaseDefaultCard': '卡片展示',
  'home.resourceCategoryFallback': '资源分类',
  'home.playerCategoryFallback': '服务器分类',
  'home.videoCategoryFallback': '视频分类',
  'home.viewDetails': '查看详情',
  'home.allResources': '全部资源',
  'home.allPlayers': '全部服务器',
  'home.allVideos': '全部视频',
  'home.viewAllResourcesAria': '查看全部资源',
  'home.showcaseSelectorAria': '{title}快捷入口',
  'home.cardShowcaseAria': '首页卡片展示',

  // 横幅与轮播
  'home.bannerDefaultLabel': '每日推荐',
  'home.bannerDefaultTitle': '发现最好的 Minecraft 中文资源',
  'home.bannerDefaultSubtitle': '探索模组、整合包、光影和资源包，与玩家共建社区',
  'home.welcomeBannerTitle': '欢迎来到 {name}',
  'home.bannerDotAria': '切换到第 {index} 张横幅',
  'home.carouselPrev': '上一张',
  'home.carouselNext': '下一张',

  // 区块标题与入口
  'home.latestResourcesTitle': '最新资源',
  'home.hotDiscussionsTitle': '热门讨论',
  'home.hotBoardsTitle': '热门板块',
  'home.collectionsTitle': '收录合集',
  'home.collectionsTitleWithSelection': '收录合集 · {name}',
  'home.collectionsSelectLabel': '选择收录合集',
  'home.allCollections': '全部合集',
  'home.collectionsHistory': '历史合集',
  'home.mcTipTitle': 'MC 小贴士',
  'home.mcTipRefreshAria': '刷新 MC 小贴士',
  'home.mcTipRefreshTitle': '换一条小贴士',
  'home.viewAll': '查看全部',
  'home.checkInTitle': '每日打卡',
  'home.communityStatsTitle': '社区统计',
  'home.hotTagsTitle': '热门标签',
  'home.onlineUsersTitle': '在线用户',
  'home.mobileSidebarAria': '首页辅助功能',
  'home.resourceShortcutsAria': '资源快捷筛选',

  // 排行榜
  'home.rankingSuffix': '排行',
  'home.rankingTitleWithSuffix': '{title}排行',
  'home.rankingScopeFallback': '分类排行',
  'home.rankingSectionFallback': '排行',
  'home.rankingScopeAria': '{title}范围',
  'home.rankingMetricAria': '{title}类型',
  'home.rankingEmpty': '暂无排行数据',

  // 单位与数值
  'home.unitRating': '{n} 分',
  'home.unitDownloads': '{n} 下载',
  'home.unitTimes': '{n} 次',
  'home.unitDiscussions': '{n} 讨论',
  'home.unitViews': '{n} 浏览',
  'home.ratingUnavailable': '暂无',
  'home.onlineMode': '正版验证',
  'home.offlineMode': '离线可进',

  // 空状态与加载态
  'home.refreshRetryDesc': '请刷新页面后重试',
  'home.emptyResourcesTitle': '暂无资源',
  'home.emptyResourcesDesc': '当前还没有可展示的资源',
  'home.emptyCollectionResourcesTitle': '合集暂无资源',
  'home.emptyCollectionResourcesDesc': '该合集暂时没有可展示内容',
  'home.emptyHistoryCollections': '暂无历史合集',
  'home.moreCollectionsTip': '其余合集请前往收录合集总页查看',
  'home.emptyPostsTitle': '暂无讨论',
  'home.emptyPostsDesc': '当前还没有可展示的讨论',
  'home.emptyBoardsTitle': '暂无板块',
  'home.emptyBoardsDesc': '当前还没有可展示的热门板块',
  'home.emptyTopicsTitle': '暂无主题',
  'home.emptyHotTags': '暂无热门标签',
  'home.boardDescriptionFallback': '浏览该板块的活跃讨论内容。',
  'home.resourceDescriptionFallback': '浏览资源简介、适配版本与下载信息。',
  'home.postsLabel': '帖子',
  'home.repliesLabel': '回复',
  'home.postActiveAt': '活跃于 {time}',
  'home.postUpdatedAt': '更新于 {time}',
  'home.downloadLabel': '下载',
  'home.archived': '已归档',
  'home.justNow': '刚刚',

  // MC 小贴士默认内容（站点设置缺失时的兜底）
  'home.mcTip1': '用床可以快速跳过夜晚。',
  'home.mcTip2': '下矿时记得随身带一桶水。',
  'home.mcTip3': '跟着蜜蜂飞行方向，常能找到附近蜂巢。',
  'home.mcTip4': '利用下界通道能大幅缩短远距离路程。',
  'home.mcTip5': '给生物命名可以防止其自然消失。',

  // 每日打卡
  'home.checkInDoing': '打卡中...',
  'home.checkInDone': '已打卡',
  'home.checkInAction': '打卡',
  'home.checkInLoginText': '登录',
  'home.checkInLoginSuffix': ' 后可打卡',
  'home.checkInReward': '+{n} 活跃度到账',
  'home.checkInPointReward': ' · +{n} {name}',
  'home.checkInStreakSuffix': ' · 连续 {n} 天',
  'home.checkInToday': '今日打卡',
  'home.checkInStreak': '连续打卡',
  'home.checkInStreakDays': '{n} 天',
  'home.checkInStatus': '打卡状态',
  'home.checkInIncomplete': '未完成',
  'home.checkInVisitStatus': '访问状态',
  'home.checkInGuest': '游客',
  'home.defaultPointName': '硬币',

  // 社区统计
  'home.statsResources': '资源总数',
  'home.statsPosts': '帖子总数',
  'home.statsToday': '今日新发',
  'home.statsOnline': '在线人数',
  'home.statsUnavailable': '统计暂时不可用',

  // 在线用户
  'home.onlineUsersCount': '{n} 人',
  'home.onlineUsersLoading': '加载中',
  'home.onlineUsersUnavailable': '暂不可用',
  'home.onlineUsersFetchFailed': '暂时无法获取',
  'home.onlineUsersError': '在线用户暂时不可用',
  'home.onlineUsersEmpty': '暂无在线用户',
  'home.onlineUsersAria': '当前在线用户',
  'home.onlineUsersActive': '在线中',
  'home.onlineUsersRefreshedJustNow': '刚刚刷新',
  'home.onlineUsersRefreshedSeconds': '{n} 秒前刷新',
  'home.onlineUsersRefreshedMinutes': '{n} 分钟前刷新',
  'home.onlineUsersRefreshedHours': '{n} 小时前刷新',
} as const;
