/** Generated from the legacy i18n module during the directory migration. */
export default {
'players.seoTitle': '找服玩 - Minecraft 服务器收录',
  'players.seoDescription': '浏览 Minecraft 服务器目录，发现生存、空岛、小游戏、RPG 与更多玩法的优质服务器。',
  'players.seoDescriptionLine1': '收录 Java 版、基岩版 Minecraft 服务器',
  'players.seoDescriptionLine2': '支持按平台、分类、版本、正版验证与排序方式筛选浏览',
  'players.seoDescriptionLine3': '快速查看服务器特色玩法、状态信息与玩家反馈，找到想玩的社区服务器',
  'players.keywordServers': 'Minecraft 服务器',
  'players.keywordFind': 'MC 找服玩',
  'players.keywordMinecraft': '我的世界服务器',
  'players.keywordJava': 'Java 服务器',
  'players.keywordBedrock': '基岩版服务器',
  'players.keywordDirectory': '服务器收录',
  'players.allPlatforms': '全部平台',
  'players.sort': '排序方式',
  'players.latest': '最新发布',
  'players.updated': '最新更新',
  'players.views': '最多浏览',
  'players.score': '综合排序',
  'players.rating': '评分最高',
  'players.pageSize': '显示数量',
  'players.itemsPerPage': '{count} 条/页',
  'players.publish': '发布服务器',
  'players.filter': '筛选',
  'players.platform': '平台',
  'players.category': '分类',
  'players.version': '版本',
  'players.allCategories': '全部分类',
  'players.allVersions': '全部版本',
  'players.onlineMode': '正版验证',
  'players.enabled': '已开启',
  'players.disabled': '未开启',
  'players.enabledOnlineMode': '已开启正版验证',
  'players.disabledOnlineMode': '未开启正版验证',
  'players.collection': '服务器收录',
  'players.collectionSummary': '收录合集：{value}',
  'players.collectionLabel': '收录合集：',
  'players.viewCollections': '查看所有合集',
  'players.collectionFilterTitle': '服务器收录筛选',
  'players.reset': '重置',
  'players.cancel': '取消',
  'players.apply': '应用',
  'players.creator.publishTitle': '发布服务器',
  'players.creator.editTitle': '编辑服务器',
  'players.creator.publishDescription': '先说明服务器定位，再补连接、封面、教程和画廊。隐藏连接地址时，请同步提供申请入口或社群联系方式。',
  'players.creator.editDescription': '修改已发布或草稿中的服务器信息。',
  'players.creator.reviewNotice': '提交后会先进入服务器审核流程；审核通过后才会公开展示。如果审核未通过，按提示修改后可再次提交。',
  'players.creator.draftFound': '发现未完成的服务器草稿',
  'players.creator.draftHelp': '请选择要恢复的版本；暂不恢复不会清除草稿。恢复后将替换当前表单内容。',
  'players.creator.localDraft': '本地草稿',
  'players.creator.cloudDraft': '云端草稿',
  'players.creator.newerContent': '内容较新',
  'players.creator.unknownSaveTime': '保存时间未知',
  'players.creator.restoreLocal': '恢复本地草稿',
  'players.creator.restoreCloud': '恢复云端草稿',
  'players.creator.skipRestore': '暂不恢复',
  'players.creator.required': '必填',
  'players.creator.serverName': '服务器名称',
  'players.creator.serverNamePlaceholder': '例如：星港生存服',
  'players.creator.titleLimit': '最多 64 个字',
  'players.creator.intro': '简介',
  'players.creator.introPlaceholder': '一句话介绍服务器特色',
  'players.creator.platform': '平台',
  'players.creator.javaEdition': 'Java 版',
  'players.creator.bedrockEdition': '基岩版',
  'players.creator.category': '分类',
  'players.creator.chooseCategory': '请选择分类',
  'players.creator.supportedVersions': '支持版本',
  'players.creator.networkEnvironment': '网络环境',
  'players.creator.telecomNorth': '中国电信（北方）',
  'players.creator.telecomSouth': '中国电信（南方）',
  'players.creator.unicom': '中国联通',
  'players.creator.mobile': '中国移动',
  'players.creator.hmt': '港澳台',
  'players.creator.overseas': '海外',
  'players.creator.onlineVerification': '正版验证',
  'players.creator.onlineEnabled': '已开启正版验证',
  'players.creator.onlineDisabled': '未开启正版验证',
  'players.creator.tags': '标签',
  'players.creator.tagsPlaceholder': '输入标签，支持搜索已有标签',
  'players.creator.tagsHelp': '输入关键词可搜索已有标签，按回车键添加，点击标签可删除',
  'players.creator.address': '服务器地址/IP',
  'players.creator.port': '端口',
  'players.creator.hideAddress': '隐藏服务器连接地址',
  'players.creator.hideAddressHelp': '开启后，玩家通过验证只会看到申请入口和你填写的交流群信息。',
  'players.creator.joinUrl': '连接申请链接',
  'players.creator.joinUrlPlaceholder': 'https://example.com/join',
  'players.creator.joinUrlHelp': '这里只填写 http(s) 网页或公开邀请链接；QQ群号请填写下方“QQ群”。隐藏地址时，申请链接、QQ群或 Discord 至少填写一项。',
  'players.creator.website': '官网',
  'players.creator.cover': '服务器封面图',
  'players.creator.chooseCover': '选择封面图',
  'players.creator.coverHelp': '上传后统一裁剪为 16:9，支持 PNG、JPG、WebP，最大 2MB',
  'players.creator.coverUrlHelp': '上传后会自动填写封面图地址，也可手动粘贴外链',
  'players.creator.coverPlaceholder': 'https://... 或 /uploads/...',
  'players.creator.qq': 'QQ群',
  'players.creator.discord': 'Discord',
  'players.creator.details': '详细介绍',
  'players.creator.tutorialIndex': '服务器教程索引',
  'players.creator.tutorialPlaceholder': '搜索站内教程帖子标题并添加到此服务器',
  'players.creator.tutorialHelp': '这里收集与该服务器相关的教程帖子。详情页“教程”页签会按这里的索引展示。',
  'players.creator.gallery': '服务器画廊',
  'players.creator.galleryAuto': '自动检测介绍内的图片',
  'players.creator.galleryManual': '手动上传图片到画廊',
  'players.creator.galleryAutoHint': '发布后将自动提取详细介绍中的图片作为画廊展示',
  'players.creator.galleryEditAutoHint': '保存后将自动提取详细介绍中的图片作为画廊展示',
  'players.creator.galleryUpload': '点击或拖拽图片到此处上传',
  'players.creator.galleryFormatHelp': '支持 PNG、JPG、GIF、WebP 格式，每张最大 5MB，可多选',
  'players.creator.confirmBeforePublish': '发布前请确认',
  'players.creator.submit': '提交审核',
  'players.creator.saveDraft': '保存草稿',
  'players.creator.save': '保存修改',
  'players.creator.cancel': '取消',
  'players.creator.backToList': '返回列表',
} as const;
