/** Generated from the legacy i18n module during the directory migration. */
export default {
'profile.seoTitle': '用户中心',
  'profile.seoDescription': '集中查看账号状态、内容记录、任务进度、积分和创作信息。',
  'profile.nextStep': '下一步',
  'profile.continue': '继续',
  'profile.loginToView': '登录后查看用户中心',
  'profile.loginToViewHelp': '登录后会显示你的收藏、任务、资产和创作者状态。',
  'profile.continueTasks': '继续完成成长任务',
  'profile.taskProgressHelp': '当前任务进度 {done}/{total}，完成后可获得奖励并解锁更多社区能力。',
  'profile.unlockCapabilities': '解锁社区能力',
  'profile.unlockCapabilitiesHelp': '通过能力认证后，可逐步获得投币、评分、推广、API Token 等权限。',
  'profile.creatorTodo': '处理创作者待办',
  'profile.creatorTodoHelp': '当前有 {count} 个内容需要检查、修改或跟进审核状态。',
  'profile.openWorkbench': '进入创作者工作台',
  'profile.openWorkbenchHelp': '查看内容表现、发布入口和下一步创作建议。',
  'profile.noRecord': '暂无记录',
  'profile.account': '账号',
  'profile.username': '用户名',
  'profile.guest': '未登录用户',
  'profile.recentActivity': '最近活动',
  'profile.capabilities': '能力资格',
  'profile.items': '{count} 项',
  'profile.content': '内容',
  'profile.viewHistory': '查看历史',
  'profile.favorites': '收藏',
  'profile.favoriteSummary': '资源 {resources} · 帖子 {posts} · 找服玩 {players} · 视频 {videos}',
  'profile.browsingHistory': '浏览历史',
  'profile.returnToRecent': '继续回到最近浏览过的内容',
  'profile.growth': '成长',
  'profile.viewTasks': '查看任务',
  'profile.taskProgress': '任务进度',
  'profile.tasksComplete': '{done}/{total} 个任务完成',
  'profile.noTaskData': '暂无任务数据',
  'profile.notStarted': '待开始',
  'profile.abilityCenter': '能力中心',
  'profile.examsAvailable': '{count} 项可参加认证',
  'profile.assets': '资产',
  'profile.viewAssets': '查看资产',
  'profile.points': '积分',
  'profile.pointsSummary': '累计获得 {earned} · 累计支出 {spent}',
  'profile.noPointsAssets': '暂无积分资产',
  'profile.inventory': '道具库存',
  'profile.ownedItems': '已拥有 {count} 类道具',
  'profile.availableItems': '可购买 {count} 个道具',
  'profile.creation': '创作',
  'profile.openCreatorCenter': '进入创作者中心',
  'profile.creatorStatus': '创作者状态',
  'profile.creatorStatusHelp': '发布内容后会显示创作者状态',
  'profile.navigation': '用户中心导航',
  'profile.creatorCenter': '创作者中心',
} as const;
