/** Generated from the legacy i18n module during the directory migration. */
export default {
// ===== SEO：资源列表 =====
  'resources.seoListingDefaultTitle': 'Minecraft 资源下载与分享',
  'resources.seoListingDesc1': '浏览 Minecraft 插件、模组、材质包、地图与光影资源',
  'resources.seoListingDesc2': '支持按平台、分类和版本动态筛选与下载资源',
  'resources.seoListingDesc3': '覆盖 Java 版、基岩版与通用资源，持续更新热门作品与合集',
  'resources.seoListingDescFallback': 'Minecraft 资源下载与分享社区',
  'resources.seoListingTitleSuffix': 'Minecraft 资源下载',
  'resources.seoKeywordMinecraft': 'Minecraft 资源',
  'resources.seoKeywordPlugin': 'MC 插件',
  'resources.seoKeywordMod': 'MC 模组',
  'resources.seoKeywordTexture': '材质包下载',
  'resources.seoKeywordMap': '地图下载',
  'resources.seoListingPageTitle': '{title} - 第 {page} 页',
  'resources.seoDescOfficialTags': '官方分类：{names}',
  'resources.seoDescPlatform': '平台：{platform}',
  'resources.seoDescCategory': '分类：{category}',
  'resources.seoDescSubCategory': '子分类：{subCategory}',
  'resources.seoDescThirdLevel': '细分方向：{names}',
  'resources.seoDescVersion': '适用版本：{version}',
  'resources.seoDescCollection': '收录合集：{names}',
  'resources.seoDescSideSupport': '端支持：{side}',
  'resources.seoDescSort': '当前按{sort}浏览资源',
  'resources.seoDescPage': '当前为第 {page} 页资源列表',
  'resources.seoJsonLdItemList': '资源列表',
  'resources.seoJsonLdItemListTags': '{tags} 资源列表',
  'resources.seoJsonLdItemListDefault': 'Minecraft 资源列表',
  'resources.seoJsonLdItemListPlatform': '{platform}资源列表',
  'resources.seoJsonLdItemListPlatformCategory': '{platform} {category}资源列表',
  'resources.seoJsonLdItemListTagsPlatform': '{tags} {platform}资源列表',
  // ===== SEO：平台筛选页兜底 =====
  'resources.seoPlatformDesc1': '{platform} Minecraft 资源筛选列表',
  'resources.seoPlatformDescCover': '覆盖插件、模组、材质包、地图与光影',
  'resources.seoPlatformDescSub': '细分类型：{subCategory}',
  'resources.seoPlatformDescFilter': '支持按平台、分类、版本与收录条件筛选浏览资源',
  'resources.seoPlatformDescFallback': '浏览和下载 Minecraft 分类资源',

  // ===== SEO：资源详情 =====
  'resources.seoResourceCenter': '资源中心',
  'resources.seoDetailTitle': '{title} - 资源中心',
  'resources.seoDetailTitleWithTaxonomy': '{prefix} {title} - 资源中心',
  'resources.seoDetailDefaultTitle': '资源详情',
  'resources.seoDetailDescTags': '标签：{tags}',
  'resources.seoDetailDescDocs': '已整理 {count} 篇资源文档',
  'resources.seoDetailDescAuthor': '作者：{authors}',
  'resources.seoDetailDescTail': '查看下载说明、版本信息、更新记录与使用介绍',
  'resources.seoDetailDescFallback': '{title} 的下载说明、版本信息与使用介绍',
  'resources.seoDetailKeywordDoc': '{title} 文档',
  'resources.seoDetailKeywordTutorial': '{title} 教程',
  'resources.seoDetailKeywordDocs': '资源文档',
  'resources.seoDetailUnavailableTitle': '资源暂时不可用',
  'resources.seoDetailUnavailableDesc': '资源详情暂时无法加载，请稍后重试。',
  'resources.seoDetailMissingTitle': '资源不存在',
  'resources.seoDetailMissingDesc': '该资源不存在、已下架或暂不可公开访问。',
  'resources.seoJsonLdDocsList': '{title} 资源文档目录',
  'resources.seoJsonLdDocItem': '文档 {index}',
  'resources.seoJsonLdDocFallback': '资源文档',
  'resources.seoBreadcrumbResources': '资源',

  // ===== 平台/分类标题标签（SEO 与展示通用） =====
  'resources.taxonomyPlatformJava': 'Java版',
  'resources.taxonomyPlatformBedrock': '基岩版',
  'resources.taxonomyPlatformUniversal': '通用',
  'resources.taxonomyCategoryPlugin': '插件',
  'resources.taxonomyCategoryMod': '模组',
  'resources.taxonomyCategoryDatapack': '数据包',
  'resources.taxonomyCategoryTexture': '材质包',
  'resources.taxonomyCategoryShader': '光影',
  'resources.taxonomyCategoryMap': '地图',
  'resources.taxonomyCategoryModpack': '整合包',
  'resources.taxonomyCategoryBehaviorPack': '行为包',
  'resources.taxonomyCategoryUtility': '实用软件',
  'resources.taxonomyCategoryLauncher': '启动器',
  'resources.taxonomyCategoryServerPanel': '服务器面板',
  'resources.taxonomyCategorySkin': '皮肤',
  'resources.taxonomyCategoryPluginConfig': '插件配置包',
  'resources.taxonomyCategoryModConfig': '模组配置包',
  'resources.taxonomyCategoryModel': '模型',
  'resources.taxonomyCategoryProgramLauncher': '程序启动器',

  // ===== 资源列表页：卡片与空状态（SSR） =====
  'resources.emptyResources': '暂无资源',
  'resources.untitledResource': '未命名资源',
  'resources.cardDescriptionFallback': '浏览资源说明、版本支持与下载信息。',
  'resources.uncategorized': '未分类',
  'resources.unitDownloads': '{n} 下载',
  'resources.noRating': '暂无评分',
  'resources.archived': '已归档',
  'resources.viewDocumentation': '查看资源文档',

  // ===== 资源列表页：筛选与工具栏 =====
  'resources.filterAllPlatforms': '全部平台',
  'resources.sortLabel': '排序方式',
  'resources.sortLatest': '最新发布',
  'resources.sortUpdated': '最新更新',
  'resources.sortDownloads': '最多下载',
  'resources.sortScore': '综合排序',
  'resources.sortRating': '评分最高',
  'resources.pageSizeLabel': '显示数量',
  'resources.pageSizeOption': '{n} 条/页',
  'resources.publishAction': '发布资源',
  'resources.fieldPlatform': '平台',
  'resources.fieldCategory': '分类',
  'resources.filterAllCategories': '全部分类',
  'resources.fieldSubCategory': '子分类',
  'resources.fieldSideSupport': '端支持',
  'resources.sideSupportBoth': '双端支持',
  'resources.sideSupportClient': '仅客户端',
  'resources.sideSupportServer': '仅服务端',
  'resources.filterSubdivision': '细分',
  'resources.fieldGameVersion': '游戏版本',
  'resources.filterAllVersions': '全部版本',
  'resources.fieldSort': '排序',
  'resources.officialTagsAll': '官方分类：全部',
  'resources.collectionFilterShort': '收录筛选',
  'resources.categorySectionTitle': '资源分类',
  'resources.officialTagsTitle': '官方分类',
  'resources.officialTagsClear': '清空官方分类',
  'resources.collectionSectionTitle': '资源收录',
  'resources.viewAllCollections': '查看所有合集',
  'resources.collectionModalTitle': '资源收录筛选',
  'resources.officialTagsModalTitle': '官方分类筛选',
  'resources.applyAction': '应用',
  'resources.officialTagsEmpty': '当前分类暂无可选项',
  'resources.officialTagsSummary': '官方分类：{summary}',
  'resources.officialTagsSummaryEmpty': '官方分类：当前分类暂无可选项',
  'resources.officialTagsGroupHeader': '{name}·官方分类',
  'resources.selectedCount': '已选 {n} 项',

  // ===== 资源文档页 =====
  'resources.docTocEmpty': '本页暂无分级标题',
  'resources.docBodyLoadFailed': '正文加载失败，请刷新后重试。',
  'resources.docBodyEmpty': '这篇文档暂时没有可展示的正文。',
  'resources.docBodyRenderFailed': '正文渲染失败，请刷新后重试。',

  // ===== 资源卡片组件 =====
  'resources.downloadLabel': '下载',
  'resources.cardDescription': '浏览资源简介、适配版本与下载信息。',
} as const;
