/** Generated from the legacy i18n module during the directory migration. */
export default {
'video.seoTitle': 'Minecraft 视频区',
  'video.seoDescription': '浏览 Minecraft 社区视频投稿，支持分类、排序和站内讨论。',
  'video.seoDescriptionCategory': '浏览{category}相关的 Minecraft 视频投稿。',
  'video.pageTitle': '视频区',
  'video.pageIntro': '外站播放，站内讨论。视频在这里不只是看完就走。',
  'video.submit': '投稿视频',
  'video.sortLabel': '排序方式',
  'video.latest': '最新发布',
  'video.discuss': '讨论最多',
  'video.hot': '浏览最多',
  'video.collectionSummary': '收录合集：{value}',
  'video.collectionLabel': '收录合集：',
  'video.all': '全部',
  'video.emptyTitle': '还没有公开视频',
  'video.emptyDescription': '第一个把值得聊的 MC 视频贴进来吧。',
  'video.previousPage': '上一页',
  'video.nextPage': '下一页',
  'video.page': '第 {page} / {total} 页',
  'video.sectionTitle': '视频分区',
  'video.allVideos': '全部视频',
  'video.guidanceTitle': '投稿说明',
  'video.guidanceBilibili': '仅支持 Bilibili、腾讯视频与抖音链接',
  'video.guidanceReview': '通过审核后才会公开显示',
  'video.guidanceDiscussion': '重点是把讨论留在站内，不做纯搬运',
  'video.collectionFilterTitle': '视频收录筛选',
  'video.reset': '重置',
  'video.cancel': '取消',
  'video.apply': '应用',
  'video.creator.submitTitle': '投稿视频',
  'video.creator.editTitle': '编辑视频',
  'video.creator.submitDescription': '粘贴视频链接后，补充封面、分区、导语和标签；审核通过后会在站内展示并承接讨论。',
  'video.creator.editDescription': '调整投稿信息后会重新提交审核，原有讨论记录继续保留在这条视频下。',
  'video.creator.sourceUrl': '视频链接',
  'video.creator.sourceUrlPlaceholder': '粘贴 Bilibili / 腾讯视频 / 抖音链接或分享文案',
  'video.creator.title': '标题',
  'video.creator.titleOptional': '标题（可选）',
  'video.creator.titlePlaceholder': '不填时会先用站内默认标题生成',
  'video.creator.titleInputPlaceholder': '输入视频标题',
  'video.creator.customSlug': '自定义链接名',
  'video.creator.customSlugPlaceholder': '可选，留空则按标题自动生成',
  'video.creator.customSlugHelp': '会生成 `/video/你的链接名` 这种更好记的地址。',
  'video.creator.coverOptional': '视频封面（可选）',
  'video.creator.coverTip': '抖音这类外链封面不稳定时，建议直接上传本站封面。',
  'video.creator.coverUploaded': '已上传',
  'video.creator.coverNotUploaded': '未上传',
  'video.creator.coverPreview': '上传后会在这里预览封面',
  'video.creator.uploadCover': '上传封面',
  'video.creator.clearCover': '清空封面',
  'video.creator.coverFormatHelp': '支持 PNG、JPG、WebP、GIF，建议横图，大小尽量控制在 4MB 内。',
  'video.creator.category': '视频分区',
  'video.creator.categoryHint': '选择一个更贴近内容的分区',
  'video.creator.categoryCount': '{count} 条',
  'video.creator.unselectedCategory': '未选择分区',
  'video.creator.introOptional': '导语（可选）',
  'video.creator.introPlaceholder': '简单写写为什么值得看，或者想让大家从哪个点开始聊。',
  'video.creator.tagsOptional': '视频标签（可选）',
  'video.creator.tagsPlaceholder': '输入标签，支持搜索本站已有标签',
  'video.creator.tagsHelp': '可用于视频搜索和 SEO 关键词补充，按回车添加，点击标签可删除。',
  'video.creator.reviewNotice': '审核重点会看内容是否与 MC 社区相关、是否适合公开讨论、是否存在明显违规或纯引流行为。',
  'video.creator.required': '必填',
  'video.creator.optional': '可选',
  'video.creator.submit': '提交审核',
  'video.creator.save': '保存修改',
  'video.creator.backToDetail': '返回详情',
  'video.creator.cancel': '取消',
  'video.creator.uploading': '上传中...',
  'video.creator.uploadFailed': '上传失败',
  'video.creator.checking': '检查中...',
  'video.creator.submitting': '提交中...',
  'video.creator.saving': '保存中...',
  'video.creator.processingTitle': '正在处理',
  'video.creator.publishingTitle': '正在发布',
  'video.creator.savingTitle': '正在保存',
  'video.creator.receivedSubmit': '已收到视频投稿请求，正在检查内容...',
  'video.creator.receivedEdit': '已收到视频修改请求，正在检查内容...',
  'video.creator.submittingHint': '视频投稿正在提交，请稍候...',
  'video.creator.savingHint': '视频修改正在提交，请稍候...',
  'video.creator.uploadImageOnly': '只能上传图片文件',
  'video.creator.coverTooLarge': '封面图片大小不能超过 4MB',
  'video.creator.coverUploadFailed': '封面上传失败',
  'video.creator.coverUploadSuccess': '视频封面上传成功',
  'video.creator.submitSuccess': '视频投稿已提交，正在进入审核队列',
  'video.creator.editSuccess': '视频信息已修改，正在重新提交审核中',
  'video.creator.editPendingSuccess': '视频信息已修改，当前仍在审核中',
  'video.creator.saveSuccess': '保存成功',
  'video.creator.saveFailed': '保存失败',
  'video.creator.resubmitting': '当前视频处于“已拒绝”状态，保存修改后会重新进入审核。',
  'video.creator.pending': '当前视频仍在审核中，你可以继续补充或修正内容。',
  'video.creator.publishedEdit': '修改已发布视频后，会重新进入审核流程，但原讨论楼会继续保留。',
  'video.creator.editHeaderHelp': '调整投稿信息后会重新提交审核，原有讨论记录继续保留在这条视频下。',
} as const;
