/** Generated from the legacy i18n module during the directory migration. */
export default {
// 通用
  'auth.login': 'Log in',
  'auth.register': 'Sign up',
  'auth.backToLogin': 'Back to login',
  'auth.goToLogin': 'Go to login',
  'auth.emailLabel': 'Email',
  'auth.passwordLabel': 'Password',
  'auth.passkeyLabel': 'Passkey',
  'auth.showPassword': 'Show password',
  'auth.or': 'or',
  'auth.termsOfService': 'Terms of Service',
  'auth.privacyPolicy': 'Privacy Policy',
  'auth.checkEmailTitle': 'Check your inbox',
  'auth.verificationLinkSentTo': 'A verification link has been sent to',
  'auth.resendLinkPrefix': 'Resend (',
  'auth.resendLinkSuffix': 's)',
  'auth.keepSignedIn30Days': 'Keep me signed in for 30 days',
  'auth.verifyingEmail': 'Verifying email...',
  'auth.emailVerifiedTitle': 'Email verified',
  'auth.emailInputPlaceholder': 'Enter your email address',
  'auth.passkeyUsageHint': 'Use your fingerprint, face recognition, or device PIN',
  'auth.immediateRegister': 'Sign up now',
  'auth.immediateLogin': 'Log in now',

  // 登录页
  'auth.seoLoginTitle': 'Account login',
  'auth.seoLoginDescription': 'Log in to your community account to join discussions, download resources, check private messages, manage your favorites, and open your profile.',
  'auth.loginEmailIntro': 'Enter your email to choose a password, an email code, or a passkey; you can also sign in directly with a third-party account.',
  'auth.emailOrUsernameLabel': 'Email or username',
  'auth.emailOrUsernamePlaceholder': 'Enter your email or username',
  'auth.nextStep': 'Next',
  'auth.loginWithPasskey': 'Log in with a passkey',
  'auth.continueWithThirdParty': 'Continue with a third-party account',
  'auth.thirdPartyNoEmailHint': 'Third-party login does not require an email first',
  'auth.noAccountYet': 'No account yet?',
  'auth.backToEmail': '← Back to email',
  'auth.chooseLoginMethod': 'Choose a login method',
  'auth.currentEmail': 'Current email: ',
  'auth.passwordLoginTitle': 'Password login',
  'auth.passwordLoginDesc': 'Log in with your email and password',
  'auth.emailLoginTitle': 'Email link login',
  'auth.emailLoginDesc': 'Log in without a password via an email link',
  'auth.thirdPartyLoginTitle': 'Third-party account login',
  'auth.thirdPartyLoginDesc': 'Use your GitHub, Google, Discord, or other account',
  'auth.backToChoose': '← Back to choices',
  'auth.passwordPlaceholder': 'Enter your password',
  'auth.forgotPasswordLink': 'Forgot password?',
  'auth.passkeyDialogHint': 'Complete the passkey verification in the popup dialog',
  'auth.startVerification': 'Start verification',
  'auth.emailLinkIntro': 'A login link will be sent to: ',
  'auth.sendVerificationLink': 'Send verification link',
  'auth.emailLinkSentHint': 'Click the link in the email to finish logging in. The link is valid for 10 minutes.',
  'auth.verifyingLoginLink': 'Verifying the login link...',
  'auth.chooseThirdPartyLogin': 'Choose a third-party account to log in',
  'auth.emailVerificationRequiredTitle': 'Verify your email first',
  'auth.emailVerificationRequiredDesc': 'The email linked to this third-party account is not verified yet. Verify it to continue logging in.',
  'auth.resendEmail': 'Resend email',
  'auth.iHaveVerified': 'I have verified',
  'auth.handleLater': 'Later',
  'auth.closeEmailVerificationPrompt': 'Close the email verification prompt',

  // 注册页
  'auth.seoRegisterTitle': 'Create a community account',
  'auth.seoRegisterDescription': 'Register a community account and verify your email to join the Minecraft Chinese resource-sharing community: publish content, join discussions, and manage your profile.',
  'auth.registerEmailStepIntro': 'Enter your email and complete the human verification, then we will send a verification link',
  'auth.emailPlaceholder': 'Enter your email',
  'auth.referralEntryBanner': 'You are signing up through a referral link. Once you finish, the referrer will get an invite record.',
  'auth.haveAccountYet': 'Already have an account?',
  'auth.registerWithThirdParty': 'Sign up with a third-party account',
  'auth.backToEmailRegister': '← Back to email signup',
  'auth.chooseThirdPartyRegister': 'Choose a third-party account to sign up',
  'auth.registerEmailSentHint': 'Click the link in the email to finish verification. The link is valid for 30 minutes.',
  'auth.backToEditEmail': 'Back to edit email',
  'auth.registerProfileIntro': 'Email verified! Set your username and choose a secure method to finish signing up',
  'auth.oauthRegisterNoEmailBanner': 'This third-party account did not return an email. Bind a commonly used email before continuing the signup.',
  'auth.geeIdNoticePrefix': 'This signup also creates your GeeID account. By continuing, you acknowledge and agree to the',
  'auth.geeIdTerms': 'GeeID Terms of Service',
  'auth.geeIdAnd': 'and',
  'auth.geeIdPrivacy': 'GeeID Privacy Policy',
  'auth.geeIdNoticeSuffix': '.',
  'auth.bindEmailLabel': 'Bind email',
  'auth.bindEmailPlaceholder': 'Enter a commonly used email',
  'auth.bindEmailHint': 'Used for password recovery, notifications, and later account security operations.',
  'auth.referralStepBanner': 'This signup includes a referral relationship, which will be recorded under the referrer once completed.',
  'auth.displayNameLabel': 'Display name',
  'auth.displayNamePlaceholder': 'Enter the display name shown on the site (Chinese is supported)',
  'auth.usernameLabel': 'English username',
  'auth.usernamePlaceholder': '3-16 characters: letters, digits, and underscores only',
  'auth.referralCodeLabel': 'Referral code (optional)',
  'auth.referralCodePlaceholder': 'Enter a referral code shared by someone else',
  'auth.referralCodeHint': 'If you arrived through someone else’s referral link, this is usually filled in automatically, but you can also change it manually.',
  'auth.referralCodeRequiredHint': 'Signups from your region require a valid referral code.',
  'auth.referralDisabledHint': 'Referral codes are currently disabled on this site, so the signup page will not process referral codes or rewards.',
  'auth.phoneBindTitle': 'Phone binding',
  'auth.phoneBindCopy': 'You can also complete the Gee ID phone binding during signup.',
  'auth.phoneLabel': 'Phone number',
  'auth.phonePlaceholder': 'Enter an 11-digit phone number',
  'auth.sendCode': 'Send code',
  'auth.smsCodeLabel': 'SMS code',
  'auth.smsCodePlaceholder': 'Enter the 6-digit SMS code',
  'auth.phoneUnavailableHint': 'Gee ID mainland China phone binding is not supported in your signup region; the related content will go to manual review after signup.',
  'auth.emailOptIn': 'Receive our messages and notifications by email',
  'auth.agreeTermsPrefix': 'I agree to the',
  'auth.agreeTermsAnd': 'and',
  'auth.securityMethodLabel': 'Choose an account security method',
  'auth.setPassword': 'Set a password',
  'auth.passwordPlaceholderMin6': 'Enter a password (at least 6 characters)',
  'auth.passwordMin6Hint': 'The password must be at least 6 characters',
  'auth.completeRegister': 'Finish signup',
  'auth.passkeyCreateHint': 'Click the button below to create a passkey with your fingerprint, face recognition, or device PIN',
  'auth.createPasskeyAndRegister': 'Create a passkey and finish signup',

  // 找回密码
  'auth.seoForgotPasswordTitle': 'Recover your account password',
  'auth.seoForgotPasswordDescription': 'Receive a reset link at your registered email to set a new community account password and log in again.',
  'auth.forgotPasswordTitle': 'Reset password',
  'auth.forgotPasswordIntro': 'Enter your registered email and we will send a reset link',
  'auth.emailAddressLabel': 'Email address',
  'auth.registeredEmailPlaceholder': 'Enter the email you registered with',
  'auth.sendResetLink': 'Send reset link',
  'auth.newPasswordLabel': 'New password',
  'auth.newPasswordPlaceholder': 'At least 6 characters',
  'auth.confirmPasswordLabel': 'Confirm password',
  'auth.confirmPasswordPlaceholder': 'Enter the new password again',
  'auth.resetPassword': 'Reset password',
  'auth.emailRequired': 'Enter your email',
  'auth.captchaRequired': 'Complete the human verification first',
  'auth.sending': 'Sending...',
  'auth.resetLinkSent': 'The reset link has been sent to your email. Please check your inbox.',
  'auth.sendFailed': 'Failed to send',
  'auth.fieldsRequired': 'Please complete all fields',
  'auth.passwordsDoNotMatch': 'The passwords do not match',
  'auth.resetting': 'Resetting...',
  'auth.passwordResetSuccess': 'Password reset successfully. Log in with your new password.',
  'auth.resetFailed': 'Reset failed',
  'auth.verifyingResetToken': 'Verifying...',
  'auth.setNewPasswordIntro': 'Set a new password',
  'auth.resetLinkInvalid': 'This link has expired or has already been used',

  // 两步验证
  'auth.seoLogin2faTitle': 'Two-step verification',
  'auth.seoLogin2faDescription': 'Complete two-step verification login or bind 2FA for the first time to protect your account and login security.',
  'auth.twoFactorTitle': 'Two-step verification',
  'auth.twoFactorIntro': 'Enter the 6-digit dynamic code, or a backup code (for example `ABCDE-FGHIJ`)',
  'auth.codeOrBackupLabel': 'Verification code / backup code',
  'auth.codeOrBackupPlaceholder': '123456 or ABCDE-FGHIJ',
  'auth.verifyAndLogin': 'Verify and log in',
  'auth.newDeviceDetected': 'A new device login was detected. Complete a security verification to continue.',
  'auth.twoFactorCodeLabel': '2FA code / backup code',
  'auth.verify2faAndLogin': 'Verify 2FA and log in',
  'auth.passkeyConfirmHint': 'Use your bound passkey to confirm this new device login.',
  'auth.verifyWithPasskey': 'Verify with a passkey',
  'auth.doublePasswordLabel': 'Two-layer password',
  'auth.doublePasswordPlaceholder': 'Enter the two-layer password',
  'auth.verifyDoublePasswordAndLogin': 'Verify the two-layer password and log in',
  'auth.twoFactorNotBound': 'Your account has not bound 2FA yet. Please bind it first.',
  'auth.scanQrHint': 'Scan the QR code with your authenticator app',
  'auth.manualSecretLabel': 'Enter the secret manually',
  'auth.copy': 'Copy',
  'auth.authenticatorTroubleshootHint': 'If scanning with Microsoft Authenticator keeps failing, choose to enter the secret manually and make sure your phone time syncs automatically.',
  'auth.setupCodeLabel': 'Enter the 6-digit code shown in the app',
  'auth.setupCodePlaceholder': '123456',
  'auth.completeBinding': 'Finish binding and generate backup codes',
  'auth.saveBackupCodesTitle': 'Save your backup codes first',
  'auth.backupCodesCopy': 'Backup codes only work when the authenticator is unavailable, and each can be used once. Save them in at least 2 secure places.',
  'auth.copyBackupCodes': 'Copy backup codes',
  'auth.downloadBackupCodes': 'Download backup codes.txt',
  'auth.backupCodesConfirm': 'I have downloaded or copied these backup codes and will keep them safe offline',
  'auth.finishAndEnterSite': 'Finish and enter the site',

  // 邮箱验证结果页
  'auth.seoVerifyEmailTitle': 'Email verification result',
  'auth.seoVerifyEmailDescription': 'Verify your account email address, check the verification result, and resend the verification email if it failed.',
  'auth.verifyingEmailHint': 'Please wait. The result will appear automatically once verification finishes.',
  'auth.emailVerifiedDesc': 'Your email has been verified. You can go back to log in and enter the site now.',
  'auth.verifyFailedTitle': 'Verification was not completed',
  'auth.verifyFailedDesc': 'This verification link has expired, was already used, or does not match your current email.',
  'auth.resendVerifyEmailHint': 'Enter your registered email and we will send a new verification email:',
  'auth.send': 'Send',

  // OAuth 授权页
  'auth.seoOAuthAuthorizeTitle': 'Authorize a third-party site',
  'auth.seoOAuthAuthorizeDescription': 'Confirm whether to let a third-party application read your account data on this site and complete login.',
  'auth.oauthAuthorizeHeading': 'Authorize a third-party site',
  'auth.oauthAuthorizeIntro': 'You are about to decide whether to let this third-party site read your account data and use it to log in.',
  'auth.oauthLoadingRequest': 'Reading the authorization request...',
  'auth.thirdPartyApp': 'Third-party application',
  'auth.oauthAppNumber': 'OAuth app ID',
  'auth.copyAppNumberTitle': 'Copy app ID',
  'auth.copyOAuthAppNumberAria': 'Copy the OAuth app ID',
  'auth.scopesToRead': 'This will read',
  'auth.reportApp': 'Report this app',
  'auth.deny': 'Deny',
  'auth.allowAndContinue': 'Allow and continue',

  // OAuth 安全验证页
  'auth.seoOAuthVerifyTitle': 'Third-party login security verification',
  'auth.seoOAuthVerifyDescription': 'Complete the human verification to continue the third-party login flow and protect login security.',
  'auth.securityVerifyTitle': 'Security verification',
  'auth.securityVerifyIntro': 'Once you finish this step, you will return to the third-party login flow without starting over.',
  'auth.completeVerifyAndContinue': 'Complete verification and continue',

  // OAuth 回调页
  'auth.seoOAuthCallbackTitle': 'Logging in...',
  'auth.oauthCallbackProcessing': 'Processing login, please wait...',
} as const;
