/** Generated from the legacy i18n module during the directory migration. */
export default {
// ===== Common =====
  'forum.apply': 'Apply',
  'forum.loadMore': 'Load more',
  'forum.remove': 'Remove',
  'forum.clear': 'Clear',
  'forum.unnamed': 'Untitled',
  'forum.unset': 'Not set',
  'forum.boardFallback': 'Board',
  'forum.unnamedBoard': 'Untitled board',
  'forum.unnamedPost': 'Untitled post',
  'forum.noDescription': 'No description yet',
  'forum.unknownUser': 'Unknown user',
  'forum.communityUser': 'Community member',
  'forum.organizationFallback': 'Organization',
  'forum.viewAll': 'View all',
  'forum.pinned': 'Pinned',
  'forum.highlighted': 'Featured',
  'forum.featured': 'Featured',
  'forum.homeFeatured': 'Homepage pick',
  'forum.enterBoard': 'Enter board',
  'forum.postsUnit': 'Posts',
  'forum.postsCountSuffix': ' posts',
  'forum.reply': 'Replies',
  'forum.viewsCount': '{count} views',
  'forum.repliesCount': '{count} replies',
  'forum.publishedAt': 'Published {time}',
  'forum.updatedAt': 'Updated {time}',
  'forum.activityAt': 'Active {time}',
  'forum.newPostsNotice': 'View {count} new or updated posts',
  'forum.newTopicsNotice': 'View {count} new or updated topics',
  'forum.topicsUnit': 'topics',
  'forum.breadcrumbHome': 'Home',
  'forum.breadcrumbForum': 'Forum',
  'forum.relativeTime.justNow': 'Just now',
  'forum.relativeTime.minutes': '{count} minutes ago',
  'forum.relativeTime.hours': '{count} hours ago',
  'forum.relativeTime.days': '{count} days ago',
  'forum.reportStatus.pending': 'Pending',
  'forum.reportStatus.investigating': 'Under review',
  'forum.reportStatus.resolved': 'Resolved',
  'forum.reportStatus.rejected': 'Rejected',
  'forum.role.admin': 'Administrator',
  'forum.role.moderator': 'Moderator',
  'forum.role.player_mod': 'Server moderator',
  'forum.role.resource_mod': 'Resource moderator',
  'forum.role.forum_mod': 'Forum moderator',
  'forum.role.video_mod': 'Video moderator',
  'forum.role.user': 'Member',

  // ===== Pagination / collection filter =====
  'forum.collectionLabel': 'Collection: ',
  'forum.collectionFilterTitle': 'Post collection filter',
  'forum.collectionEmpty': 'No collections contain posts',

  // ===== Forum index SEO =====
  'forum.seo.homeTitle': 'Forum',
  'forum.seo.homeDesc1': 'Enter the Minecraft Chinese forum',
  'forum.seo.homeDesc2': 'Browse featured boards, the latest posts and steadily updated community discussions',
  'forum.seo.homeDesc3': 'Discuss gameplay, server operations, plugins and mods, and other player topics',
  'forum.seo.homeDescFallback': 'Minecraft Chinese forum: browse featured boards and the latest posts.',
  'forum.seo.homeKeywords': 'Minecraft forum,MC community forum,Minecraft Chinese forum,MC discussion,server talk,plugins and mods',
  'forum.seo.jsonLdFeaturedBoards': 'Featured forum boards',
  'forum.seo.jsonLdLatestTopics': 'Latest forum topics',
  'forum.seo.keywordMinecraftForum': 'Minecraft forum',
  'forum.seo.keywordCommunityPost': 'Community post',

  // ===== Forum index =====
  'forum.featuredBoards': 'Featured boards',
  'forum.featuredBoardsDesc': 'Browse recommended boards and pick the right place to read or start a topic.',
  'forum.viewNewTopics': 'View new topics',
  'forum.viewAllBoards': 'View all boards',
  'forum.latestTopics': 'Latest topics',
  'forum.latestTopicsDesc': 'Browse the newest community topics by publish time.',
  'forum.mcTip': 'MC tip',
  'forum.mcTipRefresh': 'Refresh MC tip',
  'forum.mcTipAnother': 'Show another tip',
  'forum.onlineUsers': 'Online users',
  'forum.communityStats': 'Community stats',
  'forum.hotTags': 'Popular tags',

  // ===== Boards directory SEO =====
  'forum.seo.boardsTitle': 'Forum boards',
  'forum.seo.boardsDesc1': 'Browse the full Minecraft forum board directory',
  'forum.seo.boardsDesc2': 'Jump straight into the discussion, technical and community boards you care about',
  'forum.seo.boardsDesc3': 'See what each board covers, which topics it hosts and where to post',
  'forum.seo.boardsDescFallback': 'Minecraft forum board directory and discussion board overview',
  'forum.seo.boardsKeywords': 'Minecraft forum boards,MC board overview,Minecraft forum directory,MC board navigation,forum board list',
  'forum.seo.boardsJsonLdList': 'Forum board list',

  // ===== Boards directory =====
  'forum.boardsOverviewTitle': 'Forum board overview',
  'forum.boardsOverviewDesc': 'Browse the whole forum directory by board and quickly find where to post and discuss.',
  'forum.backToForumHome': 'Back to forum home',
  'forum.boardsSummaryFeatured': 'There are {total} forum boards in total, {featured} of which appear in the featured area on the forum home page.',
  'forum.boardsSummaryNone': 'There are {total} forum boards in total, and no featured board has been set for the home page yet.',
  'forum.boardsEmpty': 'There are no forum boards to browse yet.',
  'forum.boardsLoadFailed': 'Failed to load forum boards. Please try again later.',

  // ===== Board detail SEO =====
  'forum.seo.boardPageTitle': 'Forum board {board}',
  'forum.seo.boardBrowseTitle': 'Forum board browser',
  'forum.seo.boardDescDefault': 'Browse the latest posts, hot discussions, posting entry and steadily updated community activity in this forum board.',
  'forum.seo.boardDefaultKeywords': 'Minecraft forum boards,MC discussion,forum post list',
  'forum.seo.boardDiscussionSuffix': '{board} board discussion',
  'forum.seo.boardKeywordBoard': '{board} board',
  'forum.seo.boardKeywordForum': '{board} forum',
  'forum.seo.boardKeywordDiscussion': '{board} discussion',
  'forum.seo.boardKeywordExperience': '{board} experience sharing',
  'forum.seo.boardKeywordHotPosts': '{board} hot posts',
  'forum.seo.boardKeywordLatestPosts': '{board} latest posts',
  'forum.seo.keywordMcCommunityDiscussion': 'MC community discussion',
  'forum.seo.boardDescBrowse': 'Browse posts, experience sharing and community discussion in the {board} board',
  'forum.seo.boardDescHot': 'Currently viewing the hottest discussions in the {board} board by reply count',
  'forum.seo.boardDescLatest': 'Currently viewing topic updates in the {board} board by publish time',
  'forum.seo.boardDescPage': 'Currently viewing page {page} of the board list',
  'forum.seo.boardDescOverview': 'See the latest topics, hot replies and posting entry in the {board} board',
  'forum.seo.boardDescFallback': 'The latest posts and discussions in the {board} board',
  'forum.seo.boardJsonLdPosts': '{board} post list',
  'forum.seo.boardJsonLdTopics': '{board} topic categories',
  'forum.seo.topicFallback': 'Topic {index}',

  // ===== Board detail =====
  'forum.boardInfo': 'Board information',
  'forum.postCount': 'Total posts',
  'forum.publishPost': 'Publish post',
  'forum.noPostPermission': 'You do not have permission to post in this board',
  'forum.emptyPosts': 'No posts yet',
  'forum.emptyPostsInCollection': 'No posts in this collection',
  'forum.emptyTopics': 'No topics yet',
  'forum.emptyTopicsInCollection': 'No topics in this collection',
  'forum.emptyBoards': 'No boards yet',
  'forum.sortLatest': 'Newest',
  'forum.sortMostReplies': 'Most replies',
  'forum.viewNewPosts': 'View new posts',
  'forum.rules': 'Board rules',
  'forum.ruleFriendly': 'Be friendly and respect others',
  'forum.ruleNoIllegal': 'Illegal content is prohibited',
  'forum.ruleNoSpam': 'Advertising and spam are prohibited',
  'forum.ruleGoodTitle': 'Use an appropriate title',

  // ===== Post detail SEO =====
  'forum.seo.postTitle': 'Post details',
  'forum.seo.postBoard': 'Board: {name}',
  'forum.seo.postTopicTags': 'Topic categories: {names}',
  'forum.seo.postTags': 'Topics: {names}',
  'forum.seo.postPublisher': 'Publisher: {name}',
  'forum.seo.postReplies': '{count} replies',
  'forum.seo.postViews': '{count} views',
  'forum.seo.postDescLine': 'Read the full post, replies and community interaction details',
  'forum.seo.postDescFallback': 'Read the full post, replies and community discussion',
  'forum.seo.postUnavailableTitle': 'Post temporarily unavailable',
  'forum.seo.postNotFoundTitle': 'Post not found',
  'forum.seo.postUnavailableDesc': 'Post details cannot be loaded right now. Please try again later.',
  'forum.seo.postNotFoundDesc': 'This post does not exist, has been deleted, or is not publicly accessible.',
  'forum.seo.postJsonLdCollection': 'Forum',

  // ===== Post detail =====
  'forum.postUnavailable': 'This post is temporarily unavailable.',
  'forum.quoteReply': 'Reply to {target}',
  'forum.quoteReplyWithPreview': 'Reply to {target}: {preview}',
  'forum.noReplies': 'No comments or replies yet',
  'forum.noRepliesDesc': 'Nobody has joined the discussion yet. Be the first to reply.',
  'forum.moderationSubjectPost': 'This post',
  'forum.moderationResubmitting': 'This post was edited and is being resubmitted for review. Only you and administrators can see it.',
  'forum.continueEditing': 'Continue editing',
  'forum.editAndResubmit': 'Edit and resubmit',
  'forum.moderationResubmitFootnote': 'Saving your changes automatically starts the review process again.',
  'forum.publisherLabel': 'Publisher: {name}',
  'forum.authorLabel': 'Author: {name}',
  'forum.repliesTitle': 'Comments and replies',
  'forum.replySortLabel': 'Comment sorting',
  'forum.sortHot': 'Hottest',
  'forum.sortNew': 'Newest',
  'forum.replyComposerLabel': 'Reply editor',
  'forum.replyComposerKicker': 'Reply to topic',
  'forum.replyComposerKickerComment': 'Reply to comment',
  'forum.replyComposerTitle': 'Write your reply',
  'forum.closeReplyComposer': 'Close reply editor',
  'forum.closePrompt': 'Close prompt',
  'forum.discard': 'Discard',
  'forum.submitReply': 'Post reply',
  'forum.relatedPosts': 'Related posts',
  'forum.loginPromptEyebrow': 'Log in to keep joining the discussion',
  'forum.loginPromptTitle': 'Log in to reply, get notifications and resume where you left off',
  'forum.loginPromptDesc': 'With an account you can follow threads more smoothly and never miss a new reply.',
  'forum.loginPromptBenefits': 'What you get after logging in',
  'forum.loginBenefitHistory': 'Reading progress saved',
  'forum.loginBenefitNotify': 'New reply notifications',
  'forum.loginBenefitJoin': 'Join the discussion right away',
  'forum.registerAccount': 'Create account',
  'forum.loginNow': 'Log in now',
  'forum.postInfo': 'Post information',
  'forum.tocTitle': 'On this page',
  'forum.resourceDocNav': 'Resource documentation navigation',
  'forum.resourceDocKicker': 'Resource docs',
  'forum.resourceDocTitle': 'Document outline',
  'forum.resourceDocLoading': 'Loading resource documentation...',
  'forum.reportTitle': 'Report content',
  'forum.reportReason': 'Report reason',
  'forum.reportReasonPlaceholder': 'Select a report reason',
  'forum.reportDetail': 'Details (optional)',
  'forum.reportDetailPlaceholder': 'Add details to help administrators review',
  'forum.submitReport': 'Submit report',
  'forum.wechatShare': 'Share on WeChat',
  'forum.wechatShareDesc': 'Copy the link and share it with friends on WeChat',
  'forum.copy': 'Copy',
  'forum.editHistoryTitle': 'Post edit history',
  'forum.editHistoryDesc': 'Changes to post content, title and publishing settings in reverse chronological order',
  'forum.editHistoryLoading': 'Loading edit history...',
  'forum.editHistoryEmpty': 'No edit history recorded yet',
  'forum.accessPasswordTitle': 'This visit requires a passcode',
  'forum.accessPasswordDesc': 'Enter the passcode set by the publisher to view the hidden content.',
  'forum.accessPasswordPlaceholder': 'Enter the passcode',
  'forum.viewUserProfile': 'View {user} profile',
  'forum.acceptedAnswer': 'Accepted answer',
  'forum.floorTitle': 'Floor {floor}',
  'forum.locateQuoteReply': 'Jump to quoted reply #{floor}',
  'forum.locateQuoteReplyAria': 'Jump to quoted reply: {summary}',
  'forum.acceptAsAnswer': 'Accept as the answer',
  'forum.imageAltActivityCover': 'Event cover preview',
  'forum.deletePostTitle': 'Delete post',
  'forum.confirmDeletePost': 'Are you sure you want to delete this post?',
  'forum.deleteReplyTitle': 'Delete reply',
  'forum.confirmDeleteReply': 'Are you sure you want to delete this reply?',
  'forum.targetLabelReply': 'Reply',
  'forum.toastLoginToReply': 'Please log in before replying',
  'forum.toastReplyNotAllowed': 'Replies are not allowed on this post right now',
  'forum.toastReplyContentRequired': 'Please enter your reply',
  'forum.toastReplyFailed': 'Failed to reply',
  'forum.toastReplyPending': 'Reply submitted for review',
  'forum.toastReplyPublished': 'Reply published',
  'forum.toastReplyDeleted': 'Reply deleted',
  'forum.toastRepliesLoadFailed': 'Failed to load comments. Please try again.',
  'forum.toastAnswerAccepted': 'Marked this reply as the accepted answer',
  'forum.toastAcceptFailed': 'Failed to accept the answer',
  'forum.toastDeleteFailed': 'Failed to delete',
  'forum.toastActionFailed': 'The action failed. Please try again.',
  'forum.submitting': 'Submitting...',
  'forum.toastPasswordRequired': 'Please enter the passcode',
  'forum.toastPasswordInvalid': 'Passcode verification failed',
  'forum.toastDeleteSuccessBackToForum': 'Deleted. Returning to the forum.',

  // ===== Reply actions / report =====
  'forum.replyActions': 'Reply actions',
  'forum.like': 'Like',
  'forum.more': 'More',
  'forum.moreCommentActions': 'More comment actions',
  'forum.reportComment': 'Report this comment or reply',
  'forum.deleteComment': 'Delete this comment',

  // ===== Post composer / editor form =====
  'forum.seo.newTitle': 'Publish a new post',
  'forum.seo.newDesc': 'Create a new post in a chosen board with a title, body, tags and visibility settings.',
  'forum.seo.editTitle': 'Edit an existing post',
  'forum.seo.editDesc': 'Change the post title, body, tags, visibility and copyright notice.',
  'forum.publishActionLabel': 'Publish',
  'forum.editActionLabel': 'Edit',
  'forum.contentLabelPost': 'Post',
  'forum.newPostHeading': 'Publish post',
  'forum.newPostSubtitle': 'Choose a submission channel, then fill in the post content and publishing settings. After saving a draft you can continue from the creator workbench.',
  'forum.editPostHeading': 'Edit post',
  'forum.editReviewNotice': 'Published or rejected posts are resubmitted for review after you save changes; posts under review can also be refined further.',
  'forum.editReviewNoticeAdmin': 'You are editing this post as an administrator. Saving will not enter the review queue and the post will stay or become approved.',
  'forum.toastNoEditPermission': 'You do not have permission to edit this post',
  'forum.selectBoard': 'Select a board',
  'forum.selectBoardPlaceholder': 'Select a board',
  'forum.topicCategory': 'Topic category',
  'forum.topicCategoryHelp': 'Pick freely from the topic categories enabled for this board, up to 5. They appear before the title.',
  'forum.topicSelectedCount': 'Selected {count} / 5',
  'forum.toastTopicLimit': 'You can select at most 5 topic categories',
  'forum.postType': 'Post type',
  'forum.postTypeDefault': 'Standard post',
  'forum.postTypeQa': 'Q&A post',
  'forum.postTypePoll': 'Poll post',
  'forum.postTypeReference': 'Resource/server reference post',
  'forum.postTypeBadgeQa': 'Q&A',
  'forum.postTypeBadgePoll': 'Poll',
  'forum.postTypeBadgeReference': 'Reference',
  'forum.postTypeBadgeReferenceGuide': 'Reference guide',
  'forum.qaRewardLabel': 'Accepted answer reward (coins)',
  'forum.qaRewardPlaceholder': 'Enter 0 to leave it unset',
  'forum.qaRewardHelp': 'When the asker accepts the final answer, the amount is deducted from their account and paid to the answerer.',
  'forum.referenceTarget': 'Reference target',
  'forum.referenceTypeResource': 'Resource',
  'forum.referenceTypePlayer': 'Server listing',
  'forum.referenceSearchPlaceholder': 'Search for a resource or server listing to reference',
  'forum.referenceHelp': 'The referenced item is shown first after publishing and automatically added to its "Tutorials" tab; resource or server listing managers can remove it from the edit page.',
  'forum.referenceHelpEdit': 'Changing the reference target also updates the tutorial listings of the related resource or server listing.',
  'forum.pollMode': 'Poll mode',
  'forum.pollModeSingle': 'Single choice',
  'forum.pollModeMultiple': 'Multiple choice',
  'forum.pollMaxChoices': 'Max choices for multiple choice',
  'forum.pollOptions': 'Poll options',
  'forum.pollAddOption': 'Add option',
  'forum.pollOptionPlaceholder': 'Option {index}',
  'forum.pollRevealAt': 'Poll results reveal time',
  'forum.pollRevealHelp': 'Leave empty to reveal the poll results immediately.',
  'forum.pollRewardPerVoter': 'Reward per participant (coins)',
  'forum.pollRewardBudget': 'Total reward budget (coins)',
  'forum.pollRewardHelp': 'Participation rewards are paid on the first vote; once the total budget runs out, new participants no longer receive rewards.',
  'forum.eventInfo': 'Event information',
  'forum.eventInfoHelp': 'This board is used for events. Fill in the event time, location and display information.',
  'forum.eventStartsAt': 'Start time',
  'forum.eventEndsAt': 'End time',
  'forum.eventTitle': 'Event title',
  'forum.eventTitlePlaceholder': 'Leave empty to use the post title',
  'forum.eventLocation': 'Location',
  'forum.eventLocationPlaceholder': 'Online / server / city location',
  'forum.eventLocationUrl': 'Location link',
  'forum.eventCoverImage': 'Cover image link',
  'forum.eventUploadImage': 'Upload image',
  'forum.eventCoverHelp': 'You can upload a cover image or keep using an external image link.',
  'forum.eventCapacity': 'Capacity',
  'forum.eventCapacityPlaceholder': 'Leave empty for unlimited',
  'forum.eventRsvpEnabled': 'Enable RSVP',
  'forum.eventRsvpHelp': 'This version only shows the marker; the attendee list will be wired up later.',
  'forum.eventSummary': 'Event summary',
  'forum.eventSummaryPlaceholder': 'Briefly describe the event, how to join, or the rewards',
  'forum.postTitleLabel': 'Post title',
  'forum.postTitlePlaceholder': 'Enter the post title',
  'forum.postContentLabel': 'Post content',
  'forum.tagsLabel': 'Tags',
  'forum.tagsHint': '(up to 20, press Enter to add)',
  'forum.tagsPlaceholder': 'Enter a tag name and press Enter to add',
  'forum.toastTagExists': 'This tag already exists',
  'forum.tagUsageCount': 'used {count} times',
  'forum.visibility': 'Visibility',
  'forum.visibilityPublic': 'Public',
  'forum.visibilityVerify': 'Verified access',
  'forum.visibilityPartial': 'Visible to selected people',
  'forum.visibilityPrivate': 'Unpublished (visible only to you and the management team)',
  'forum.accessMode': 'Verification method',
  'forum.accessModePassword': 'Passcode',
  'forum.accessModeReply': 'Visible after replying',
  'forum.accessModeLogin': 'Visible after logging in',
  'forum.accessModeHelp': 'Verified access does not hide the title or the reply area; it only restricts viewing the post body.',
  'forum.accessPasswordLabel': 'Access passcode',
  'forum.accessPasswordNewPlaceholder': 'Enter a 4-64 character access passcode',
  'forum.accessPasswordTip': 'The post body is only visible after entering the correct passcode.',
  'forum.accessPasswordKeepPlaceholder': 'Leave empty to keep the current passcode, or enter a new one to replace it',
  'forum.accessPasswordKeepTip': 'If the post already uses passcode verification, leave this empty to keep the existing passcode.',
  'forum.visibilityAllowIds': 'User IDs allowed to view (comma separated)',
  'forum.visibilityAllowIdsPlaceholder': 'For example: user-id-1,user-id-2',
  'forum.visibilityAllowIdsHelp': 'Administrators, super moderators and forum moderators can always see it.',
  'forum.paidArticleSettings': 'Paid article settings',
  'forum.paidArticleSettingsHelp': 'Paid articles share the publishing entry with regular topics; readers pay to view the full body.',
  'forum.paidArticleEnable': 'Enable paid article',
  'forum.paidArticleEnableHelp': 'The price and preview ratio can be adjusted on the administrator edit page after publishing.',
  'forum.paidArticlePrice': 'Article price (CNY)',
  'forum.paidArticlePricePlaceholder': 'For example: 9.90',
  'forum.paidArticlePriceRange': 'Allowed range ¥0.01 - ¥100000.00.',
  'forum.paidArticlePreviewPercent': 'Free preview ratio (%)',
  'forum.paidArticleAssetsHelp': 'Images, videos, audio and attachments still require purchase to view.',
  'forum.paidArticleReaderAmount': 'Reader pays',
  'forum.paidArticlePlatformAmount': 'User income',
  'forum.paidArticlePreviewLabel': 'Pre-purchase note',
  'forum.paidArticlePreviewPlaceholder': 'Briefly describe the article and who it is for',
  'forum.paidArticleTutorial': 'Publishing tutorial',
  'forum.paidArticleAgreement': 'Paid article pricing and publishing agreement',
  'forum.paidArticleAgreementCheckbox': 'I have read and agree to the pricing rules and paid article publishing agreement above',
  'forum.paidArticleNote': 'Paid articles must stay publicly visible and cannot enable other body access verification at the same time.',
  'forum.copyrightEnable': 'Add a copyright notice',
  'forum.copyrightEnableHelp': 'Show copyright information and a license at the bottom of the post',
  'forum.copyrightLicense': 'License type',
  'forum.licenseCcBy': 'Attribution 4.0 International (CC BY 4.0)',
  'forum.licenseCcBySa': 'Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)',
  'forum.licenseCcByNc': 'Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)',
  'forum.licenseCcByNcSa': 'Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)',
  'forum.licenseCcByNcSaShort': 'Attribution-NonCommercial-ShareAlike 4.0 International',
  'forum.licenseCcByNd': 'Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)',
  'forum.licenseCcByNcNd': 'Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)',
  'forum.licenseCcByNcNdShort': 'Attribution-NonCommercial-NoDerivatives 4.0 International',
  'forum.licenseCc0': 'CC0 1.0 Public Domain Dedication',
  'forum.licenseArr': 'All Rights Reserved',
  'forum.copyrightPreviewTitle': 'Post title',
  'forum.copyrightPreviewLink': 'Link generated after publishing',
  'forum.copyrightAuthor': 'Author',
  'forum.copyrightAuthorFallback': 'Author',
  'forum.copyrightDate': 'Published',
  'forum.copyrightToday': 'Today',
  'forum.copyrightLicenseLabel': 'License',
  'forum.saveDraft': 'Save draft',
  'forum.saveChanges': 'Save changes',
  'forum.restoreDraft': 'Restore draft',
  'forum.discardDraft': 'Discard',
  'forum.draftDetectedPrefix': 'Unpublished draft detected (',
  'forum.draftDetectedSuffix': ')',
  'forum.selectDraftToRestore': 'Select a draft to restore',
  'forum.unnamedDraft': 'Untitled draft',
  'forum.draftBoardLabel': ' | Board {board}',
  'forum.toastDraftRestored': 'Draft restored',
  'forum.toastDraftSaved': 'Draft saved, you can keep editing',
  'forum.toastDraftSaveFailed': 'Failed to save the draft',
  'forum.toastDraftDeleted': 'Draft deleted',
  'forum.toastDraftCleared': 'Draft cleared',
  'forum.draftCloudEqual': 'The cloud draft is currently loaded.',
  'forum.draftLocalEqual': 'The local cache matches the cloud draft.',
  'forum.draftCloudFresh': 'The cloud draft is newer than the local cache; the cloud version is loaded on this page.',
  'forum.draftLocalFresh': 'The local cache is newer than the current cloud draft; check whether you need to restore the local version manually.',

  // ===== Composer validation and submission =====
  'forum.checking': 'Checking...',
  'forum.publishing': 'Publishing...',
  'forum.toastSubmitChecking': 'Post request received, checking content and permissions...',
  'forum.toastSaveChecking': 'Save request received, checking the post content...',
  'forum.toastProcessing': 'Processing',
  'forum.toastSavingTitle': 'Saving',
  'forum.toastPublishingTitle': 'Publishing',
  'forum.toastPublishing': 'The post is being published; you will be redirected automatically once it finishes.',
  'forum.toastEditSubmitting': 'Submitting your post changes, please wait...',
  'forum.validationTitleRequired': 'Please enter a title',
  'forum.validationTitleMin': 'The title must be at least 3 characters',
  'forum.validationBoardRequired': 'Please select a board',
  'forum.validationContentRequired': 'Please enter the post content',
  'forum.validationContentRequiredEdit': 'Please enter the content',
  'forum.validationContentMin': 'The post body must be at least {count} characters',
  'forum.validationAllowIdsRequired': 'Please select the user IDs allowed to view',
  'forum.validationEventStartRequired': 'Please set the event start time',
  'forum.validationEventEndBeforeStart': 'The event end time cannot be earlier than the start time',
  'forum.validationPasswordRequired': 'Please enter the access passcode',
  'forum.validationPaidMustBePublic': 'Paid articles must be public and cannot enable other body access verification',
  'forum.validationPaidPriceInvalid': 'Please enter a valid article price with at most two decimal places',
  'forum.validationPaidAgreement': 'Please read and agree to the paid article pricing rules and publishing agreement',
  'forum.validationPollMinOptions': 'A poll post needs at least 2 options',
  'forum.validationPollMinChoices': 'A multiple-choice poll must allow at least 2 choices',
  'forum.validationPollBudget': 'The total poll reward budget cannot be less than a single reward',
  'forum.validationReferenceRequired': 'Please select a resource or server listing to reference',
  'forum.docTitleFormat': '[Resource name]Document name',
  'forum.docTitleFormatError': 'The document title format must be "[Resource name]Document name"',
  'forum.docTitleFormatHint': 'Title format: {format}, for example "[LuckPerms]Installation and configuration guide"',
  'forum.toastPostTooLarge': 'The post content is too large. Reduce images pasted directly into the body or upload them first.',
  'forum.toastPublishSuccess': 'Published successfully and submitted for review',
  'forum.toastPublishFailed': 'Publishing failed. Please log in first.',
  'forum.toastPostLoadFailed': 'Failed to load the post',
  'forum.toastPostLoadFailedRetrySave': '{message}. Please reload the page before saving again.',
  'forum.toastPostUpdated': 'Post updated',
  'forum.toastPostUpdatedApproved': 'Post updated and approved directly',
  'forum.toastPostResubmitted': 'Post edited and resubmitted for review',
  'forum.toastSaveFailed': 'Failed to save',
  'forum.toastEditDataNotReady': 'The edit data has not finished loading. Please reload the page before saving.',
  'forum.toastPaidSettingsFailed': 'The body was saved, but the paid settings failed to save. Your input is kept; please check and retry the paid settings.',
  'forum.toastPostTypeSwitched': 'This board does not allow that post type, so it was switched to an available type.',
  'forum.toastBoardPostDenied': 'You do not have permission to post in this board. Please choose another board.',
  'forum.toastBoardsLoadFailed': 'Failed to load the board list',
  'forum.noBoardsAvailable': 'No board is available for posting',
  'forum.boardNoPermissionOption': '{board} (no posting permission)',
  'forum.currentBoard': 'Current board',

  // ===== Submission channel =====
  'forum.submissionChannel': 'Submission channel',
  'forum.submissionChannelSelect': 'Select a submission channel',
  'forum.channelGeneral': 'Standard post',
  'forum.channelEvent': 'Event',
  'forum.channelDocumentation': 'Documentation',
  'forum.channelStatusGeneral': 'Posting to a standard board',
  'forum.channelStatusAuto': 'Automatically published to the "{board}" board',
  'forum.channelUnavailable': 'This channel is not available for posting right now',

  // ===== Post edit history =====
  'forum.historyField.title': 'Title',
  'forum.historyField.content': 'Post body',
  'forum.historyField.boardId': 'Board',
  'forum.historyField.tags': 'Tags',
  'forum.historyField.topicTags': 'Topic categories',
  'forum.historyField.topicTagId': 'Topic',
  'forum.historyField.topicTagName': 'Topic name',
  'forum.historyField.visibility': 'Visibility',
  'forum.historyField.visibilityAllowUserIds': 'Allowed users',
  'forum.historyField.accessMode': 'Access method',
  'forum.historyField.copyrightEnabled': 'Copyright notice',
  'forum.historyField.copyrightLicense': 'Copyright license',
  'forum.historyDiffEmpty': 'The body is empty or no displayable text could be parsed',
  'forum.historyDiffSkipped': '{count} unchanged lines omitted',
  'forum.historyDiffAdd': 'Added',
  'forum.historyDiffRemove': 'Removed',
  'forum.historyDiffUnchanged': 'Unchanged',
  'forum.historyCharNoChange': 'No change in character count',
  'forum.historyCharDelta': '{delta} characters',
  'forum.historyContentTitle': 'Post body',
  'forum.historyContentNote': 'Expand to see the text diff',
  'forum.historyContentStatsLabel': 'Body change summary',
  'forum.historyBeforeChars': '{count} characters before',
  'forum.historyAfterChars': '{count} characters after',
  'forum.historyLineChanges': '{added} lines added / {removed} lines removed',
  'forum.historyViewDiff': 'View body diff',
  'forum.historyApproxChars': 'about {count} characters',
  'forum.historyEmptyContent': 'Empty body',
  'forum.historyNoTags': 'No tags set',
  'forum.historyUserCount': '{count} selected users',
  'forum.historyNoUsers': 'No users selected',
  'forum.historyVisibilityPublic': 'Publicly visible',
  'forum.historyVisibilityPartial': 'Visible to selected users',
  'forum.historyVisibilityPrivate': 'Visible only to yourself',
  'forum.historyAccessNone': 'No extra verification',
  'forum.historyAccessLogin': 'Visible after logging in',
  'forum.historyAccessReply': 'Visible after replying',
  'forum.historyAccessPassword': 'Passcode access',
  'forum.historyEnabled': 'Enabled',
  'forum.historyDisabled': 'Disabled',
  'forum.historyNoLicense': 'No license set',
  'forum.historyUpdatedPost': 'Updated the post',
  'forum.historyUpdatedOne': 'Updated {field}',
  'forum.historyUpdatedMany': 'Updated {count} items: {fields}',
  'forum.historyUpdatedManyMore': ' and {count} more',
  'forum.historyNoDetail': 'This record has no displayable field details',
  'forum.historyBefore': 'Before',
  'forum.historyAfter': 'After',
  'forum.historyContentDefaultNote': 'The body shows a summary by default; expand to see the text diff before and after.',

  // ===== Q&A / poll posts =====
  'forum.postTypeSolved': 'Solved',
  'forum.qaSolved': 'Answer accepted',
  'forum.qaSolvedDesc': 'The asker has chosen one reply as the final answer.',
  'forum.qaOpenDesc': 'The asker can choose one reply as the final answer.',
  'forum.qaRewardValue': 'Accepted answer reward: {value}',
  'forum.qaRewardCoins': '{count} coins',
  'forum.voteCount': '{count} votes',
  'forum.pollResultHidden': 'Results will be shown after the reveal time',
  'forum.pollMultipleDesc': 'Multiple choice, up to {count} options',
  'forum.pollVoterCount': 'Participants:',
  'forum.pollRewardLine': 'Participation reward: {value}',
  'forum.pollRewardDetail': '{amount} coins / total budget {budget}',
  'forum.pollRevealTime': 'Reveal time: {time}',
  'forum.pollRevealNow': 'Reveal results immediately',
  'forum.submitVote': 'Submit vote',
  'forum.toastLoginToVote': 'Please log in before voting',
  'forum.toastSelectVoteOption': 'Please select an option first',
  'forum.toastVoteSubmitted': 'Vote submitted',
  'forum.toastVoteFailed': 'Failed to vote',

  // ===== WeChat Pay =====
  'forum.wechatCreatingOrder': 'Creating the WeChat Pay order...',
  'forum.wechatQrMissing': 'Failed to get the WeChat Pay QR code',
  'forum.wechatModalTitle': 'Scan to pay with WeChat',
  'forum.wechatModalDesc': 'Scan the QR code with WeChat to pay, then tap the button below to check the payment.',
  'forum.wechatQrAlt': 'WeChat Pay QR code',
  'forum.wechatCheckButton': 'Payment done, check order',
  'forum.wechatChecking': 'Checking...',
  'forum.wechatQuerying': 'Checking the payment result...',
  'forum.wechatConfirmed': 'Payment confirmed, opening the full text...',
  'forum.wechatNotDetected': 'No payment detected yet. Please wait a moment and check again.',
  'forum.wechatCheckFailed': 'Check failed. Please try again later.',
  'forum.wechatScanToPay': 'Please scan the code to complete the payment',
  'forum.wechatOrderFailed': 'Failed to create the payment order. Please try again later.',
  'forum.docModeTitle': 'Read this content in document mode',

  // ===== Reference card / picker =====
  'forum.referenceLabel': 'Reference to {target}',
  'forum.referenceOnline': '{online}/{max} online',
  'forum.viewTarget': 'View {target}',
  'forum.referenceNotSelected': 'No reference target selected yet',
  'forum.referenceSelectedFallback': 'Selected {label}',
  'forum.toastReferenceLoadFailed': 'Failed to load the reference target',

  // ===== Event card / cover upload =====
  'forum.eventStatus.cancelled': 'Cancelled',
  'forum.eventStatus.ended': 'Ended',
  'forum.eventStatus.ongoing': 'Ongoing',
  'forum.eventStatus.upcoming': 'Starting soon',
  'forum.eventFallbackTitle': 'Event',
  'forum.eventCapacityCount': '{count} spots',
  'forum.eventCoverCleared': 'Cover image cleared',
  'forum.toastImageOnly': 'Only image files can be uploaded',
  'forum.uploading': 'Uploading...',
  'forum.uploadingPercent': 'Uploading {percent}%',
  'forum.eventCoverUploadFailed': 'Failed to upload the cover image',
  'forum.eventCoverUploaded': 'Cover image uploaded',
  'forum.toastEventCoverUploaded': 'Event cover uploaded successfully',
  'forum.uploadFailed': 'Upload failed',

  // ===== Feedback progress status =====
  'forum.feedback.pending_discussion': 'To discuss',
  'forum.feedback.todo': 'To do',
  'forum.feedback.in_progress': 'In progress',
  'forum.feedback.completed': 'Completed',
  'forum.feedback.not_bug': 'Not a bug',
  'forum.feedback.wontfix': "Won't fix",
  'forum.feedback.duplicate': 'Duplicate',
  'forum.feedback.closed': 'Closed',
} as const;
