/** Generated from the legacy i18n module during the directory migration. */
export default {
// SEO
  'home.seoTitle': 'Minecraft Community — Resources, Forums & Servers',
  'home.seoDescription1': 'Browse the latest resources, trending discussions, and active boards in the Minecraft community',
  'home.seoDescription2': 'Share plugins, mods, modpacks, texture packs, and server experience',
  'home.seoDescription3': 'Explore resource downloads, forum discussions, server listings, and community updates',
  'home.seoDescriptionFallback': 'A Minecraft community for sharing resources and meeting players',
  'home.seoKeyword1': 'Minecraft forum',
  'home.seoKeyword2': 'Minecraft resource community',
  'home.seoKeyword3': 'Minecraft community',
  'home.seoKeyword4': 'Minecraft plugins and mods',
  'home.seoKeyword5': 'Minecraft server community',

  // 结构化数据（JSON-LD）
  'home.jsonLdShowcaseName': 'Home · {title}',
  'home.jsonLdLatestResources': 'Latest resources on the home page',
  'home.jsonLdHotPosts': 'Trending discussions on the home page',
  'home.jsonLdHotBoards': 'Popular boards on the home page',
  'home.jsonLdLatestPlayers': 'Latest servers on the home page',
  'home.jsonLdLatestVideos': 'Latest videos on the home page',
  'home.jsonLdOrganizations': 'Organizations on the home page',
  'home.jsonLdResourceDocs': 'Resource docs on the home page',
  'home.jsonLdResourceDocName': '{post} - {resource}',
  'home.jsonLdFallbackResourceDoc': 'Resource doc',
  'home.jsonLdFallbackResource': 'Resource',

  // 未命名 / 未知兜底
  'home.untitledContent': 'Untitled item',
  'home.untitledResource': 'Untitled resource',
  'home.untitledPost': 'Untitled post',
  'home.untitledBoard': 'Untitled board',
  'home.untitledPlayer': 'Untitled server',
  'home.untitledVideo': 'Untitled video',
  'home.untitledOrganization': 'Untitled organization',
  'home.untitledTopic': 'Untitled topic',
  'home.unknownUser': 'Unknown user',
  'home.userAvatarAlt': 'User avatar',
  'home.playerCoverAlt': 'Server cover',
  'home.uncategorized': 'Uncategorized',
  'home.noDescription': 'No description yet',

  // 分类展示（showcase）
  'home.showcaseDefaultResource': 'Random resource picks',
  'home.showcaseDefaultPlayer': 'Random server picks',
  'home.showcaseDefaultVideo': 'Random video picks',
  'home.showcaseDefaultCard': 'Featured card',
  'home.resourceCategoryFallback': 'Resource category',
  'home.playerCategoryFallback': 'Server category',
  'home.videoCategoryFallback': 'Video category',
  'home.viewDetails': 'View details',
  'home.allResources': 'All resources',
  'home.allPlayers': 'All servers',
  'home.allVideos': 'All videos',
  'home.viewAllResourcesAria': 'View all resources',
  'home.showcaseSelectorAria': 'Quick links for {title}',
  'home.cardShowcaseAria': 'Home page featured card',

  // 横幅与轮播
  'home.bannerDefaultLabel': 'Daily pick',
  'home.bannerDefaultTitle': 'Discover the best Minecraft resources',
  'home.bannerDefaultSubtitle': 'Explore mods, modpacks, shaders, and resource packs, and build the community together',
  'home.welcomeBannerTitle': 'Welcome to {name}',
  'home.bannerDotAria': 'Switch to banner {index}',
  'home.carouselPrev': 'Previous slide',
  'home.carouselNext': 'Next slide',

  // 区块标题与入口
  'home.latestResourcesTitle': 'Latest resources',
  'home.hotDiscussionsTitle': 'Trending discussions',
  'home.hotBoardsTitle': 'Popular boards',
  'home.collectionsTitle': 'Collections',
  'home.collectionsTitleWithSelection': 'Collections · {name}',
  'home.collectionsSelectLabel': 'Select a collection',
  'home.allCollections': 'All collections',
  'home.collectionsHistory': 'Collection history',
  'home.mcTipTitle': 'MC tips',
  'home.mcTipRefreshAria': 'Refresh MC tip',
  'home.mcTipRefreshTitle': 'Show another tip',
  'home.viewAll': 'View all',
  'home.checkInTitle': 'Daily check-in',
  'home.communityStatsTitle': 'Community stats',
  'home.hotTagsTitle': 'Popular tags',
  'home.onlineUsersTitle': 'Online users',
  'home.mobileSidebarAria': 'Home page auxiliary panels',
  'home.resourceShortcutsAria': 'Quick resource filters',

  // 排行榜
  'home.rankingSuffix': 'rankings',
  'home.rankingTitleWithSuffix': '{title} rankings',
  'home.rankingScopeFallback': 'Category ranking',
  'home.rankingSectionFallback': 'Ranking',
  'home.rankingScopeAria': '{title} scope',
  'home.rankingMetricAria': '{title} type',
  'home.rankingEmpty': 'No ranking data yet',

  // 单位与数值
  'home.unitRating': '{n} pts',
  'home.unitDownloads': '{n} downloads',
  'home.unitTimes': '{n} times',
  'home.unitDiscussions': '{n} replies',
  'home.unitViews': '{n} views',
  'home.ratingUnavailable': 'N/A',
  'home.onlineMode': 'Online mode',
  'home.offlineMode': 'Offline mode',

  // 空状态与加载态
  'home.refreshRetryDesc': 'Please refresh the page and try again.',
  'home.emptyResourcesTitle': 'No resources yet',
  'home.emptyResourcesDesc': 'There are no resources to show yet',
  'home.emptyCollectionResourcesTitle': 'No resources in this collection',
  'home.emptyCollectionResourcesDesc': 'This collection has no content to show yet',
  'home.emptyHistoryCollections': 'No collection history yet',
  'home.moreCollectionsTip': 'See the collections page for more collections',
  'home.emptyPostsTitle': 'No discussions yet',
  'home.emptyPostsDesc': 'There are no discussions to show yet',
  'home.emptyBoardsTitle': 'No boards yet',
  'home.emptyBoardsDesc': 'There are no popular boards to show yet',
  'home.emptyTopicsTitle': 'No topics yet',
  'home.emptyHotTags': 'No popular tags yet',
  'home.boardDescriptionFallback': 'Browse the active discussions in this board.',
  'home.resourceDescriptionFallback': 'Browse the resource summary, supported versions, and download info.',
  'home.postsLabel': 'Posts',
  'home.repliesLabel': 'Replies',
  'home.postActiveAt': 'Active {time}',
  'home.postUpdatedAt': 'Updated {time}',
  'home.downloadLabel': 'Download',
  'home.archived': 'Archived',
  'home.justNow': 'Just now',

  // MC 小贴士默认内容（站点设置缺失时的兜底）
  'home.mcTip1': 'Use a bed to skip the night quickly.',
  'home.mcTip2': 'Always carry a water bucket while mining.',
  'home.mcTip3': 'Follow the bees to find a nearby bee nest.',
  'home.mcTip4': 'Nether travel can greatly shorten long-distance routes.',
  'home.mcTip5': 'Name a mob to prevent it from despawning.',

  // 每日打卡
  'home.checkInDoing': 'Checking in...',
  'home.checkInDone': 'Checked in',
  'home.checkInAction': 'Check in',
  'home.checkInLoginText': 'Log in',
  'home.checkInLoginSuffix': ' to check in',
  'home.checkInReward': '+{n} activity credited',
  'home.checkInPointReward': ' · +{n} {name}',
  'home.checkInStreakSuffix': ' · {n}-day streak',
  'home.checkInToday': 'Check-ins today',
  'home.checkInStreak': 'Current streak',
  'home.checkInStreakDays': '{n} days',
  'home.checkInStatus': 'Check-in status',
  'home.checkInIncomplete': 'Not yet',
  'home.checkInVisitStatus': 'Visit status',
  'home.checkInGuest': 'Guest',
  'home.defaultPointName': 'Coins',

  // 社区统计
  'home.statsResources': 'Resources',
  'home.statsPosts': 'Posts',
  'home.statsToday': 'New today',
  'home.statsOnline': 'Online now',
  'home.statsUnavailable': 'Stats are temporarily unavailable',

  // 在线用户
  'home.onlineUsersCount': '{n} online',
  'home.onlineUsersLoading': 'Loading',
  'home.onlineUsersUnavailable': 'Unavailable',
  'home.onlineUsersFetchFailed': 'Unable to fetch right now',
  'home.onlineUsersError': 'Online users are temporarily unavailable',
  'home.onlineUsersEmpty': 'No users online yet',
  'home.onlineUsersAria': 'Currently online users',
  'home.onlineUsersActive': 'Online',
  'home.onlineUsersRefreshedJustNow': 'Refreshed just now',
  'home.onlineUsersRefreshedSeconds': 'Refreshed {n}s ago',
  'home.onlineUsersRefreshedMinutes': 'Refreshed {n}m ago',
  'home.onlineUsersRefreshedHours': 'Refreshed {n}h ago',
} as const;
