/** Generated from the legacy i18n module during the directory migration. */
export default {
'players.seoTitle': 'Minecraft server directory',
  'players.seoDescription': 'Browse Minecraft servers and discover communities offering survival, skyblock, minigames, RPG, and more.',
  'players.seoDescriptionLine1': 'Java and Bedrock Minecraft servers',
  'players.seoDescriptionLine2': 'Filter by platform, category, version, online-mode verification, and sorting',
  'players.seoDescriptionLine3': 'Compare server features, status, and player feedback to find a community to play',
  'players.keywordServers': 'Minecraft servers',
  'players.keywordFind': 'Find Minecraft servers',
  'players.keywordMinecraft': 'Minecraft server directory',
  'players.keywordJava': 'Java servers',
  'players.keywordBedrock': 'Bedrock servers',
  'players.keywordDirectory': 'Server listings',
  'players.allPlatforms': 'All platforms',
  'players.sort': 'Sort by',
  'players.latest': 'Latest',
  'players.updated': 'Recently updated',
  'players.views': 'Most viewed',
  'players.score': 'Best overall',
  'players.rating': 'Highest rated',
  'players.pageSize': 'Page size',
  'players.itemsPerPage': '{count} / page',
  'players.publish': 'Publish server',
  'players.filter': 'Filter',
  'players.platform': 'Platform',
  'players.category': 'Category',
  'players.version': 'Version',
  'players.allCategories': 'All categories',
  'players.allVersions': 'All versions',
  'players.onlineMode': 'Online-mode verification',
  'players.enabled': 'Enabled',
  'players.disabled': 'Disabled',
  'players.enabledOnlineMode': 'Online-mode enabled',
  'players.disabledOnlineMode': 'Online-mode disabled',
  'players.collection': 'Server collections',
  'players.collectionSummary': 'Collection: {value}',
  'players.collectionLabel': 'Collection: ',
  'players.viewCollections': 'View all collections',
  'players.collectionFilterTitle': 'Server collection filter',
  'players.reset': 'Reset',
  'players.cancel': 'Cancel',
  'players.apply': 'Apply',
  'players.creator.publishTitle': 'Publish server',
  'players.creator.editTitle': 'Edit server',
  'players.creator.publishDescription': 'Describe the server first, then add connection details, a cover, tutorials, and a gallery. If the address is hidden, provide an application link or community contact.',
  'players.creator.editDescription': 'Update information for a published server or draft.',
  'players.creator.reviewNotice': 'Submissions enter server review first and become public only after approval. If review fails, update the information as requested and submit again.',
  'players.creator.draftFound': 'An unfinished server draft was found',
  'players.creator.draftHelp': 'Choose which version to restore. Skipping will not delete the draft; restoring it replaces the current form.',
  'players.creator.localDraft': 'Local draft',
  'players.creator.cloudDraft': 'Cloud draft',
  'players.creator.newerContent': 'Newer content',
  'players.creator.unknownSaveTime': 'Save time unknown',
  'players.creator.restoreLocal': 'Restore local draft',
  'players.creator.restoreCloud': 'Restore cloud draft',
  'players.creator.skipRestore': 'Skip for now',
  'players.creator.required': 'Required',
  'players.creator.serverName': 'Server name',
  'players.creator.serverNamePlaceholder': 'For example: Star Harbor Survival',
  'players.creator.titleLimit': 'Up to 64 characters',
  'players.creator.intro': 'Introduction',
  'players.creator.introPlaceholder': 'Describe the server in one sentence',
  'players.creator.platform': 'Platform',
  'players.creator.javaEdition': 'Java Edition',
  'players.creator.bedrockEdition': 'Bedrock Edition',
  'players.creator.category': 'Category',
  'players.creator.chooseCategory': 'Choose a category',
  'players.creator.supportedVersions': 'Supported versions',
  'players.creator.networkEnvironment': 'Network environment',
  'players.creator.telecomNorth': 'China Telecom (North)',
  'players.creator.telecomSouth': 'China Telecom (South)',
  'players.creator.unicom': 'China Unicom',
  'players.creator.mobile': 'China Mobile',
  'players.creator.hmt': 'Hong Kong, Macao, and Taiwan',
  'players.creator.overseas': 'Overseas',
  'players.creator.onlineVerification': 'Online-mode verification',
  'players.creator.onlineEnabled': 'Online-mode enabled',
  'players.creator.onlineDisabled': 'Online-mode disabled',
  'players.creator.tags': 'Tags',
  'players.creator.tagsPlaceholder': 'Enter tags and search existing tags',
  'players.creator.tagsHelp': 'Search existing tags, press Enter to add, and click a tag to remove it',
  'players.creator.address': 'Server address/IP',
  'players.creator.port': 'Port',
  'players.creator.hideAddress': 'Hide server connection address',
  'players.creator.hideAddressHelp': 'Players will see only the application entry and the community contact details after verification.',
  'players.creator.joinUrl': 'Connection application link',
  'players.creator.joinUrlPlaceholder': 'https://example.com/join',
  'players.creator.joinUrlHelp': 'Use an http(s) webpage or public invite link here. Put QQ group numbers in the QQ field below. When hidden, at least one of this link, QQ, or Discord is required.',
  'players.creator.website': 'Website',
  'players.creator.cover': 'Server cover image',
  'players.creator.chooseCover': 'Choose cover image',
  'players.creator.coverHelp': 'Images are cropped to 16:9. PNG, JPG, and WebP are supported, up to 2 MB',
  'players.creator.coverUrlHelp': 'Uploading fills the cover URL automatically; an external URL can also be pasted manually',
  'players.creator.coverPlaceholder': 'https://... or /uploads/...',
  'players.creator.qq': 'QQ group',
  'players.creator.discord': 'Discord',
  'players.creator.details': 'Detailed description',
  'players.creator.tutorialIndex': 'Server tutorial index',
  'players.creator.tutorialPlaceholder': 'Search site tutorial posts and add them to this server',
  'players.creator.tutorialHelp': 'Collect tutorials related to this server. The details page shows them in its Tutorials tab.',
  'players.creator.gallery': 'Server gallery',
  'players.creator.galleryAuto': 'Automatically detect images in the description',
  'players.creator.galleryManual': 'Upload images to the gallery manually',
  'players.creator.galleryAutoHint': 'Images in the detailed description will be extracted into the gallery after publishing',
  'players.creator.galleryEditAutoHint': 'Images in the detailed description will be extracted into the gallery after saving',
  'players.creator.galleryUpload': 'Click or drag images here to upload',
  'players.creator.galleryFormatHelp': 'PNG, JPG, GIF, and WebP are supported; up to 5 MB each, multiple selection allowed',
  'players.creator.confirmBeforePublish': 'Confirm before publishing',
  'players.creator.submit': 'Submit for review',
  'players.creator.saveDraft': 'Save draft',
  'players.creator.save': 'Save changes',
  'players.creator.cancel': 'Cancel',
  'players.creator.backToList': 'Back to list',
} as const;
