/** Generated from the legacy i18n module during the directory migration. */
export default {
'profile.seoTitle': 'Account center',
  'profile.seoDescription': 'View account status, content history, tasks, points, and creator information in one place.',
  'profile.nextStep': 'Next step',
  'profile.continue': 'Continue',
  'profile.loginToView': 'Log in to view your account center',
  'profile.loginToViewHelp': 'Log in to see your favorites, tasks, assets, and creator status.',
  'profile.continueTasks': 'Continue growth tasks',
  'profile.taskProgressHelp': 'You have completed {done}/{total} tasks. Finish them to earn rewards and unlock community features.',
  'profile.unlockCapabilities': 'Unlock capabilities',
  'profile.unlockCapabilitiesHelp': 'Pass capability checks to unlock tipping, ratings, referrals, API tokens, and more.',
  'profile.creatorTodo': 'Handle creator tasks',
  'profile.creatorTodoHelp': '{count} items need review, changes, or follow-up.',
  'profile.openWorkbench': 'Open creator workbench',
  'profile.openWorkbenchHelp': 'Review content performance, publishing entry points, and next steps.',
  'profile.noRecord': 'No record yet',
  'profile.account': 'Account',
  'profile.username': 'Username',
  'profile.guest': 'Guest user',
  'profile.recentActivity': 'Recent activity',
  'profile.capabilities': 'Capabilities',
  'profile.items': '{count} items',
  'profile.content': 'Content',
  'profile.viewHistory': 'View history',
  'profile.favorites': 'Favorites',
  'profile.favoriteSummary': 'Resources {resources} · Posts {posts} · Servers {players} · Videos {videos}',
  'profile.browsingHistory': 'Browsing history',
  'profile.returnToRecent': 'Return to recently viewed content',
  'profile.growth': 'Growth',
  'profile.viewTasks': 'View tasks',
  'profile.taskProgress': 'Task progress',
  'profile.tasksComplete': '{done}/{total} tasks complete',
  'profile.noTaskData': 'No task data yet',
  'profile.notStarted': 'Not started',
  'profile.abilityCenter': 'Capability center',
  'profile.examsAvailable': '{count} certifications available',
  'profile.assets': 'Assets',
  'profile.viewAssets': 'View assets',
  'profile.points': 'Points',
  'profile.pointsSummary': 'Earned {earned} · Spent {spent}',
  'profile.noPointsAssets': 'No points assets yet',
  'profile.inventory': 'Item inventory',
  'profile.ownedItems': '{count} item types owned',
  'profile.availableItems': '{count} items available to buy',
  'profile.creation': 'Creation',
  'profile.openCreatorCenter': 'Open creator center',
  'profile.creatorStatus': 'Creator status',
  'profile.creatorStatusHelp': 'Your creator status will appear after you publish content.',
  'profile.navigation': 'Account center navigation',
  'profile.creatorCenter': 'Creator center',
} as const;
