/** Generated from the legacy i18n module during the directory migration. */
export default {
// ===== SEO：资源列表 =====
  'resources.seoListingDefaultTitle': 'Download and share Minecraft resources',
  'resources.seoListingDesc1': 'Browse the latest Minecraft plugins, mods, texture packs, maps, and shaders',
  'resources.seoListingDesc2': 'Filter and download resources by platform, category, and version',
  'resources.seoListingDesc3': 'Covers Java, Bedrock, and universal resources, with popular works and collections updated continuously',
  'resources.seoListingDescFallback': 'A community for downloading and sharing Minecraft resources',
  'resources.seoListingTitleSuffix': 'Minecraft resource downloads',
  'resources.seoKeywordMinecraft': 'Minecraft resources',
  'resources.seoKeywordPlugin': 'Minecraft plugins',
  'resources.seoKeywordMod': 'Minecraft mods',
  'resources.seoKeywordTexture': 'texture pack downloads',
  'resources.seoKeywordMap': 'map downloads',
  'resources.seoListingPageTitle': '{title} - Page {page}',
  'resources.seoDescOfficialTags': 'Official categories: {names}',
  'resources.seoDescPlatform': 'Platform: {platform}',
  'resources.seoDescCategory': 'Category: {category}',
  'resources.seoDescSubCategory': 'Subcategory: {subCategory}',
  'resources.seoDescThirdLevel': 'Sub-directions: {names}',
  'resources.seoDescVersion': 'Supported versions: {version}',
  'resources.seoDescCollection': 'Collections: {names}',
  'resources.seoDescSideSupport': 'Side support: {side}',
  'resources.seoDescSort': 'Browsing resources sorted by {sort}',
  'resources.seoDescPage': 'Currently showing page {page} of the resource list',
  'resources.seoJsonLdItemList': 'Resource list',
  'resources.seoJsonLdItemListTags': '{tags} resource list',
  'resources.seoJsonLdItemListDefault': 'Minecraft resource list',
  'resources.seoJsonLdItemListPlatform': '{platform} resource list',
  'resources.seoJsonLdItemListPlatformCategory': '{platform} {category} resource list',
  'resources.seoJsonLdItemListTagsPlatform': '{tags} {platform} resource list',

  // ===== SEO：平台筛选页兜底 =====
  'resources.seoPlatformDesc1': '{platform} Minecraft resource filter list',
  'resources.seoPlatformDescCover': 'Covers plugins, mods, texture packs, maps, and shaders',
  'resources.seoPlatformDescSub': 'Sub-type: {subCategory}',
  'resources.seoPlatformDescFilter': 'Filter and browse resources by platform, category, version, and collection',
  'resources.seoPlatformDescFallback': 'Browse and download Minecraft resources by category',

  // ===== SEO：资源详情 =====
  'resources.seoResourceCenter': 'Resource center',
  'resources.seoDetailTitle': '{title} - Resource center',
  'resources.seoDetailTitleWithTaxonomy': '{prefix} {title} - Resource center',
  'resources.seoDetailDefaultTitle': 'Resource details',
  'resources.seoDetailDescTags': 'Tags: {tags}',
  'resources.seoDetailDescDocs': '{count} resource docs organized',
  'resources.seoDetailDescAuthor': 'Author: {authors}',
  'resources.seoDetailDescTail': 'See download instructions, version info, changelogs, and usage guides',
  'resources.seoDetailDescFallback': 'Download instructions, version info, and usage guides for {title}',
  'resources.seoDetailKeywordDoc': '{title} docs',
  'resources.seoDetailKeywordTutorial': '{title} tutorial',
  'resources.seoDetailKeywordDocs': 'Resource docs',
  'resources.seoDetailUnavailableTitle': 'Resource temporarily unavailable',
  'resources.seoDetailUnavailableDesc': 'Resource details cannot be loaded right now. Please try again later.',
  'resources.seoDetailMissingTitle': 'Resource not found',
  'resources.seoDetailMissingDesc': 'This resource does not exist, has been taken down, or is not publicly available.',
  'resources.seoJsonLdDocsList': '{title} resource docs index',
  'resources.seoJsonLdDocItem': 'Doc {index}',
  'resources.seoJsonLdDocFallback': 'Resource doc',
  'resources.seoBreadcrumbResources': 'Resources',

  // ===== 平台/分类标题标签（SEO 与展示通用） =====
  'resources.taxonomyPlatformJava': 'Java Edition',
  'resources.taxonomyPlatformBedrock': 'Bedrock Edition',
  'resources.taxonomyPlatformUniversal': 'Universal',
  'resources.taxonomyCategoryPlugin': 'Plugin',
  'resources.taxonomyCategoryMod': 'Mod',
  'resources.taxonomyCategoryDatapack': 'Data pack',
  'resources.taxonomyCategoryTexture': 'Texture pack',
  'resources.taxonomyCategoryShader': 'Shader',
  'resources.taxonomyCategoryMap': 'Map',
  'resources.taxonomyCategoryModpack': 'Modpack',
  'resources.taxonomyCategoryBehaviorPack': 'Behavior pack',
  'resources.taxonomyCategoryUtility': 'Utility',
  'resources.taxonomyCategoryLauncher': 'Launcher',
  'resources.taxonomyCategoryServerPanel': 'Server panel',
  'resources.taxonomyCategorySkin': 'Skin',
  'resources.taxonomyCategoryPluginConfig': 'Plugin config pack',
  'resources.taxonomyCategoryModConfig': 'Mod config pack',
  'resources.taxonomyCategoryModel': 'Model',
  'resources.taxonomyCategoryProgramLauncher': 'Application launcher',

  // ===== 资源列表页：卡片与空状态（SSR） =====
  'resources.emptyResources': 'No resources yet',
  'resources.untitledResource': 'Untitled resource',
  'resources.cardDescriptionFallback': 'Browse the resource summary, supported versions, and download info.',
  'resources.uncategorized': 'Uncategorized',
  'resources.unitDownloads': '{n} downloads',
  'resources.noRating': 'No ratings yet',
  'resources.archived': 'Archived',
  'resources.viewDocumentation': 'View resource docs',

  // ===== 资源列表页：筛选与工具栏 =====
  'resources.filterAllPlatforms': 'All platforms',
  'resources.sortLabel': 'Sort by',
  'resources.sortLatest': 'Newest',
  'resources.sortUpdated': 'Recently updated',
  'resources.sortDownloads': 'Most downloads',
  'resources.sortScore': 'Overall',
  'resources.sortRating': 'Top rated',
  'resources.pageSizeLabel': 'Items per page',
  'resources.pageSizeOption': '{n} per page',
  'resources.publishAction': 'Publish resource',
  'resources.fieldPlatform': 'Platform',
  'resources.fieldCategory': 'Category',
  'resources.filterAllCategories': 'All categories',
  'resources.fieldSubCategory': 'Subcategory',
  'resources.fieldSideSupport': 'Side support',
  'resources.sideSupportBoth': 'Client & server',
  'resources.sideSupportClient': 'Client only',
  'resources.sideSupportServer': 'Server only',
  'resources.filterSubdivision': 'Sub-type',
  'resources.fieldGameVersion': 'Game version',
  'resources.filterAllVersions': 'All versions',
  'resources.fieldSort': 'Sort',
  'resources.officialTagsAll': 'Official categories: All',
  'resources.collectionFilterShort': 'Collection filter',
  'resources.categorySectionTitle': 'Resource categories',
  'resources.officialTagsTitle': 'Official categories',
  'resources.officialTagsClear': 'Clear official categories',
  'resources.collectionSectionTitle': 'Resource collections',
  'resources.viewAllCollections': 'View all collections',
  'resources.collectionModalTitle': 'Resource collection filter',
  'resources.officialTagsModalTitle': 'Official category filter',
  'resources.applyAction': 'Apply',
  'resources.officialTagsEmpty': 'No options in this category yet',
  'resources.officialTagsSummary': 'Official categories: {summary}',
  'resources.officialTagsSummaryEmpty': 'Official categories: no options in this category yet',
  'resources.officialTagsGroupHeader': '{name} · Official categories',
  'resources.selectedCount': '{n} selected',

  // ===== 资源文档页 =====
  'resources.docTocEmpty': 'No headings on this page yet',
  'resources.docBodyLoadFailed': 'Failed to load the content. Please refresh and try again.',
  'resources.docBodyEmpty': 'This document has no content to display yet.',
  'resources.docBodyRenderFailed': 'Failed to render the content. Please refresh and try again.',

  // ===== 资源卡片组件 =====
  'resources.downloadLabel': 'Download',
  'resources.cardDescription': 'Browse the resource summary, supported versions, and download info.',
} as const;
