/** Generated from the legacy i18n module during the directory migration. */
export default {
'video.seoTitle': 'Minecraft videos',
  'video.seoDescription': 'Browse community Minecraft videos with category filters, sorting, and on-site discussion.',
  'video.seoDescriptionCategory': 'Browse Minecraft videos about {category}.',
  'video.pageTitle': 'Videos',
  'video.pageIntro': 'Watch off-site, then keep the discussion here.',
  'video.submit': 'Submit video',
  'video.sortLabel': 'Sort by',
  'video.latest': 'Latest',
  'video.discuss': 'Most discussed',
  'video.hot': 'Most viewed',
  'video.collectionSummary': 'Collection: {value}',
  'video.collectionLabel': 'Collection: ',
  'video.all': 'All',
  'video.emptyTitle': 'No public videos yet',
  'video.emptyDescription': 'Be the first to share an MC video worth discussing.',
  'video.previousPage': 'Previous',
  'video.nextPage': 'Next',
  'video.page': 'Page {page} / {total}',
  'video.sectionTitle': 'Video categories',
  'video.allVideos': 'All videos',
  'video.guidanceTitle': 'Submission notes',
  'video.guidanceBilibili': 'Bilibili, Tencent Video, and Douyin links are supported',
  'video.guidanceReview': 'Videos become public after review',
  'video.guidanceDiscussion': 'Keep the discussion on this site instead of reposting without context',
  'video.collectionFilterTitle': 'Video collection filter',
  'video.reset': 'Reset',
  'video.cancel': 'Cancel',
  'video.apply': 'Apply',
  'video.creator.submitTitle': 'Submit video',
  'video.creator.editTitle': 'Edit video',
  'video.creator.submitDescription': 'Paste a video link, then add a cover, category, intro, and tags. Approved videos will be shown on the site for discussion.',
  'video.creator.editDescription': 'Updated submissions go through review again while the existing discussion stays attached to this video.',
  'video.creator.sourceUrl': 'Video link',
  'video.creator.sourceUrlPlaceholder': 'Paste a Bilibili, Tencent Video, or Douyin link or share text',
  'video.creator.title': 'Title',
  'video.creator.titleOptional': 'Title (optional)',
  'video.creator.titlePlaceholder': 'Leave blank to generate a site default title',
  'video.creator.titleInputPlaceholder': 'Enter a video title',
  'video.creator.customSlug': 'Custom URL name',
  'video.creator.customSlugPlaceholder': 'Optional; leave blank to generate one from the title',
  'video.creator.customSlugHelp': 'This creates an easier-to-remember address such as `/video/your-name`.',
  'video.creator.coverOptional': 'Video cover (optional)',
  'video.creator.coverTip': 'External covers such as Douyin can be unstable, so uploading a site-hosted cover is recommended.',
  'video.creator.coverUploaded': 'Uploaded',
  'video.creator.coverNotUploaded': 'Not uploaded',
  'video.creator.coverPreview': 'The cover preview will appear here after upload',
  'video.creator.uploadCover': 'Upload cover',
  'video.creator.clearCover': 'Clear cover',
  'video.creator.coverFormatHelp': 'PNG, JPG, WebP, and GIF are supported. A landscape image under 4 MB is recommended.',
  'video.creator.category': 'Video category',
  'video.creator.categoryHint': 'Choose the category that best fits the content',
  'video.creator.categoryCount': '{count} items',
  'video.creator.unselectedCategory': 'No category selected',
  'video.creator.introOptional': 'Intro (optional)',
  'video.creator.introPlaceholder': 'Explain why it is worth watching or what you want people to discuss.',
  'video.creator.tagsOptional': 'Video tags (optional)',
  'video.creator.tagsPlaceholder': 'Enter tags and search existing site tags',
  'video.creator.tagsHelp': 'Tags support video search and SEO. Press Enter to add one and click a tag to remove it.',
  'video.creator.reviewNotice': 'Review checks whether the content relates to the Minecraft community, is suitable for public discussion, and avoids obvious violations or pure traffic diversion.',
  'video.creator.required': 'Required',
  'video.creator.optional': 'Optional',
  'video.creator.submit': 'Submit for review',
  'video.creator.save': 'Save changes',
  'video.creator.backToDetail': 'Back to details',
  'video.creator.cancel': 'Cancel',
  'video.creator.uploading': 'Uploading...',
  'video.creator.uploadFailed': 'Upload failed',
  'video.creator.checking': 'Checking...',
  'video.creator.submitting': 'Submitting...',
  'video.creator.saving': 'Saving...',
  'video.creator.processingTitle': 'Processing',
  'video.creator.publishingTitle': 'Publishing',
  'video.creator.savingTitle': 'Saving',
  'video.creator.receivedSubmit': 'Your video submission was received and is being checked...',
  'video.creator.receivedEdit': 'Your video changes were received and are being checked...',
  'video.creator.submittingHint': 'Submitting the video; please wait...',
  'video.creator.savingHint': 'Submitting the video changes; please wait...',
  'video.creator.uploadImageOnly': 'Only image files can be uploaded',
  'video.creator.coverTooLarge': 'The cover image cannot exceed 4 MB',
  'video.creator.coverUploadFailed': 'Cover upload failed',
  'video.creator.coverUploadSuccess': 'Video cover uploaded',
  'video.creator.submitSuccess': 'Video submitted and queued for review',
  'video.creator.editSuccess': 'Video updated and resubmitted for review',
  'video.creator.editPendingSuccess': 'Video updated; it is still under review',
  'video.creator.saveSuccess': 'Saved successfully',
  'video.creator.saveFailed': 'Save failed',
  'video.creator.resubmitting': 'This video was rejected. Saving changes will send it through review again.',
  'video.creator.pending': 'This video is still under review. You can continue adding or correcting information.',
  'video.creator.publishedEdit': 'Editing a published video sends it through review again, while the existing discussion remains available.',
  'video.creator.editHeaderHelp': 'Updated submissions go through review again while the existing discussion stays attached to this video.',
} as const;
