// Simplified Chinese server dictionary.
// The `errors.*` group is generated — edit scripts/errorMessageTranslations.ts and re-run
// `npx tsx scripts/extractErrorCatalog.ts` instead of editing it here.

const errors = {
  // --- generated: errors.* (P2-1, scripts/extractErrorCatalog.ts) ---
  'errors.2faIsNotEnabledOnYourAccount': '当前账号未启用 2FA 验证',
  'errors.aCategoryCannotBeSetAsItsOwnParent': '不能将自己设为父分类',
  'errors.aMigrationTaskIsCurrentlyRunning': '迁移任务正在运行中',
  'errors.aPasswordIsAlreadySetUseTheChangePasswordFeature': '已设置密码，请使用修改密码功能',
  'errors.aReasonIsRequiredWhenRejecting': '拒绝时必须填写原因',
  'errors.aReasonIsRequiredWhenRejecting2': '拒绝时必须填写理由',
  'errors.aReasonIsRequiredWhenRejectingInBulk': '批量拒绝时必须填写理由',
  'errors.aResolutionMustBeSelectedWhenClosingTheCase': '结案时必须选择处理措施',
  'errors.aSingleChunkCannotExceed': '单个分块不能超过 ',
  'errors.aTwoLayerPasswordIsAlreadySetChangeItThroughTheU': '已设置双层密码，请通过更新接口修改',
  'errors.aTwoLayerPasswordIsAlreadySetYouMustVerifyTheCur': '已设置双层密码，修改前必须验证当前双层密码',
  'errors.aTwoLayerPasswordIsEnabledDeleteTheTwoLayerPassw': '已启用双层密码，请先删除双层密码后再删除账号密码',
  'errors.aValidLoginSessionIsRequired': '需要有效的登录会话',
  'errors.aVerificationEmailWasJustSentPleaseWaitAMinuteAn': '验证邮件刚刚已发送，请一分钟后再试',
  'errors.accountHasBeenBanned': '账号已被封禁 (',
  'errors.accountNotFoundOrAlreadyDeleted': '账号不存在或已被删除',
  'errors.adminAccessRequiresBindingTwoStepVerification2fa': '后台访问要求先绑定二步验证(2FA)或通行密钥或设置双层密码',
  'errors.adminAccessRequiresCompletingSecurityVerificatio': '当前后台访问需要重新完成安全验证',
  'errors.administratorsHaveNotEnabledMessageAttachments': '管理员未开启消息附件功能',
  'errors.administratorsOnly': '仅管理员可操作',
  'errors.administratorsOnly2': '仅管理员可访问',
  'errors.aiDidNotReturnStructuredContent': 'AI 未返回结构化内容',
  'errors.aiRequestRecordNotFound': 'AI 请求记录不存在',
  'errors.aiReturnedNoUsableContent': 'AI 未返回可用内容',
  'errors.aiSkillNotFound': 'AI Skill 不存在',
  'errors.alibabaCloudGreenNetworkReturnedNoValidScenarioR': '阿里云绿网未返回有效场景结果',
  'errors.allInteractiveFeaturesAreDisabledOnThisSite': '站点已关闭全部互动功能',
  'errors.altchaHmacKeyIsNotConfiguredOrUsesAnInsecureExam': 'ALTCHA_HMAC_KEY 未配置或使用了不安全的示例值',
  'errors.anApplicationOfTheSameTypeIsAlreadyUnderReviewDo': '已有同类型申请正在审核，请勿重复提交',
  'errors.apiKeyNotFound': 'API 密钥不存在',
  'errors.apiTokenNotFound': 'API Token 不存在',
  'errors.applicationDetailsAreIncomplete': '申请资料未填写完整：',
  'errors.applicationNotFound': '应用不存在',
  'errors.applicationNotFoundOrDisabled': '应用不存在或已停用',
  'errors.applicationRecordNotFound': '申请记录不存在',
  'errors.approveYourBoundOauthApplicationFirst': '请先审核通过绑定的 OAuth 应用',
  'errors.archivedOrganizationsCannotBeFollowed': '已归档组织不能关注',
  'errors.archivedOrganizationsCannotBeJoined': '已归档组织不能加入',
  'errors.articleNotFound': '文章不存在',
  'errors.articleOrPurchasingUserNotFound': '文章或购买用户不存在',
  'errors.atLeastOneValidCallbackUrlIsRequired': '至少需要填写一个有效回调地址',
  'errors.atLeastOneVersionTagMustBeEnabled': '至少需要启用一个版本标签',
  'errors.backgroundImageProcessingFailedTheOriginalImageW': '图片后台处理失败，已保留原图',
  'errors.backupFileContainsDisallowedStatements': '备份文件包含不允许的语句: ',
  'errors.backupFileNotFound': '备份文件不存在',
  'errors.badgeIdentifierAlreadyExists': '徽章标识已存在',
  'errors.badgeNotFound': '徽章不存在',
  'errors.batchUploadFailed': '批量上传失败',
  'errors.becomingAViceLeaderRequiresAccountLevelLv': '成为副会长至少需要账号等级 Lv.',
  'errors.bindAnEmailOrAnotherLoginMethodBeforeUnbinding': '请先绑定邮箱或其他登录方式后再解绑',
  'errors.bindAnEmailToThisUserOrKeepAtLeastOneOtherLoginM': '请先为该用户绑定邮箱或保留至少一个其他登录方式后再删除',
  'errors.bindAnotherStrongVerificationMethodBeforeDeletin': '请先绑定其他强验证方式，再删除最后一个通行密钥',
  'errors.bindAtLeastOnePasskeyBeforeRemovingYourPassword': '请先绑定至少一个通行密钥后再删除密码',
  'errors.bingWebmasterResubmissionIsNotEnabled': 'Bing Webmaster 补推未启用',
  'errors.boardNotFound': '板块不存在',
  'errors.boardSlugAlreadyExists': '板块 slug 已存在',
  'errors.bucketNotFound': '存储桶不存在',
  'errors.bulkOperationFailedPleaseTryAgainLater': '批量操作失败，请稍后重试',
  'errors.callbackUrlValidationFailed': '回调地址校验失败',
  'errors.categoryGroupNameAndSlugAreRequired': '分类组名称和 slug 必填',
  'errors.categoryGroupSlugAlreadyExists': '分类组 slug 已存在',
  'errors.categoryNotFound': '分类不存在',
  'errors.chatRoomApplicationNotFound': '聊天室申请不存在',
  'errors.chatRoomNameCannotBeEmpty': '聊天室名称不能为空',
  'errors.chatRoomNotFoundOrAlreadyClosed': '聊天室不存在或已关闭',
  'errors.chatRoomNotFoundOrYouDoNotHavePermissionToAccess': '聊天室不存在或无权限访问',
  'errors.checkInFailed': '签到失败',
  'errors.chunkIndexOutOfRange': '分块序号超出范围',
  'errors.chunkSizeExceedsTheLimit': '分块大小超过限制',
  'errors.chunkedUploadParametersAreIncomplete': '分块上传参数不完整',
  'errors.clickOnceToGetTheServerConnectionAddressBeforeRa': '请先点击一次获取服务器连接地址后再评分',
  'errors.clickTheGetResourceButtonOnceBeforeRating': '请先点击一次获取资源按钮后再评分',
  'errors.codeNameUrlAndGroupidAreRequired': 'code, name, url, groupId 必填',
  'errors.commentContentCannotBeEmpty': '评论内容不能为空',
  'errors.commentsAreDisabledOnNonPublicPosts': '未公开帖子已关闭评论',
  'errors.commentsCannotExceed5000Characters': '评论内容不能超过 5000 字符',
  'errors.contactInfoCannotExceed120Characters': '联系方式不能超过 120 个字符',
  'errors.contentNotFound': '内容不存在',
  'errors.couldNotFind': 'ZIP 内没有找到 ',
  'errors.creatingAnOrganizationRequiresAccountLevelLv': '创建组织至少需要账号等级 Lv.',
  'errors.customCategoryGroupNotFound': '自定义分类组不存在',
  'errors.dateAndChangeValueCannotBeEmpty': '日期和变动值不能为空',
  'errors.defaultIsAReservedGroupNamePleaseChooseAnotherOn': 'default 为系统保留组名，请换一个名称',
  'errors.deleteOrMoveTheSubcategoriesFirst': '请先删除或移动子分类',
  'errors.descriptionCannotBeEmpty': '描述不能为空',
  'errors.descriptionCannotExceed300Characters': '简介不能超过 300 个字符',
  'errors.directUploadCurrentlyOnlySupportsFileUploads': '直传暂仅支持文件上传',
  'errors.directUploadFileSizeValidationFailed': '直传文件大小校验失败',
  'errors.directUploadParametersAreIncomplete': '直传参数不完整',
  'errors.documentGroupNameCannotBeEmpty': '文档组名称不能为空',
  'errors.downloadFailedHttp': '下载失败：HTTP ',
  'errors.draftNotFound': '草稿不存在',
  'errors.duplicateRuleId': '规则 ID 重复：',
  'errors.editsAreOnlyAllowedWithin2MinutesOfSending': '仅支持发送后 2 分钟内编辑',
  'errors.emailAlreadyExists': '邮箱已存在',
  'errors.emailDeliveryLogNotFound': '邮件发送日志不存在',
  'errors.emlPreviewNotFound': 'EML 预览不存在',
  'errors.emojiUrlCannotBeEmpty': '表情地址不能为空',
  'errors.enforcementActionsCanOnlyBeAppliedWhenClosingThe': '只有结案时可以执行处理措施',
  'errors.examKeyAndTitleCannotBeEmpty': '考试 key 和标题不能为空',
  'errors.examNotFoundOrNotOpen': '考试不存在或未开放',
  'errors.examQuestionSnapshotNotFound': '考试题目快照不存在',
  'errors.examRecordNotFound': '考试记录不存在',
  'errors.expiryDaysMustBeBetween1And365': '过期天数必须在 1 到 365 天之间',
  'errors.expiryDaysMustBeBetween1And365OrLeaveBlankForNoE': '过期天数必须在 1 到 365 天之间，或留空表示长期有效',
  'errors.failedToAcceptTheAnswer': '采纳答案失败',
  'errors.failedToAutoClaimTheTaskReward': '自动领取任务奖励失败',
  'errors.failedToAwardTheBountyTheAskerSPointsBalanceIsIn': '悬赏发放失败，提问者积分余额不足',
  'errors.failedToCancelTheChunkedUpload': '取消分块上传失败',
  'errors.failedToConfirmTheDirectUpload': '确认直传失败',
  'errors.failedToConfirmTheDirectUploadRetryWithARegularU': '确认直传失败，请改用普通上传重试',
  'errors.failedToCreateItem': '创建道具失败',
  'errors.failedToCreateThePointsSystem': '创建积分体系失败',
  'errors.failedToCreateTheVerificationCategory': '认证分类创建失败',
  'errors.failedToDeleteThePasskey': '删除通行密钥失败',
  'errors.failedToDeleteTheQuestion': '删除题目失败',
  'errors.failedToDeleteTheVerificationCategory': '认证分类删除失败',
  'errors.failedToDownloadOrConvertTheExternalAvatar': '头像外链下载或转换失败',
  'errors.failedToDownloadTheFile': '下载文件失败',
  'errors.failedToFetchCheckInStatus': '获取签到状态失败',
  'errors.failedToFetchExamDetails': '获取考试详情失败',
  'errors.failedToFetchImage': '抓取图片失败 (',
  'errors.failedToFetchItemStock': '获取道具库存失败',
  'errors.failedToFetchMinecraftPremiumVerificationStatus': '获取 Minecraft 正版验证功能状态失败',
  'errors.failedToFetchPostPointsInfo': '获取帖子积分信息失败',
  'errors.failedToFetchReferralCodeStatistics': '获取推广码统计失败',
  'errors.failedToFetchReferralRewardRecords': '获取推广奖励流水失败',
  'errors.failedToFetchTheChunkedUploadStatus': '获取分块上传状态失败',
  'errors.failedToFetchThePointsSystem': '获取积分体系失败',
  'errors.failedToFetchVideoPointsInfo': '获取视频积分信息失败',
  'errors.failedToGenerateLoginOptions': '生成登录选项失败',
  'errors.failedToGeneratePasskeyOptions': '生成通行密钥选项失败',
  'errors.failedToGenerateRegistrationOptions': '生成注册选项失败',
  'errors.failedToGenerateTheReferralCodePleaseTryAgainLat': '生成推广码失败，请稍后重试',
  'errors.failedToGetMinecraftCapeStatus': '获取 Minecraft 披风状态失败',
  'errors.failedToGetTheMicrosoftBindingStatus': '获取 Microsoft 绑定状态失败',
  'errors.failedToGetTheMinecraftPremiumVerificationRecord': '获取 Minecraft 正版验证记录失败',
  'errors.failedToInitializeAiManagementDataTables': 'AI 管理数据表初始化失败',
  'errors.failedToInitializeTheChunkedUpload': '初始化分块上传失败',
  'errors.failedToInitializeTheDirectUpload': '初始化直传失败',
  'errors.failedToLoadCreatorData': '创作者数据加载失败',
  'errors.failedToLoadExistingVerifications': '已有认证加载失败',
  'errors.failedToLoadGeeidStatus': 'GeeID 状态加载失败',
  'errors.failedToLoadItemPurchaseRecords': '获取道具购买记录失败',
  'errors.failedToLoadItemUsageRecords': '获取道具使用记录失败',
  'errors.failedToLoadLogDetails': '日志详情读取失败',
  'errors.failedToLoadLogOperationOptions': '日志操作选项读取失败',
  'errors.failedToLoadPointsHistory': '获取积分流水失败',
  'errors.failedToLoadPointsStatistics': '获取积分统计失败',
  'errors.failedToLoadQuestionBankDetails': '获取题库详情失败',
  'errors.failedToLoadReferralCodeSettings': '获取推广码设置失败',
  'errors.failedToLoadReferralRecords': '获取推广记录失败',
  'errors.failedToLoadResourcePointsInformation': '获取资源积分信息失败',
  'errors.failedToLoadServerPointsInformation': '获取服务器积分信息失败',
  'errors.failedToLoadShopItems': '获取道具商品失败',
  'errors.failedToLoadTheCapeShowcase': '获取披风橱窗失败',
  'errors.failedToLoadTheDefaultTemplatePreview': '获取默认模板预览失败',
  'errors.failedToLoadTheExamList': '获取考试列表失败',
  'errors.failedToLoadThePasskeyList': '获取通行密钥列表失败',
  'errors.failedToLoadTheQuestionBankList': '获取题库列表失败',
  'errors.failedToLoadTheReferralCodePointsSystem': '获取推广码积分体系失败',
  'errors.failedToLoadTheTaskOverview': '获取任务概览失败',
  'errors.failedToLoadTheVerificationApplicationList': '认证申请列表加载失败',
  'errors.failedToLoadTheVerificationAuthorizationList': '认证授权列表加载失败',
  'errors.failedToLoadUploadLimits': '获取上传限制失败',
  'errors.failedToLoadUserPoints': '获取用户积分失败',
  'errors.failedToLoadVerificationApplicationEligibility': '认证申请资格加载失败',
  'errors.failedToLoadVerificationCategories': '认证分类加载失败',
  'errors.failedToMergeTheChunkedUpload': '合并分块上传失败',
  'errors.failedToObtainAMinecraftServiceAccessToken': '无法获取 Minecraft 服务访问令牌',
  'errors.failedToPayOutThePollRewardThePosterDoesNotHaveE': '投票奖励发放失败，发帖者积分余额不足',
  'errors.failedToQueryEmailSendLogs': '邮件发送日志查询失败',
  'errors.failedToQueryLogs': '日志查询失败',
  'errors.failedToQueryTheLogTrace': '日志链路查询失败',
  'errors.failedToReadTheEmailDeliveryLogDetails': '邮件发送日志详情读取失败',
  'errors.failedToReadTheEmlPreview': 'EML 预览读取失败',
  'errors.failedToRegisterThePasskey': '注册通行密钥失败',
  'errors.failedToRemoveThePassword': '删除密码失败',
  'errors.failedToRenameThePasskey': '重命名通行密钥失败',
  'errors.failedToResetTheKey': '重置密钥失败',
  'errors.failedToReviewTheVerificationApplication': '认证申请审核失败',
  'errors.failedToRevokeAuthorization': '撤销授权失败',
  'errors.failedToSend': '发送失败',
  'errors.failedToSendPleaseTryAgainLater': '发送失败，请稍后重试',
  'errors.failedToSendTheEmailCheckTheMailConnectionConfig': '邮件发送失败，请检查邮件连接配置',
  'errors.failedToSendTheLoginEmailCheckYourEmailConfigura': '登录邮件发送失败，请检查邮箱配置',
  'errors.failedToSendTheResetEmailCheckYourEmailConfigura': '重置邮件发送失败，请检查邮箱配置',
  'errors.failedToSendTheTemplateEmailCheckTheSmtpConfigur': '模板邮件发送失败，请检查邮件连接配置或模板内容',
  'errors.failedToSendTheVerificationCodeEmailCheckTheEmai': '验证码邮件发送失败，请检查邮箱配置',
  'errors.failedToSendTheVerificationEmailCheckTheEmailCon': '验证邮件发送失败，请检查邮箱配置',
  'errors.failedToSendTheVerificationEmailCheckTheMailServ': '验证邮件发送失败，请检查邮件服务配置后重试',
  'errors.failedToSendTheVerificationEmailPleaseTryAgain': '验证邮件发送失败，请重试',
  'errors.failedToSetThePassword': '设置密码失败',
  'errors.failedToSubmitTheVerificationApplicationPleaseTr': '认证申请提交失败，请稍后重试',
  'errors.failedToUpdateTheItem': '更新道具失败',
  'errors.failedToUpdateThePointsSystem': '更新积分体系失败',
  'errors.failedToUpdateTheVerificationAuthorization': '认证授权更新失败',
  'errors.failedToUpdateTheVerificationCategory': '认证分类更新失败',
  'errors.failedToUploadTheChunk': '上传分块失败',
  'errors.featuredProjectsCannotBeDuplicated': '精选项目不能重复',
  'errors.feedbackPostNotFound': '建议反馈帖子不存在',
  'errors.fetchFailed': '抓取失败 (',
  'errors.forAccountSecurityBindTwoStepVerification2faOrAP': '为保障账号安全，请先在设置中绑定二步验证(2FA)或通行密钥或设置双层密码后再执行此操作',
  'errors.geeIdDirectRegistrationIsCurrentlyUnavailable': 'Gee ID 直注册当前不可用',
  'errors.geeIdDirectRegistrationIsNotEnabled': 'Gee ID 直注册功能未启用',
  'errors.geeIdMainlandChinaPhoneBindingIsNotSupportedForT': '当前账号注册地区暂不支持 Gee ID 大陆手机号绑定',
  'errors.geeIdOauthAuthorizationCodeWasGeneratedButNoCode': 'Gee ID OAuth 授权码生成成功，但未返回 code',
  'errors.geeIdOauthAutoAuthorizationIsNotEnabled': 'Gee ID OAuth 自动授权功能未启用',
  'errors.geeIdOauthBindingHasNotBeenCompletedYet': 'Gee ID OAuth 绑定尚未完成',
  'errors.geeIdOauthUserInfoDidNotReturnAUserId': 'Gee ID OAuth 用户信息未返回用户 ID',
  'errors.geeIdPhoneBindingIsNotEnabled': 'Gee ID 手机绑定功能未启用',
  'errors.geeIdPhoneBindingIsNotEnabled2': '当前未启用 Gee ID 手机绑定',
  'errors.geeIdRequestTimedOutPleaseTryAgainLater': 'Gee ID 请求超时，请稍后重试',
  'errors.geeIdUserLookupRequiresAValidIdUsernameEmailOrPh': 'Gee ID 用户查询缺少有效的 id、username、email 或 phone',
  'errors.geeidOauthClientIdClientSecretIsNotConfiguredSoA': 'GeeID OAuth client_id / client_secret 未配置，无法自动绑定',
  'errors.geeidOauthLoginIsNotEnabledSoAutoBindingIsNotPos': 'GeeID OAuth 登录未启用，无法自动绑定',
  'errors.groupChatNameCannotBeEmpty': '群聊名称不能为空',
  'errors.groupNameCannotBeEmpty': '分组名称不能为空',
  'errors.groupNotFound': '分组不存在',
  'errors.groupidIsRequired': 'groupId 必填',
  'errors.idsCannotBeEmpty': 'ids 不能为空',
  'errors.imageContentIsEmpty': '图片内容为空',
  'errors.imageDownloadInterrupted': '图片下载中断',
  'errors.imageFetchTimedOut': '抓取图片超时',
  'errors.imageProcessingTaskNotFound': '图片处理任务不存在',
  'errors.incorrect2faCodeOrBackupCode': '2FA 验证码或备用码不正确',
  'errors.incorrectAccessCode': '访问口令错误',
  'errors.incorrectChunkSize': '分块大小不正确',
  'errors.incorrectNumberOfChunks': '分块数量不正确',
  'errors.incorrectPassword': '密码不正确',
  'errors.installationFromTheAdminPanelRequiresAnHttpsUrl': '后台安装仅允许 HTTPS 地址',
  'errors.insufficientItemStock': '道具库存不足',
  'errors.insufficientPointsBalance': '积分余额不足',
  'errors.interactionButtonMessagesCanOnlyBeSentByBots': '互动按钮消息仅允许机器人发送',
  'errors.interactionsAreDisabledForNonPublicContent': '未公开内容已关闭互动',
  'errors.interactionsAreDisabledForNonPublicResources': '未公开资源已关闭互动',
  'errors.interactionsAreDisabledForUnpublishedPosts': '未公开帖子已关闭互动',
  'errors.internalServerError': '服务器内部错误',
  'errors.invalidApplicationType': '申请类型无效',
  'errors.invalidAuthorizationParameters': '授权参数无效',
  'errors.invalidAuthorizationTargetType': '授权对象类型无效',
  'errors.invalidBeforeParameter': '无效的 before 参数',
  'errors.invalidBingWebmasterApiKeyFormat': 'Bing Webmaster API Key 格式无效',
  'errors.invalidChunkedUploadParameters': '分块上传参数无效',
  'errors.invalidCleanupItems': '无效清理项: ',
  'errors.invalidContactEmailFormat': '联系邮箱格式不正确',
  'errors.invalidContactPhoneNumberFormat': '联系手机号格式不正确',
  'errors.invalidContentType': '内容类型无效',
  'errors.invalidCursor': 'cursor 无效',
  'errors.invalidDataFormatAJsonArrayIsRequired': '数据格式错误，需要 JSON 数组',
  'errors.invalidDescriptionFormat': '描述格式无效',
  'errors.invalidDirectUploadConfirmationParameters': '直传确认参数无效',
  'errors.invalidDisabledOrExpiredSiteApiKey': '无效、已停用或已过期的站点 API 密钥',
  'errors.invalidDocumentGroupSlug': '文档组 slug 无效',
  'errors.invalidEmailFormat': '邮箱格式不正确',
  'errors.invalidEmojiUrl': '表情地址无效',
  'errors.invalidExpirationDateFormat': '到期时间格式无效',
  'errors.invalidExternalAccountLinkFormat': '站外账号链接格式不正确',
  'errors.invalidFeaturedItem': '精选项目无效',
  'errors.invalidFilePath': '非法文件路径',
  'errors.invalidIconRedirectUrl': '图标重定向地址无效',
  'errors.invalidIconUrlFormat': '图标链接格式不正确',
  'errors.invalidImageProcessingTaskParameters': '图片处理任务参数无效',
  'errors.invalidIndexIdentifier': '索引标识无效',
  'errors.invalidIp2locationBinFileHeader': 'IP2Location BIN 文件头无效',
  'errors.invalidIp2locationUpdateTime': 'IP2Location 更新时间无效',
  'errors.invalidJoinLinkOrJoinCode': '加入链接或加入代码无效',
  'errors.invalidLogId': '日志 ID 无效',
  'errors.invalidNotificationStatus': '通知状态不合法',
  'errors.invalidNotificationType': '通知类型不合法',
  'errors.invalidOfficialWebsiteUrlFormat': '官网地址格式不正确',
  'errors.invalidOperation': '无效操作',
  'errors.invalidOrExpiredVerificationCode': '验证码无效或已过期',
  'errors.invalidParameter': '无效参数',
  'errors.invalidPasskeyResponse': '无效的通行密钥响应',
  'errors.invalidPhoneBindingScope': '无效的手机号绑定范围',
  'errors.invalidQueryParameters': '查询参数无效',
  'errors.invalidQuestionContentOrQuestionType': '题目内容或题型无效',
  'errors.invalidRateLimitConfigurationFormat': '限流配置格式无效',
  'errors.invalidReferenceType': '引用类型无效',
  'errors.invalidReferralCodeFormat': '推广码格式无效',
  'errors.invalidRegularExpression': '无效的正则表达式',
  'errors.invalidRegularExpression2': '正则表达式不合法',
  'errors.invalidReportReason': '无效的举报原因',
  'errors.invalidReportType': '无效的举报类型',
  'errors.invalidReviewAction': '审核动作无效',
  'errors.invalidRevokedOrExpiredOauthAccessToken': '无效、已撤销或已过期的 OAuth Access Token',
  'errors.invalidSecurityVerificationScope': '无效的安全校验范围',
  'errors.invalidSelectedOrganizationType': '所选组织类型无效',
  'errors.invalidServerPort': '服务器端口无效',
  'errors.invalidSkillDownloadRedirect': 'Skill 下载重定向无效 (',
  'errors.invalidSkillMdHeaderFormat': 'SKILL.md 头信息格式错误：',
  'errors.invalidSlug': 'slug 无效',
  'errors.invalidSortData': '排序数据无效',
  'errors.invalidTagGroupSlug': '标签组 slug 无效',
  'errors.invalidTargetType': '无效的目标类型',
  'errors.invalidTargetUserType': '目标用户类型不合法',
  'errors.invalidTencentCloudSesCredentialFormat': '腾讯云 SES 凭据格式不正确',
  'errors.invalidTestEnglishUsernameItMustBe316LettersDigi': '测试英文用户名格式不正确，需为 3-16 位英文、数字或下划线',
  'errors.invalidTopicCategoryGroupSlug': '话题分类组 slug 不合法',
  'errors.invalidVerificationCodeMakeSureYourPhoneTimeIsSy': '验证码无效，请确认手机时间已自动同步，或重新扫描最新二维码后再试',
  'errors.invalidVerificationCodePleaseRequestANewOne': '验证码无效，请重新获取',
  'errors.invalidVideoSectionId': '视频分区 ID 无效',
  'errors.invalidXdbFileHeader': 'xdb 文件头无效',
  'errors.invalidZipCentralDirectory': 'ZIP 中央目录无效',
  'errors.invalidZipFileStructure': 'ZIP 文件结构无效',
  'errors.invalidZipLocalFileHeader': 'ZIP 本地文件头无效',
  'errors.inviterNotFound': '邀请人不存在',
  'errors.ip2locationOnlySupportsBinFiles': 'IP2Location 仅支持 .BIN 文件',
  'errors.ip2locationOnlySupportsBinOrBinZipFiles': 'IP2Location 仅支持 .BIN 或 .BIN.ZIP 文件',
  'errors.ip2locationTokenIsNotConfigured': 'IP2Location token 未配置',
  'errors.ip2regionOnlySupportsXdbFiles': 'ip2region 仅支持 .xdb 文件',
  'errors.itemIdentifierAlreadyExists': '道具标识已存在',
  'errors.itemNotFound': '道具不存在',
  'errors.itemNotFoundOrNotAvailable': '道具不存在或未上架',
  'errors.joinCodeCannotBeEmpty': '加入代码不能为空',
  'errors.joiningAnOrganizationRequiresAtLeastAccountLevel': '加入组织至少需要账号等级 Lv.',
  'errors.keyAlreadyExists': 'key 已存在',
  'errors.keyAndNameAreRequired': 'key 和 name 必填',
  'errors.licenseIdentifierAlreadyExists': '许可证标识已存在',
  'errors.licenseNameAndIdentifierCannotBeEmpty': '许可证名称和标识不能为空',
  'errors.linkExchangeApplicationsAreCurrentlyClosed': '当前未开放友情链接申请',
  'errors.linkIsTooLong': '链接过长',
  'errors.listingCategoryNameCannotBeEmpty': '收录分类名称不能为空',
  'errors.listingCategoryNotFound': '收录分类不存在',
  'errors.localOrIntranetAddressesAreNotAllowed': '不允许使用本地或内网地址',
  'errors.logIdCannotBeEmpty': '日志 ID 不能为空',
  'errors.logNotFoundOrAlreadyPurged': '日志不存在或已被清理',
  'errors.mainlandChinaPhoneBindingForGeeIdIsNotSupportedI': '当前访问地区暂不支持 Gee ID 中国大陆手机号绑定',
  'errors.makeUpCheckInCardsCanOnlyBeUsedForDatesBeforeTod': '补签卡只能用于今天之前的日期',
  'errors.memberListCannotBeEmpty': '成员列表不能为空',
  'errors.messageContentCannotBeEmpty': '消息内容不能为空',
  'errors.messageNotFound': '消息不存在',
  'errors.messagesCanOnlyBeRecalledWithin2MinutesOfSending': '仅支持发送后 2 分钟内撤回',
  'errors.missingBingWebmasterSecretJwtSecretOrCookieSecre': '缺少 BING_WEBMASTER_SECRET、JWT_SECRET 或 COOKIE_SECRET，无法安全保存 Bing API Key',
  'errors.missingGeeIdAccountIdentifier': '缺少 Gee ID 账号标识',
  'errors.missingIconUrl': '缺少图标地址',
  'errors.missingLinkUrl': '缺少链接地址',
  'errors.missingParameters': '缺少参数',
  'errors.missingRequiredFields': '缺少必填字段',
  'errors.missingRequiredParameters': '缺少必要参数',
  'errors.missingToken': '缺少 token',
  'errors.moderatorsCanOnlyHandleRegularUsers': '版主只能处理普通用户',
  'errors.moderatorsCanOnlyIssueWarningsWithinReportsAssig': '版主只能在其管辖举报上下文中发出警告',
  'errors.moderatorsCanOnlyWarnRegularUsers': '版主只能警告普通用户',
  'errors.nameAndLinkCannotBeEmpty': '名称和链接不能为空',
  'errors.nameAndSlugCannotBeEmpty': '名称和 slug 不能为空',
  'errors.nameCannotBeEmpty': '名称不能为空',
  'errors.nameCannotExceed60Characters': '名称不能超过 60 个字符',
  'errors.nameOrSlugAlreadyExists': '名称或 slug 已存在',
  'errors.noContentAvailableToSummarize': '无法读取可总结的内容',
  'errors.noDirectUploadUrlIsAvailableRightNowUseARegularU': '当前没有可用的直传上传地址，请改用普通上传或稍后重试',
  'errors.noMatchingPasskeyFoundMakeSureThisDeviceHasARegi': '未找到对应的通行密钥，请确认该设备已注册通行密钥',
  'errors.noMatchingPasskeyWasFound': '未找到对应的通行密钥',
  'errors.noMatchingUsersFound': '未匹配到任何用户',
  'errors.noPasswordIsCurrentlySet': '当前未设置密码',
  'errors.noPermissionOnlyAdministratorsAndForumModerators': '无权限：仅管理员和论坛版主可审核帖子',
  'errors.noPermissionOnlyAdministratorsAndForumModerators2': '无权限：仅管理员和论坛版主可审核帖子回复',
  'errors.noPermissionOnlyAdministratorsAndResourceModerat': '无权限：仅管理员和资源版主可审核资源',
  'errors.noPermissionOnlyAdministratorsAndServerFinderMod': '无权限：仅管理员和找服玩版主可审核服务器评论',
  'errors.noPermissionOnlyAdministratorsAndSuperModerators': '无权限：仅管理员和总版主可审核用户资料变更',
  'errors.noPermissionOnlyAdministratorsAndSuperModerators2': '无权限：仅管理员和总版主可审核组织资料变更',
  'errors.noPermissionOnlyAdministratorsAndVideoModerators': '无权限：仅管理员和视频版主可审核视频',
  'errors.noPermissionOnlyAdministratorsAndVideoModerators2': '无权限：仅管理员和视频版主可审核视频讨论',
  'errors.noPermissionOnlyAdminsAndForumModeratorsCanRevie': '无权限：仅管理员和论坛版主可审核帖子评论',
  'errors.noPermissionOnlyAdminsAndResourceModeratorsCanRe': '无权限：仅管理员和资源版主可审核资源评论',
  'errors.noPermissionOnlyAdminsAndServerFinderModeratorsC': '无权限：仅管理员和找服玩版主可审核服务器',
  'errors.noSettingsToUpdate': '没有可更新的设置',
  'errors.noStorageMethodIsEnabled': '未启用任何存储方式',
  'errors.noStorageMethodIsEnabledPleaseContactAnAdministr': '未启用任何存储方式，请联系管理员',
  'errors.noUsablePasskeyFound': '未找到可用的通行密钥',
  'errors.noUsableQuestionsFoundInTheImportedJson': '导入 JSON 中没有可用题目',
  'errors.noUsersMatchedForCompensation': '没有匹配到可补偿用户',
  'errors.noValidChatRoomInvitationFound': '未找到有效的聊天室邀请',
  'errors.noValidSkillMdYamlFrontmatterWasFound': '未找到有效的 SKILL.md YAML 头信息',
  'errors.noValidUsersToAdd': '没有可添加的有效用户',
  'errors.normalizedSettingExceeds': '规范化设置项越过 ',
  'errors.notBoundToThisAccount': '未绑定该账号',
  'errors.notLoggedIn': '未登录',
  'errors.notificationNotFound': '通知不存在',
  'errors.notificationTitleCannotBeEmpty': '通知标题不能为空',
  'errors.oauthApplicationRequestNotFound': 'OAuth 应用申请不存在',
  'errors.oauthUserIdentityNotFound': 'OAuth 用户身份不存在',
  'errors.offSiteAccountsMustHaveAtLeast10000Followers': '站外账号粉丝量需达到 10,000 人',
  'errors.only730Or90DayDataAnalysisIsSupported': '仅支持 7、30 或 90 天的数据分析',
  'errors.onlyAdministratorsAndModeratorsCanAccessAccountA': '仅管理员和版主可访问账号分析',
  'errors.onlyAdministratorsAndSuperModeratorsCanManageBad': '仅管理员和总版主可管理徽章',
  'errors.onlyAdministratorsAndSuperModeratorsCanManageCus': '仅管理员和总版主可管理自定义页面',
  'errors.onlyAdministratorsAndSuperModeratorsCanManageFil': '仅管理员和总版主可操作过滤规则',
  'errors.onlyAdministratorsAndSuperModeratorsCanManageFri': '仅管理员和总版主可管理友情链接',
  'errors.onlyAdministratorsAndSuperModeratorsCanManageThe': '仅管理员和总版主可管理考试系统',
  'errors.onlyAdministratorsAndSuperModeratorsCanManageThi': '仅管理员和总版主可操作该内容配置',
  'errors.onlyAdministratorsAndSuperModeratorsCanSubmitSeo': '仅管理员和总版主可执行 SEO 推送',
  'errors.onlyAdministratorsCanAccessChatRoomManagement': '仅管理员可访问聊天室管理',
  'errors.onlyAdministratorsCanAccessSiteSettings': '仅管理员可访问站点设置',
  'errors.onlyAdministratorsCanChangeRoles': '仅管理员可修改角色',
  'errors.onlyAdministratorsCanChangeTheBingWebmasterConfi': '仅管理员可修改 Bing Webmaster 配置',
  'errors.onlyAdministratorsCanConfigureCategoryModerators': '仅管理员可配置分类版主',
  'errors.onlyAdministratorsCanConfigureModeratorScopes': '仅管理员可配置版主管辖范围',
  'errors.onlyAdministratorsCanConfigurePaidArticlePublish': '仅管理员可配置付费文章发布权限',
  'errors.onlyAdministratorsCanGenerateTheIndexnowKey': '仅管理员可生成 IndexNow Key',
  'errors.onlyAdministratorsCanManageDevelopmentLogs': '仅管理员可管理开发日志',
  'errors.onlyAdministratorsCanManageLeaderboards': '仅管理员可管理排行榜',
  'errors.onlyAdministratorsCanManageOperationsNotificatio': '仅管理员可管理运营通知',
  'errors.onlyAdministratorsCanManageOrganizations': '仅管理员可管理组织',
  'errors.onlyAdministratorsCanManageUserLoginDevices': '仅管理员可管理用户登录设备',
  'errors.onlyAdministratorsCanManageUsersPersonalApiToken': '仅管理员可管理用户个人 API Token',
  'errors.onlyAdministratorsCanModifyPersonalApiRateLimitR': '仅管理员可修改个人 API 限流规则',
  'errors.onlyAdministratorsCanModifySiteSettings': '仅管理员可修改站点设置',
  'errors.onlyAdministratorsCanPerformThisAction': '仅管理员可执行此操作',
  'errors.onlyAdministratorsCanPurgeDatabaseRecords': '仅管理员可清理数据库记录',
  'errors.onlyAdministratorsCanSendVerificationEmails': '仅管理员可发送验证邮件',
  'errors.onlyAdministratorsCanViewEmailDeliveryLogs': '仅管理员可查看邮件发送日志',
  'errors.onlyAdministratorsCanViewPersonalApiRateLimitRul': '仅管理员可查看个人 API 限流规则',
  'errors.onlyAdministratorsSuperModeratorsAndContentModer': '仅管理员、总版主与内容版主可访问',
  'errors.onlyAdministratorsSuperModeratorsAndResourceMode': '仅管理员、总版主和资源版主可操作该内容配置',
  'errors.onlyAdministratorsSuperModeratorsAndVideoModerat': '仅管理员、总版主和视频版主可操作该内容配置',
  'errors.onlyAdministratorsSuperModeratorsResourceModerat': '仅管理员、总版主、资源版主与找服玩版主可访问',
  'errors.onlyAdministratorsSuperModeratorsResourceModerat2': '仅管理员、总版主、资源版主与论坛版主可访问',
  'errors.onlyAdminsAndSuperModeratorsCanManageEmojiResour': '仅管理员和总版主可管理表情资源',
  'errors.onlyAdminsAndSuperModeratorsCanManageVerificatio': '仅管理员和总版主可管理认证',
  'errors.onlyAdminsAndSuperModeratorsCanManageVersionConf': '仅管理员和总版主可操作版本配置',
  'errors.onlyAdminsAndSuperModeratorsCanSearchUserInfo': '仅管理员和总版主可检索用户信息',
  'errors.onlyAdminsCanAccessErrorPageManagement': '仅管理员可访问错误页管理',
  'errors.onlyAdminsCanAssignSectionModerators': '仅管理员可配置板块版主',
  'errors.onlyAdminsCanChangeEmailVerificationStatus': '仅管理员可修改邮箱验证状态',
  'errors.onlyAdminsCanConfigurePaidArticles': '仅管理员可配置付费文章',
  'errors.onlyAdminsCanManageTheIpDatabase': '仅管理员可管理 IP 数据库',
  'errors.onlyAdminsCanManageUserFeatureRestrictions': '仅管理员可管理用户功能限制',
  'errors.onlyAdminsCanManageUserSecuritySettings': '仅管理员可管理用户安全设置',
  'errors.onlyAdminsCanModifyErrorPages': '仅管理员可修改错误页',
  'errors.onlyAdminsCanResetErrorPages': '仅管理员可重置错误页',
  'errors.onlyAdminsCanScanForDatabaseCleanupItems': '仅管理员可扫描数据库清理项',
  'errors.onlyAdminsCanSendNotifications': '仅管理员可发送通知',
  'errors.onlyAdminsCanTestTheGeeIdApi': '仅管理员可测试 Gee ID 接口',
  'errors.onlyAdminsSuperModeratorsAndContentModeratorsCan': '仅管理员、总版主与内容版主可操作',
  'errors.onlyAdminsSuperModeratorsAndContentModeratorsCan2': '仅管理员、总版主和内容版主可操作该内容配置',
  'errors.onlyApplicationsUnderReviewCanBeWithdrawn': '只有审核中的申请可以撤回',
  'errors.onlyBilibiliTencentVideoOrDouyinLinksAreSupporte': '仅支持 Bilibili、腾讯视频或抖音链接',
  'errors.onlyHttpHttpsLinksAreSupported': '只支持 http/https 链接',
  'errors.onlyPersonalResourcesAndPostsCanBeTransferredToA': '当前仅支持将个人资源和帖子转移到工作室',
  'errors.onlyPublicPostsCanBecomePaidArticles': '仅公开帖子可设为付费文章',
  'errors.onlySiteAdminsCanManageAiSkillsAndRequestLogs': '仅站点管理员可管理 AI Skills 和请求记录',
  'errors.onlyTheAskerCanAcceptAnAnswer': '只有提问者可以采纳答案',
  'errors.onlyTheEventsBoardCanFillInEventInformation': '只有活动板块可以填写活动信息',
  'errors.onlyTheGroupOwnerCanDeleteTheChatRoom': '只有群主可以删除聊天室',
  'errors.onlyTheGroupOwnerCanSetGroupAdmins': '只有群主可以设置群管理',
  'errors.onlyTheOrganizationOwnerCanArchiveTheOrganizatio': '只有组织所有者可以归档组织',
  'errors.onlyTheOrganizationOwnerCanChangePermissionGroup': '只有组织所有者可以修改权限组',
  'errors.onlyTheOrganizationOwnerCanDeleteTheOrganization': '只有组织所有者可以删除组织',
  'errors.onlyTheOwnerCanAddAdmins': '只有所有者可以添加管理员',
  'errors.onlyTheOwnerCanChangeAdministratorRoles': '只有所有者可以调整管理员角色',
  'errors.onlyTheOwnerCanPromoteAMemberToAdministrator': '只有所有者可以提升成员为管理员',
  'errors.onlyTheOwnerCanRemoveAdministrators': '只有所有者可以移除管理员',
  'errors.onlyTheStudioLeaderCanApplyToCreateAnOrganizatio': '只有室长可以申请创建组织群聊',
  'errors.onlyTxtFilesCanBeUploaded': '仅支持上传 txt 文件',
  'errors.openSourceResourcesMustHaveALicenseSelected': '开源资源必须选择许可证',
  'errors.operationFailed': '操作失败',
  'errors.organizationNotFound': '组织不存在',
  'errors.organizationPathCannotBeEmpty': '组织路径不能为空',
  'errors.organizationVerificationAuthorizationNotFound': '组织认证授权不存在',
  'errors.organizationsCanOnlyBeJoinedAfterTheirReviewIsAp': '组织审核通过后才能加入',
  'errors.paidResourcesMustUseAValidExternalDownloadLink': '付费资源必须使用有效的外部下载链接',
  'errors.paidResourcesOnlySupportDownloadsViaExternalLink': '付费资源仅支持外部链接下载',
  'errors.parentCategoryNotFound': '父分类不存在',
  'errors.passkeyLoginFailed': '通行密钥登录失败',
  'errors.passkeyVerificationFailed': '通行密钥验证失败',
  'errors.passkeysAreNotEnabled': '通行密钥功能未启用',
  'errors.passwordResetEmailsAreNotEnabledContactTheAdmini': '密码重置邮件功能未启用，请联系管理员',
  'errors.patternIsRequired': 'pattern 必填',
  'errors.personalApiTokenManagementActionsMustBeConfirmed': '个人 API Token 管理操作必须在站内登录后完成确认',
  'errors.personalApiTokensCanOnlyDeleteTheirOwnResources': '个人 API Token 只能删除自己的资源',
  'errors.personalApiTokensCanOnlyEditTheirOwnPosts': '个人 API Token 只能编辑自己的帖子',
  'errors.personalApiTokensCanOnlyEditTheirOwnServerFinder': '个人 API Token 只能编辑自己的找服玩投稿',
  'errors.personalApiTokensCanOnlyEditYourOwnResources': '个人 API Token 只能编辑自己的资源',
  'errors.personalApiTokensCanOnlyEditYourOwnVideoSubmissi': '个人 API Token 只能编辑自己的视频投稿',
  'errors.personalApiTokensCanOnlyReadEditDataForTheirOwnP': '个人 API Token 只能读取自己的帖子编辑数据',
  'errors.personalApiTokensCanOnlyReadTheirOwnResourceEdit': '个人 API Token 只能读取自己的资源编辑数据',
  'errors.personalApiTokensCanOnlyReadTheirOwnVideoEditDat': '个人 API Token 只能读取自己的视频编辑数据',
  'errors.personalApiTokensCanOnlyReadYourOwnServerFinderE': '个人 API Token 只能读取自己的找服玩编辑数据',
  'errors.personalApiTokensCanOnlyReleaseNewVersionsOfYour': '个人 API Token 只能为自己的资源发布新版本',
  'errors.personalApiTokensCannotCurrentlyDeleteOrganizati': '个人 API Token 暂不支持删除组织身份投稿',
  'errors.personalApiTokensCannotPostOnBehalfOfAnOrganizat': '个人 API Token 暂不支持组织身份投稿',
  'errors.phoneNumberBindingForRegistrationIsNotEnabled': '当前未启用注册手机号绑定',
  'errors.platformIdentifierAlreadyExists': '平台标识已存在',
  'errors.platformNameCannotBeEmpty': '平台名称不能为空',
  'errors.pleaseCompleteMinecraftPremiumVerificationFirst': '请先完成 Minecraft 正版验证',
  'errors.pleaseCompleteTheCaptchaFirst': '请先完成人机验证',
  'errors.pleaseCompleteTheHumanVerification': '请完成人机验证',
  'errors.pleaseEnterANewEmail': '请输入新邮箱',
  'errors.pleaseEnterARegularExpression': '请输入正则表达式',
  'errors.pleaseEnterAUsername': '请输入用户名',
  'errors.pleaseEnterAValidEmailAddress': '请输入有效的邮箱地址',
  'errors.pleaseEnterAValidMakeupCheckInDate': '请填写有效的补签日期',
  'errors.pleaseEnterAValidPhoneNumber': '请输入有效的手机号',
  'errors.pleaseEnterAValidSkillMdUrl': '请输入有效的 SKILL.md 地址',
  'errors.pleaseEnterAnEmailAddress': '请输入邮箱地址',
  'errors.pleaseEnterAnEmailOrUsername': '请输入邮箱或用户名',
  'errors.pleaseEnterTheNotificationTitle': '请填写通知标题',
  'errors.pleaseEnterThePointsName': '请填写积分名称',
  'errors.pleaseEnterTheQuestion': '请输入问题',
  'errors.pleaseEnterTheRealSecretKeyMaskedPlaceholdersAre': '请填写真实 Secret Key，不能使用掩码占位符',
  'errors.pleaseEnterTheReferralCode': '请输入推广码',
  'errors.pleaseEnterTheRewriteRequestFirst': '请先输入改写要求',
  'errors.pleaseEnterTheUpdateDetails': '请填写更新内容',
  'errors.pleaseEnterYourCurrentCodeOrABackupCodeBeforeReB': '重新绑定 2FA 前请输入当前验证码或备用码',
  'errors.pleaseEnterYourEmail': '请输入邮箱',
  'errors.pleaseFillInAValidTestEmail': '请填写有效的测试邮箱',
  'errors.pleaseFillInAValidTestPhoneNumberInternationalDi': '请填写有效的测试手机号，支持国际区号',
  'errors.pleaseFillInAccount': '请填写 account',
  'errors.pleaseFillInTheEmailSubjectAndBody': '请填写邮件主题和内容',
  'errors.pleaseFillInTheEventStartTime': '请填写活动开始时间',
  'errors.pleaseFillInTheIdentifierAndName': '请填写标识和名称',
  'errors.pleaseFillInTheIpToLookUp': '请填写要查询的 IP',
  'errors.pleaseFillInTheItemIdentifierNameImplementationT': '请填写道具标识、名称、实现类型和售价积分体系',
  'errors.pleaseFillInTheItemNameImplementationTypeAndPric': '请填写道具名称、实现类型和售价积分体系',
  'errors.pleaseFillInTheLogTitle': '请填写日志标题',
  'errors.pleaseFillInThePointsIdentifierAndName': '请填写积分标识和名称',
  'errors.pleaseFillInTheRecipientEmail': '请填写收件人邮箱',
  'errors.pleaseFillInTheRequiredFields': '请填写必要字段',
  'errors.pleaseFillInTheSpecifiedUser': '请填写指定用户',
  'errors.pleaseFillInTheTitleAndContent': '请填写标题和内容',
  'errors.pleaseLogInFirst': '请先登录',
  'errors.pleaseProvideAtLeastOneUser': '请至少提供一个用户',
  'errors.pleaseProvideTheCompensationReason': '请填写补偿原因',
  'errors.pleaseRateTheResourceFirst': '请先完成资源评分',
  'errors.pleaseRateTheServerFinderEntryFirst': '请先完成找服玩评分',
  'errors.pleaseReadAndAcceptThePaidArticlePricingTermsAnd': '请先阅读并同意付费文章收费标准与发布协议',
  'errors.pleaseSelectABoard': '请选择板块',
  'errors.pleaseSelectACategory': '请选择分类',
  'errors.pleaseSelectACompensationTarget': '请选择补偿对象',
  'errors.pleaseSelectALevelUsergroup': '请选择等级用户组',
  'errors.pleaseSelectANewOrganizationOwner': '请选择新的组织所有者',
  'errors.pleaseSelectANewResourceOwner': '请选择新的资源所有者',
  'errors.pleaseSelectAPublicAndAvailableResourceOrServerF': '请选择一个公开且可用的资源或找服玩',
  'errors.pleaseSelectAPublicOrNonPublicStatus': '请选择公开或未公开状态',
  'errors.pleaseSelectASendTarget': '请选择发送目标',
  'errors.pleaseSelectATargetStudio': '请选择目标工作室',
  'errors.pleaseSelectAUser': '请选择用户',
  'errors.pleaseSelectAUserPermissionGroup': '请选择用户权限组',
  'errors.pleaseSelectAVerificationCategory': '请选择认证分类',
  'errors.pleaseSelectAnOrganization': '请选择组织',
  'errors.pleaseSelectAtLeastOneCleanupItem': '请选择至少一个清理项',
  'errors.pleaseSelectAtLeastOneCompensationItem': '请至少选择一种补偿内容',
  'errors.pleaseSelectAtLeastOneNetworkEnvironment': '请至少选择一个网络环境',
  'errors.pleaseSelectAtLeastOnePollOption': '请至少选择一个投票选项',
  'errors.pleaseSelectAtLeastOneQuestionBankSource': '请至少选择一个题库来源',
  'errors.pleaseSelectAtLeastOneSupportedMcVersion': '请至少选择一个支持的 MC 版本',
  'errors.pleaseSelectAtLeastOneUser': '请选择至少一个用户',
  'errors.pleaseSelectTheAccountTypeToVerify': '请选择要认证的账号类型',
  'errors.pleaseSelectTheContentToInclude': '请选择要收录的内容',
  'errors.pleaseSelectTheContentToProcessInBatch': '请选择要批量处理的内容',
  'errors.pleaseSelectTheOrganizationToVerify': '请选择要认证的组织',
  'errors.pleaseSelectTheTutorialPostAndIndexTarget': '请选择教程帖子和索引目标',
  'errors.pleaseSelectTheUserToAddToTheBlacklist': '请选择要加入黑名单的用户',
  'errors.pleaseSelectTheUserToAddToTheOrganization': '请选择要加入组织的用户',
  'errors.pleaseSelectTheUserToRemoveFromTheBlacklist': '请选择要移出黑名单的用户',
  'errors.pleaseSelectWhetherToEnablePremiumVerification': '请选择是否开启正版验证',
  'errors.pleaseSetAPasswordOrAddAPasskey': '请设置密码或添加通行密钥',
  'errors.pleaseSpecifyTheRecipient': '请指定接收用户',
  'errors.pleaseUploadATxtFile': '请上传 txt 文件',
  'errors.pleaseUseTheThirdPartyIdentityOriginallyBoundToT': '请使用此账号原来绑定的第三方身份验证',
  'errors.pleaseVerifyAnExistingLoginMethodToContinue': '请验证已有登录方式后继续',
  'errors.pleaseVerifyYourCurrentEmailFirst': '请先验证当前邮箱',
  'errors.pointsChangesMustBeGreaterThan0': '积分变动必须大于 0',
  'errors.pointsIdentifierAlreadyExists': '积分标识已存在',
  'errors.pointsSystemNotFound': '积分体系不存在',
  'errors.pointsUnavailable': '积分不可用',
  'errors.postNotFound': '帖子不存在',
  'errors.postsInTheEventsBoardRequireAnEventStartTime': '活动板块的帖子需要填写活动开始时间',
  'errors.publishingAnEventPostRequiresAnEventStartTime': '发布活动帖需要填写活动开始时间',
  'errors.pushRecordNotFound': '推送记录不存在',
  'errors.questionBankKeyAndTitleCannotBeEmpty': '题库 key 和标题不能为空',
  'errors.questionNotFound': '题目不存在',
  'errors.ratingChangesAreOnCooldownWait24HoursBeforeChang': '评分修改冷却中，请满 24 小时后再修改评分',
  'errors.ratingsAreDisabledForUnpublishedResources': '未公开资源已关闭评分',
  'errors.ratingsAreNotEnabledYet': '评分功能暂未开启',
  'errors.rebindingEmailsAreNotEnabledPleaseContactAnAdmin': '邮箱换绑邮件功能未启用，请联系管理员',
  'errors.recalculationFailed': '重新计算失败',
  'errors.redirectLinksOnlySupportHttpSOrInSitePaths': '跳转链接仅支持 http(s) 或站内路径',
  'errors.referencedDocumentsMustComeFromTheDocumentCollec': '引用文档必须来自“文档收集”板块，且帖子需公开、已审核、无访问限制',
  'errors.referralCodeNotFoundOrUnavailable': '推广码不存在或不可用',
  'errors.registeringInYourRegionRequiresAReferralCode': '当前访问地区注册需要填写推广码',
  'errors.registrationFailedPleaseTryAgainLater': '注册失败，请稍后重试',
  'errors.registrationHasExpiredPleaseTryAgain': '注册已过期，请重试',
  'errors.registrationIsClosed': '注册已关闭',
  'errors.regularExpressionIsTooLong': '正则表达式过长',
  'errors.remoteContentIsTooLarge': '远端内容过大',
  'errors.replyContentCannotBeEmpty': '回复内容不能为空',
  'errors.replyIsTooLong': '回复内容过长',
  'errors.replyNotFound': '回复不存在',
  'errors.replyTargetNotFound': '回复目标不存在',
  'errors.reportNotFound': '举报不存在',
  'errors.requestIdCannotBeEmpty': 'request_id 不能为空',
  'errors.resetFailedPleaseTryAgainLater': '重置失败，请稍后重试',
  'errors.resourceNotFound': '资源不存在',
  'errors.reviewContentCannotBePublishedAsACommentReply': '评价内容不能作为评论回复发布',
  'errors.ruleNotFound': '规则不存在',
  'errors.rulesMustBeAnArray': 'rules 必须是数组',
  'errors.scanFailed': '扫描失败',
  'errors.selectAtLeastOnePermissionScope': '至少选择一个权限范围',
  'errors.serverAddressCannotBeEmpty': '服务器地址不能为空',
  'errors.serverFinderEntryNotFound': '找服玩不存在',
  'errors.serverNotFound': '服务器不存在',
  'errors.serverPortCannotBeEmpty': '服务器端口不能为空',
  'errors.sessionExpired': '会话已失效',
  'errors.sessionNotFound': '会话不存在',
  'errors.setAnAccountPasswordBeforeEnablingTheTwoLayerPas': '请先设置账号密码后再启用双层密码',
  'errors.setAnEnglishUsernameInYourProfileBeforeEnablingG': '请先在个人资料中设置英文用户名，再开通 Gee ID',
  'errors.setUpTwoStepVerificationFirst': '请先完成二步验证设置',
  'errors.settingDoesNotBelongTo': '设置项不属于 ',
  'errors.shortcodeAlreadyExists': '短代码已存在',
  'errors.siteApiCatalogNotFound': '站点 API 目录不存在',
  'errors.siteApiPresetNotFound': '站点 API 预设不存在',
  'errors.siteApiTokenApplicationNotFound': '站点 API Token 申请不存在',
  'errors.siteConfigurationIsTemporarilyUnavailable': '站点配置暂时不可用',
  'errors.skillDescriptionCannotExceed600Characters': 'Skill 描述不能超过 600 字',
  'errors.skillDownloadFailed': 'Skill 下载失败 (',
  'errors.skillDownloadRedirectsMustStayOnHttps': 'Skill 下载重定向必须保持 HTTPS',
  'errors.skillIdentifierAlreadyExists': 'Skill 标识已存在',
  'errors.skillIdentifiersMayOnlyContainLowercaseLettersDi': 'Skill 标识只能使用小写字母、数字和连字符，长度不超过 64',
  'errors.skillInstructionsCannotBeEmptyAndMustNotExceed30': 'Skill 指令不能为空且长度不能超过 30000 字',
  'errors.skillMdFilesCannotExceed128Kb': 'SKILL.md 文件不能超过 128 KB',
  'errors.skillNameCannotBeEmptyAndMustNotExceed80Characte': 'Skill 名称不能为空且长度不能超过 80',
  'errors.slugAlreadyExists': 'slug 已存在',
  'errors.someContentDoesNotExistOrHasBeenDeletedRefreshAn': '部分内容不存在或已被删除，请刷新后重试',
  'errors.someContentStatusesHaveChangedRefreshAndTryAgain': '部分内容状态已变化，请刷新后重试',
  'errors.someResourcesDoNotExist': '部分资源不存在',
  'errors.sortDataCannotBeEmpty': '排序数据不能为空',
  'errors.syncingTooFrequentlyPleaseTryAgainLater': '同步太频繁，请稍后再试',
  'errors.systemIssuedBadgesCannotBeDeleted': '系统自动发放徽章不支持删除',
  'errors.tagGroupNameCannotBeEmpty': '标签组名称不能为空',
  'errors.tagGroupNotFound': '标签组不存在',
  'errors.tagGroupOrTagSlugAlreadyExists': '标签组或标签 slug 已存在',
  'errors.tagNameCannotBeEmpty': '标签名不能为空',
  'errors.tagNameOrSlugAlreadyExists': '标签名或 Slug 已存在',
  'errors.tagNotFound': '标签不存在',
  'errors.targetIsNotAFile': '目标不是文件',
  'errors.targetReplyNotFound': '目标回复不存在',
  'errors.taskNotFoundOrItsCurrentStateCannotBeRetried': '任务不存在或当前状态不可重试',
  'errors.tencentCloudSesEndpointFormatIsInvalid': '腾讯云 SES 接口地址格式不正确',
  'errors.tencentCloudSesRefusedToSendThisRecipientAddress': '腾讯云 SES 拒绝发送：该收件地址在服务商黑名单中。允许注册邮箱后缀不会解除服务商黑名单。',
  'errors.tencentCloudSesRegionFormatIsInvalid': '腾讯云 SES 地域格式不正确',
  'errors.tencentCloudSesSecretidAndSecretkeyAreNotConfigu': '腾讯云 SES SecretId 和 SecretKey 未配置',
  'errors.testPasswordMustBeAtLeast6Characters': '测试密码至少 6 位',
  'errors.textIsRequired': 'text 必填',
  'errors.thatAddressReturnedAWebpageUseTheRawSkillMdFileU': '该地址返回了网页，请填写原始 SKILL.md 文件地址',
  'errors.theAccountBehindThisReferralCodeIsInAnAbnormalSt': '推广码所属账号状态异常，暂不可使用',
  'errors.theAccountBehindThisReferralCodeIsNotYetEligible': '推广码所属账号尚未获得推广资格',
  'errors.theAccountThatOwnsTheReferralCodeHasNotCompleted': '推广码所属账号尚未完成邮箱验证',
  'errors.theAiDidNotReturnValidJson': 'AI 未返回有效 JSON',
  'errors.theAiModelIsNotFullyConfiguredYet': 'AI 模型尚未配置完成',
  'errors.theApplicantIsNoLongerTheStudioLeaderOfThisOrgan': '申请人已不是该组织的室长，请拒绝此申请后由当前室长重新提交',
  'errors.theAuthorLinkMustBeAValidUrl': '作者链接必须是有效的网址',
  'errors.theAuthorizationRecordDoesNotExist': '授权记录不存在',
  'errors.theAuthorizationRequestHasExpiredPleaseStartTheL': '授权请求已失效，请重新发起登录',
  'errors.theAutomaticallyCreatedGeeIdAccountIsAlreadyBoun': '自动补建的 Gee ID 账号已绑定到其他站内账号，请联系管理员处理',
  'errors.theAvatarUrlMustBeAnUploadPathOnThisSite': '头像地址必须是本站上传路径',
  'errors.theBinFileInTheZipExceedsTheSizeLimit': 'ZIP 内 BIN 文件超过大小限制',
  'errors.theBingWebmasterApiKeyIsNotConfiguredOrCannotBeD': 'Bing Webmaster API Key 未配置或无法解密',
  'errors.theBingWebmasterSiteUrlMustBeAValidHttpSSiteRoot': 'Bing Webmaster 站点 URL 必须是有效的 HTTP(S) 站点根地址',
  'errors.theBingWebmasterUrlSubmissionQuotaHasBeenUsedUp': 'Bing Webmaster 当前 URL 提交额度已用完',
  'errors.theCaptchaHasExpiredRefreshAndVerifyAgain': '人机验证已失效，请刷新后重新验证',
  'errors.theChangeValueMustBeANonZeroInteger': '变动值必须为非零整数',
  'errors.theChatRoomCreatorCannotBeRemoved': '不能移除聊天室创建者',
  'errors.theChatRoomDoesNotExist': '聊天室不存在',
  'errors.theChatRoomIsNotOpenYetJoinCodesCannotBeGenerate': '聊天室未开放，暂不能生成加入代码',
  'errors.theChatRoomIsNotOpenYetMembersCannotBeAdded': '聊天室未开放，暂不能添加成员',
  'errors.theChunkedUploadSessionDoesNotExistOrHasExpiredU': '分块上传会话不存在或已过期，请重新上传',
  'errors.theCoinAmountCanOnlyBe1Or2': '投币数量只能选择 1 或 2',
  'errors.theCollectedEntryDoesNotExist': '收录条目不存在',
  'errors.theConnectionApplicationEntryOnlySupportsHttpSLi': '连接申请入口只支持 http(s) 链接；QQ群号请填写“QQ群”字段',
  'errors.theCooldownHasChangedOrEndedRefreshAndTryAgain': '冷却状态已变更或结束，请刷新后重试',
  'errors.theCorrespondingVerificationTypeDoesNotExistOrIs': '对应认证类型不存在或已停用，无法通过申请',
  'errors.theCorrespondingVerificationTypeIsNotEnabled': '对应认证类型当前未启用',
  'errors.theCoverImageOnlySupportsHttpSOrOnSitePathsAndMu': '封面图仅支持 http(s) 或站内路径，并需为 png/jpg/webp/gif/avif 格式',
  'errors.theCurrentApiTokenLacksPermissionForThisOperatio': '当前 API Token 没有此操作权限',
  'errors.theCurrentSiteApiKeyLacksPermissionForThisEndpoi': '当前站点 API 密钥没有此接口权限',
  'errors.theCurrentTwoLayerPasswordIsIncorrect': '当前双层密码不正确',
  'errors.theCurrentUserDoesNotHoldADelegableModeratorRole': '当前用户不是可分权版主角色',
  'errors.theDatabaseFileDoesNotExist': '数据库文件不存在',
  'errors.theDatabaseFileExceedsTheSizeLimit': '数据库文件超过大小限制',
  'errors.theDatabaseFileIsTooSmallOrEmpty': '数据库文件过小或为空',
  'errors.theDevelopmentLogDoesNotExist': '开发日志不存在',
  'errors.theDirectUploadFileDoesNotExistOrTheUploadUrlHas': '直传文件不存在或上传地址已失效',
  'errors.theDisableApplicationActionIsNotSupportedForThis': '当前举报对象不支持停用应用操作',
  'errors.theDocumentGroupDoesNotExist': '文档组不存在',
  'errors.theDownloadUrlIsNotAllowed': '下载地址不在允许范围内',
  'errors.theDownloadedFileExceedsTheSizeLimit': '下载文件超过大小限制',
  'errors.theEmailTemplateDoesNotExistOrIsNotAnEmailTempla': '邮件模板不存在或不是邮件模板',
  'errors.theEndTimeCannotBeEarlierThanTheStartTime': '活动结束时间不能早于开始时间',
  'errors.theExamDoesNotExist': '考试不存在',
  'errors.theExamIsNotLinkedToAQuestionBankYet': '考试尚未绑定题库',
  'errors.theExamRecordDoesNotExistOrHasAlreadyBeenSubmitt': '考试记录不存在或已提交',
  'errors.theExamTimedOutAndCannotBeSubmittedForGrading': '考试已超时，无法提交评分',
  'errors.theExpirationTimeMustBeLaterThanTheEffectiveTime': '失效时间必须晚于生效时间',
  'errors.theExternalDownloadUrlMustBeAValidHttpHttpsLink': '外链下载地址必须为有效的 http/https 链接',
  'errors.theFileContainsNoSensitiveWordsToImport': '文件中没有可导入的敏感词',
  'errors.theFileContentDoesNotMatchItsExtensionUploadReje': '文件内容与扩展名不匹配，上传被拒绝',
  'errors.theFileIsStillBeingProcessedAndCannotBeCanceledY': '文件正在完成处理中，暂时不能取消',
  'errors.theGeeIdBindphoneDirectApiKeyIsNotConfigured': 'Gee ID bindphone_direct API Key 未配置',
  'errors.theGeeIdExternalApiIsNotEnabled': 'Gee ID 外接 API 未启用',
  'errors.theGeeIdOauthAppClientIdDoesNotMatchTheSiteConfi': 'Gee ID OAuth 应用 client_id 与站点配置不一致，无法自动绑定',
  'errors.theGeeIdOauthAuthorizeApiKeyIsNotConfigured': 'Gee ID oauth_authorize API Key 未配置',
  'errors.theGeeIdOauthTokenResponseIsMissingAccessToken': 'Gee ID OAuth token 返回缺少 access_token',
  'errors.theGeeIdRegisterDirectApiKeyIsNotConfigured': 'Gee ID register_direct API Key 未配置',
  'errors.theGeeIdUserQueryReturnedNoUserInfo': 'Gee ID 用户查询未返回用户信息',
  'errors.theGlossaryGroupDoesNotExist': '词库组不存在',
  'errors.theGrantMethodOfSystemIssuedBadgesCannotBeChange': '系统自动发放徽章的授予方式不可改为其他类型',
  'errors.theGroupOwnerCannotRemoveThemselves': '群主不能移除自己',
  'errors.theHumanVerificationServiceIsUnavailable': '人机验证服务不可用',
  'errors.theIdentifierAlreadyExistsWithinTheSameCategory': '同一分类范围内的标识已存在',
  'errors.theImageContentDoesNotMatchItsExtensionUploadRej': '图片内容与扩展名不匹配，上传被拒绝',
  'errors.theIp2locationZipTargetFilenameMustBeBin': 'IP2Location ZIP 目标文件名必须是 .BIN',
  'errors.theLastVersionCannotBeDeleted': '不能删除最后一个版本',
  'errors.theLimitMustBeBetween1And3650DaysOrSetToPermanen': '限制天数必须在 1 到 3650 天之间，或设置为永久',
  'errors.theLinkHasExpiredOrHasAlreadyBeenUsed': '链接已失效或已被使用',
  'errors.theLinkMustBeHttpOrHttps': '链接必须为 http/https',
  'errors.theLinkedResourceReviewDoesNotExistOrYouCannotEd': '关联的资源评价内容不存在或无权修改',
  'errors.theLinkedServerFinderReviewDoesNotExistOrYouCann': '关联的找服玩评价内容不存在或无权修改',
  'errors.theMessageDoesNotExistOrYouCannotEditIt': '消息不存在或无权编辑',
  'errors.theMicrosoftAccountCannotBeExchangedForXboxLiveC': 'Microsoft 账号无法换取 Xbox Live 凭据',
  'errors.theMinecraftAuthorizationHasExpiredReVerifyYourP': 'Minecraft 授权已过期，请重新验证正版后再同步披风',
  'errors.theNewEmailCannotBeTheSameAsTheCurrentEmail': '新邮箱不能与当前邮箱相同',
  'errors.theNewSlugIsTheSameAsTheCurrentOne': '新 Slug 与当前相同',
  'errors.theNewUsernameIsTheSameAsTheCurrentOne': '新用户名与当前相同',
  'errors.theOauthAppDoesNotExist': 'OAuth 应用不存在',
  'errors.theOauthTokenAndTheSiteApiKeyDoNotBelongToTheSam': 'OAuth Token 与站点 API 密钥不属于同一应用',
  'errors.theOauthTokenLacksPermissionForThisEndpoint': 'OAuth Token 没有此接口权限',
  'errors.theOperationsNoticeDoesNotExist': '运营通知不存在',
  'errors.theOrganizationDoesNotExistOrYouDoNotHaveAccess': '组织不存在或你没有访问权限',
  'errors.theOrganizationMemberDoesNotExist': '组织成员不存在',
  'errors.theOrganizationOwnerCannotBeChangedDirectlyUseTr': '不能直接修改组织所有者，请使用转移所有者',
  'errors.theOrganizationOwnerCannotBeRemoved': '不能移除组织所有者',
  'errors.theOrganizationOwnerCannotBeRemovedTransferOwner': '不能移除组织所有者，请先转移所有者',
  'errors.theOrganizationPathMustBeAtLeast2Characters': '组织路径至少需要 2 个字符',
  'errors.theOrganizationVerificationApplicationIsMissingT': '组织认证申请缺少目标组织',
  'errors.theOwnerRoleCannotBeModified': '不能修改所有者角色',
  'errors.thePaidArticleDoesNotExistOrIsNotPurchasableYet': '付费文章不存在或暂不可购买',
  'errors.theParentCommentDoesNotBelongToThisResource': '父级评论不属于当前资源',
  'errors.theParentCommentDoesNotBelongToThisServer': '父级评论不属于当前服务器',
  'errors.theParentReplyDoesNotBelongToThisPost': '父级回复不属于当前帖子',
  'errors.theParentReplyDoesNotBelongToThisVideo': '父级回复不属于当前视频',
  'errors.theParentReplyDoesNotExist': '父级回复不存在',
  'errors.theParentReplyIsInvalid': '父级回复无效',
  'errors.thePasskeyDoesNotExist': '通行密钥不存在',
  'errors.thePathCanOnlyContainLowercaseLettersNumbersAndH': '路径只能包含小写字母、数字和连字符',
  'errors.thePendingItemHasChangedRefreshAndTryAgain': '待审项已变更，请刷新后重试',
  'errors.thePendingOrganizationPathIsAlreadyTakenByAnothe': '待应用的组织路径已被其他组织占用，请驳回后让用户重新提交',
  'errors.thePendingUsernameHasAnInvalidLengthRejectItAndA': '待审用户名长度无效，请驳回后让用户重新提交',
  'errors.thePendingUsernameOrEnglishNameIsAlreadyTakenByA': '待应用的用户名或英文名已被其他账号占用，请驳回后让用户重新提交',
  'errors.thePhoneNumberBoundToGeeIdIsAlreadyTakenByAnothe': 'Gee ID 已绑定的手机号已被其他站内账号占用，请联系管理员处理',
  'errors.thePlatformIdentifierMayOnlyContainLowercaseLett': '平台标识只能使用小写字母、数字和短横线，长度 1-50 位',
  'errors.thePointTypeDoesNotExist': '积分不存在',
  'errors.thePointsSystemForThisItemIsUnavailable': '当前道具的积分体系不可用',
  'errors.thePollConfigurationOrPermissionsHaveChangedRefr': '投票配置或权限已变化，请刷新后重试',
  'errors.thePollRewardBudgetIsInsufficientAndCannotBePaid': '投票奖励预算不足，无法发放',
  'errors.thePriceOfAPaidArticleMustBeAPositiveIntegerInCe': '付费文章价格必须为大于 0 的分单位整数',
  'errors.theQuestionBankDoesNotExist': '题库不存在',
  'errors.theRatingMustBeBetween1And5Stars': '评分必须在 1 到 5 星之间',
  'errors.theRegistrationSessionHasExpired': '注册会话已过期',
  'errors.theRegistrationSessionHasExpiredVerifyYourEmailA': '注册会话已过期，请重新验证邮箱',
  'errors.theRemoteFileExceedsTheSizeLimit': '远程文件超过大小限制',
  'errors.theReplyTargetDoesNotBelongToThisPost': '回复目标不属于当前帖子',
  'errors.theReportHasChangedRefreshAndTryAgain': '举报已变更，请刷新后重试',
  'errors.theReportedCommentDoesNotExist': '被举报的评论不存在',
  'errors.theReportedOauthAppDoesNotExist': '被举报的 OAuth 应用不存在',
  'errors.theReportedOrganizationDoesNotExist': '被举报的组织不存在',
  'errors.theReportedPostDoesNotExist': '被举报的帖子不存在',
  'errors.theReportedReplyDoesNotExist': '被举报的回复不存在',
  'errors.theReportedResourceDoesNotExist': '被举报的资源不存在',
  'errors.theReportedServerDoesNotExist': '被举报的服务器不存在',
  'errors.theReportedTargetCannotBeLinkedToAnActionableUse': '当前举报对象无法关联到可处理用户',
  'errors.theReportedTargetDoesNotExist': '被举报对象不存在',
  'errors.theReportedTargetIsNotAnActionableUser': '当前举报对象不是可处理用户',
  'errors.theReportedUserDoesNotExist': '被举报的用户不存在',
  'errors.theReportedVideoDoesNotExist': '被举报的视频不存在',
  'errors.theReportedVideoReplyDoesNotExist': '被举报的视频回复不存在',
  'errors.theSavePathMustBeInsideTheBackendWorkingDirector': '保存路径必须位于后端工作目录内',
  'errors.theSelectedLicenseDoesNotExistOrIsDisabled': '所选许可证不存在或已停用',
  'errors.theSelectedTopicDoesNotBelongToACategoryAllowedB': '所选话题不属于当前板块允许的分类',
  'errors.theSelectedVerificationCategoryIsInvalidOrDisabl': '所选认证分类无效或已停用',
  'errors.theSelectedVersionTagDoesNotExistOrIsDisabled': '所选版本标签不存在或已停用',
  'errors.theSettingsAuthorizationCannotBeUsedForThisOpera': '设置授权不能用于此操作',
  'errors.theSettingsWereUpdatedByAnotherOperationReloadAn': '设置已被其他操作更新，请重新读取并合并修改后再保存',
  'errors.theSetupAuthorizationHasExpiredPleaseLogInAgain': '设置授权已过期，请重新登录',
  'errors.theSiteApiKeyDoesNotExist': '站点 API Key 不存在',
  'errors.theSiteApiKeyIsNotBoundToAnOauthApp': '站点 API 密钥未绑定 OAuth 应用',
  'errors.theSiteHasNotEnabledTheReferralCodeFeatureYet': '站点暂未开启推广码功能',
  'errors.theSiteUrlAndApiKeyMustBeFilledInBeforeEnablingB': '启用 Bing Webmaster 前必须填写站点 URL 和 API Key',
  'errors.theSpecifiedAdminUserDoesNotExistOrIsABotIdentit': '指定管理用户不存在或属于机器人身份',
  'errors.theStudioLeaderCannotLeaveTheOrganizationDirectl': '室长不能直接退出组织，请先转移组织所有权或删除组织',
  'errors.theTargetLinkIsNotASupportedImageResource': '目标链接不是受支持的图片资源',
  'errors.theTargetLinkIsNotAnHtmlPage': '目标链接不是 HTML 页面',
  'errors.theTargetLinkIsNotAnImageResource': '目标链接不是图片资源',
  'errors.theTargetStudioIsUnavailableOrHasNotBeenApproved': '目标工作室不可用或尚未通过审核',
  'errors.theTargetUserDoesNotExist': '目标用户不存在',
  'errors.theTargetVideoSectionIsNotWithinYourManagementSc': '目标视频分区不在你的管理范围内',
  'errors.theTaskDoesNotExistOrCannotBeCancelledInItsCurre': '任务不存在或当前状态不可取消',
  'errors.theTencentCloudSesEndpointMustUseHttps': '腾讯云 SES 接口地址必须使用 HTTPS',
  'errors.theTencentCloudSesRegionIsNotConfigured': '腾讯云 SES 地域未配置',
  'errors.theThirdPartyRegistrationSessionHasExpired': '第三方注册会话已过期',
  'errors.theThirdPartyRegistrationSessionHasExpiredStartT': '第三方注册会话已失效，请重新发起注册',
  'errors.theTopicCategoryGroupDoesNotExist': '话题分类组不存在',
  'errors.theTutorialPostDoesNotExistOrCannotBeIndexed': '教程帖子不存在或不可索引',
  'errors.theTwoLayerPasswordIsIncorrect': '双层密码不正确',
  'errors.theTwoLayerPasswordMustBeAtLeast6Characters': '双层密码长度不能少于6位',
  'errors.theTwoLayerPasswordMustBeBetween6And128Character': '双层密码长度需在 6 到 128 位之间',
  'errors.theUploadSessionHasEnteredFinalizationNoMoreChun': '上传会话已进入完成处理，不能继续上传分块',
  'errors.theUploadedFileExceedsTheSizeLimit': '上传文件超过大小限制',
  'errors.theUsernameCannotBeOnlySpaces': '用户名不能为纯空格',
  'errors.theUsernameEnglishUsernameEmailOrPhoneNumberIsAl': '用户名、英文用户名、邮箱或手机号已被注册',
  'errors.theUsernameMustBeAtLeast2Characters': '用户名至少 2 个字符',
  'errors.theVerificationCodeMustBe6Digits': '验证码必须是 6 位数字',
  'errors.theVerificationLinkHasExpiredOrHasAlreadyBeenUse': '验证链接已失效或已被使用',
  'errors.theVerificationStatusHasExpiredLogInAgainWithYou': '验证状态已过期，请重新使用第三方账号登录',
  'errors.theWebsocketAppDoesNotExist': 'WebSocket 应用不存在',
  'errors.thereAreInvalidPollOptions': '存在无效的投票选项',
  'errors.thereAreNoFieldsToUpdate': '没有可更新的字段',
  'errors.thereIsAnInvalidQuestionBankSource': '存在无效的题库来源',
  'errors.thereIsNoPreviousVersionToRollBackTo': '没有可回滚的上一版本',
  'errors.thereIsNoTextToProcess': '当前没有可处理的文本',
  'errors.thisAccountDoesNotHaveAUsablePasskeyBound': '当前账号未绑定可用的通行密钥',
  'errors.thisAccountHasNoEmailAvailableForVerification': '当前账号没有可用于验证的邮箱',
  'errors.thisAccountHasNoGeeIdAccountYetAndAutomaticCreat': '当前账号尚未建立 Gee ID 账号，站点也未启用自动补建，请先绑定 GeeID OAuth 或联系管理员',
  'errors.thisAccountHasNoPasswordSetLogInWithEmailVerific': '该账号未设置密码，请使用邮箱验证、通行密钥或第三方账号登录',
  'errors.thisAccountHasNoPasswordSetSetOneOnTheSettingsPa': '该账号未设置密码，请前往设置页面设置密码',
  'errors.thisAccountHasNotSetATwoLayerPassword': '当前账号未设置双层密码',
  'errors.thisAccountIsNotPermittedToPublishPaidArticles': '当前账号未获得付费文章发布权限',
  'errors.thisActionRequiresCompletingSecurityVerification': '当前操作需要重新完成安全验证',
  'errors.thisAiFeatureIsNotEnabledYet': '该 AI 功能尚未启用',
  'errors.thisApiOnlySupportsTwoSidedDeletionWithAnExplici': '当前接口仅支持显式 scope=global 的双方删除，前端“仅自己可见删除”请使用本地隐藏逻辑',
  'errors.thisApplicationHasAlreadyBeenProcessedAndCannotB': '该申请已处理，不能重复审核',
  'errors.thisApplicationHasAlreadyBeenReviewed': '该申请已审核',
  'errors.thisCategoryDoesNotAllowPublishingPaidResources': '当前分类不允许发布付费资源',
  'errors.thisCategoryHasExistingApplicationRecordsDisable': '该分类已有申请记录，请停用而不是删除',
  'errors.thisChatRoomApplicationHasAlreadyBeenProcessed': '该聊天室申请已处理',
  'errors.thisCommentWasAlreadyHandledByAnotherReviewFlowR': '该评论已由其他审核流程处理，请刷新审核队列',
  'errors.thisContentIsAlreadyInThisListing': '该内容已经在这个收录中',
  'errors.thisContentIsNotInABranchYouModerate': '当前内容不在你的管辖分支内',
  'errors.thisContentIsNotInASectionYouManage': '当前内容不在你的管辖分区内',
  'errors.thisContentIsNotInASectionYouModerate': '当前内容不在你的管辖板块内',
  'errors.thisDirectUploadObjectDoesNotBelongToTheCurrentS': '该直传对象不属于当前会话，无法确认',
  'errors.thisEmailIsAlreadyRegistered': '该邮箱已被注册',
  'errors.thisEmailIsAlreadyUsedByAnotherAccount': '该邮箱已被其他账号使用',
  'errors.thisEmailIsAlreadyVerified': '该邮箱已经验证',
  'errors.thisEndpointDoesNotAcceptPersonalApiTokensUseYou': '当前接口不允许使用个人 API Token，请使用站内登录会话',
  'errors.thisEnglishUsernameIsAlreadyTaken': '该英文用户名已被使用',
  'errors.thisExamHasAlreadyBeenSubmitted': '该考试已提交',
  'errors.thisExamHasNoAvailableQuestionsConfigured': '该考试尚未配置可用题目',
  'errors.thisExamHasNoDefaultQuestionBankTemplateToImport': '当前考试没有可导入的默认题库模板',
  'errors.thisExamHasNoDefaultTemplateToPreview': '当前考试没有默认模板可预览',
  'errors.thisExamIsNotLinkedToAQuestionBankYet': '当前考试还没有绑定题库',
  'errors.thisExamIsNotLinkedToAQuestionBankYet2': '该考试尚未绑定题库',
  'errors.thisFeatureRestrictionDoesNotExist': '该功能限制不存在',
  'errors.thisItemTypeIsNotSupportedYet': '当前道具类型暂不支持使用',
  'errors.thisKeyIsNotGrantedPermissionForThisContentType': '当前密钥未授予该内容类型权限',
  'errors.thisMemberIsNotPendingApproval': '该成员不是待审批状态',
  'errors.thisMessageHasBeenRecalled': '该消息已撤回',
  'errors.thisOrganizationApplicationHasAlreadyBeenProcess': '该组织申请已处理',
  'errors.thisOrganizationCannotBeFollowedRightNow': '这个组织当前不可关注',
  'errors.thisOrganizationIsNotAcceptingNewMembersRightNow': '这个组织暂不开放加入',
  'errors.thisOrganizationIsNotOpenForPublicJoiningRightNo': '这个组织当前不开放公开加入',
  'errors.thisOrganizationOnlySupportsJoiningByInvitation': '这个组织仅支持邀请加入',
  'errors.thisOrganizationPathIsAlreadyTaken': '该组织路径已被使用',
  'errors.thisPathIsAlreadyTaken': '该路径已被使用',
  'errors.thisPathIsReservedByTheSystem': '该路径为系统保留路径',
  'errors.thisPendingItemHasAlreadyBeenProcessed': '该待审项已处理',
  'errors.thisPendingItemWasSupersededByANewerSubmissionAn': '该待审项已有更新提交覆盖，已自动移出队列，请刷新审核列表',
  'errors.thisPhoneNumberIsAlreadyBound': '该手机号已被绑定',
  'errors.thisPhoneNumberIsAlreadyBoundToAnotherAccount': '该手机号已被其他账号绑定',
  'errors.thisPollHasEnded': '该投票已经结束',
  'errors.thisPollHasEndedOrThePostDoesNotAcceptVotes': '该投票已结束或帖子不可投票',
  'errors.thisPollOnlySupportsSingleChoice': '当前投票仅支持单选',
  'errors.thisPostIsNotAPoll': '当前帖子不是投票帖',
  'errors.thisPostIsNotAQAPost': '当前帖子不是问答帖',
  'errors.thisPostIsNotInABoardYouModerate': '当前帖子不在你的管辖板块内',
  'errors.thisPostIsOutsideYourManagementScope': '当前帖子不在你的管理范围内',
  'errors.thisPostWasAlreadyHandledByAnotherReviewFlowRefr': '该帖子已由其他审核流程处理，请刷新审核队列',
  'errors.thisQAPostAlreadyHasAnAcceptedAnswer': '该问答帖已经采纳过答案',
  'errors.thisQuestionBankIsStillReferencedByAnExamAndCann': '当前题库仍被考试引用，无法删除',
  'errors.thisReplyWasAlreadyHandledByAnotherReviewFlowRef': '该回复已由其他审核流程处理，请刷新审核队列',
  'errors.thisReportHasBeenClosedNoFurtherWarningCanBeIssu': '该举报已结束处理，不能再次发出警告',
  'errors.thisReportIsNotAssignedToYou': '当前举报不在你的处理范围内',
  'errors.thisReportTargetCannotBeLinkedToAUserWhoCanBeWar': '当前举报对象无法关联到可警告用户',
  'errors.thisReportTargetDoesNotSupportHidingOrArchiving': '当前举报对象不支持隐藏或归档操作',
  'errors.thisResourceDoesNotHavePasscodeVerificationEnabl': '该资源未启用口令验证',
  'errors.thisResourceIsNotAnExternalDownloadAndCannotBeMa': '当前资源不是外链下载，无法标记为付费资源',
  'errors.thisResourceIsNotInABranchYouModerate': '当前资源不在你的管辖分支内',
  'errors.thisResourceIsNotWithinYourManagementScope': '当前资源不在你的管理范围内',
  'errors.thisResourceWasAlreadyHandledByAnotherReviewFlow': '该资源已由其他审核流程处理，请刷新审核队列',
  'errors.thisSectionDoesNotAcceptSubmissionsRightNow': '该板块当前不可投稿',
  'errors.thisSectionStillContainsVideosAndCannotBeDeleted': '该分区下还有视频，暂时不能删除',
  'errors.thisServerAlreadyExistsAndIsPublishedEditItOnThe': '该服务器已存在且已发布，请前往原服务器页面进行编辑',
  'errors.thisServerDoesNotHavePassphraseVerificationEnabl': '该服务器未启用口令验证',
  'errors.thisServerHasNoConnectionAddressConfiguredYet': '该服务器暂未配置连接地址',
  'errors.thisServerWasAlreadyHandledByAnotherReviewFlowRe': '该服务器已由其他审核流程处理，请刷新审核队列',
  'errors.thisSiteApiEndpointHasBeenRetiredUseTheNewDomain': '站点 API 端点已退役，请使用按业务域划分的新接口',
  'errors.thisSiteDoesNotSupportDirectUploadYetUseRegularO': '当前站点暂不支持直传，请改用普通上传或分块上传',
  'errors.thisTargetAlreadyHasTheCorrespondingVerification': '当前对象已拥有对应认证，无需重复申请',
  'errors.thisThirdPartyAccountDidNotProvideAUsableEmailPl': '该第三方账号没有提供可用邮箱，请联系管理员补充邮箱',
  'errors.thisThirdPartyAccountIsAlreadyBoundJustLogIn': '该第三方账号已完成绑定，请直接登录',
  'errors.thisUserHasNotSetATwoLayerPassword': '该用户未设置双层密码',
  'errors.thisUserHasTurnedOffDirectMessages': '该用户已关闭私信功能',
  'errors.thisUserHasTurnedOffDirectMessagesTheMessageCann': '对方已关闭私信功能，无法发送消息',
  'errors.thisUserIsAlreadyALeaderOrAdministratorOfAnother': '当前用户已是其他组织会长或管理员，不能再加入其它组织',
  'errors.thisUserIsAlreadyALeaderOrAdministratorOfAnother2': '当前用户已是其他组织会长或管理员，不能再成为新的组织管理员',
  'errors.thisUserIsAlreadyInTheOrganization': '该用户已经在组织中',
  'errors.thisUserIsNotInTheChatRoom': '该用户不在聊天室中',
  'errors.thisUsernameIsAlreadyRegistered': '该用户名已被注册',
  'errors.thisUsernameIsAlreadyTaken': '该用户名已被使用',
  'errors.thisVerificationTypeDoesNotSupportTheCurrentTarg': '该认证类型不支持当前目标类型',
  'errors.thisVersionAlreadyExistsInTheCurrentGroup': '该版本在当前分组已存在',
  'errors.thisVideoDoesNotHavePasscodeVerificationEnabled': '该视频未启用口令验证',
  'errors.thisVideoIsNotInASectionYouModerate': '当前视频不在你的管辖分区内',
  'errors.thisVideoIsOutsideYourManagementScope': '当前视频不在你的管理范围内',
  'errors.thisVideoWasAlreadyHandledByAnotherReviewFlowRef': '该视频已由其他审核流程处理，请刷新审核队列',
  'errors.timedOutWhileGettingTheGeeIdOauthTokenPleaseTryA': 'Gee ID OAuth token 获取超时，请稍后重试',
  'errors.timedOutWhileLoadingGeeIdOauthUserInformationPle': 'Gee ID OAuth 用户信息获取超时，请稍后重试',
  'errors.titleAndPathCannotBeEmpty': '标题和路径不能为空',
  'errors.titleCannotBeEmpty': '标题不能为空',
  'errors.toClearTheDefaultWordFilterUseTheManualEditBoxAn': '默认词库请通过手动编辑框清空后保存',
  'errors.toKeepYourAccountSecureBindTwoStepVerification2f': '为保障账号安全，请先在设置中绑定二步验证(2FA)、通行密钥或设置双层密码后再执行此操作',
  'errors.tokenExpiredOrInvalid': 'Token 已过期或无效',
  'errors.tokenNameCannotBeEmpty': 'Token 名称不能为空',
  'errors.tooManyEmailsSentPleaseTryAgainLater': '邮件发送过于频繁，请稍后再试',
  'errors.tooManyIncorrectVerificationCodesPleaseRequestAN': '验证码错误次数过多，请重新获取验证码',
  'errors.tooManyIncorrectVerificationCodesPleaseTryAgainI': '验证码错误次数过多，请 15 分钟后再试',
  'errors.tooManyPersonalApiRequests': '个人 API 请求过于频繁',
  'errors.tooManyRedirects': '重定向次数过多',
  'errors.tooManyRedirectsWhileDownloadingTheSkill': 'Skill 下载重定向次数过多',
  'errors.tooManyRegistrationRequestsRightNowPleaseTryAgai': '当前注册请求较多，请稍后再试',
  'errors.tooManyRequestsForThisSiteApiKey': '当前站点 API 密钥请求过于频繁',
  'errors.tooManyRequestsFromThisDevicePleaseTryAgainLater': '当前设备请求过于频繁，请稍后再试',
  'errors.tooManyRequestsFromThisSourcePleaseTryAgainLater': '当前来源请求过于频繁，请稍后再试',
  'errors.topicCategoryGroupNameCannotBeEmpty': '话题分类组名称不能为空',
  'errors.topicCategoryGroupOrTopicSlugAlreadyExists': '话题分类组或话题 slug 已存在',
  'errors.totalSizeOfThisUploadExceedsTheLimit': '本次上传总大小超过限制 (',
  'errors.unableToGetTheVerifiedPhoneNumberFromGeeIdAuthor': '无法获取 Gee ID 已验证的手机号，请重新授权 Gee ID 后重试',
  'errors.unableToObtainAMinecraftAccessToken': '无法获取 Minecraft 访问令牌',
  'errors.unableToReadTheContentLinkedToTheConversation': '无法读取对话关联的内容',
  'errors.unauthorizedShopRequest': '未授权的商城请求',
  'errors.unsupportedAiProvider': '暂不支持的 AI Provider: ',
  'errors.unsupportedErrorCode': '不支持的错误码',
  'errors.unsupportedFileTypeAllowed': '不支持的文件类型，允许: ',
  'errors.unsupportedImageTypeAllowed': '不支持的图片类型，允许: ',
  'errors.unsupportedRestrictionType': '不支持的限制类型',
  'errors.unsupportedVerificationApplicationType': '不支持的认证申请类型',
  'errors.unsupportedZipCompressionMethod': 'ZIP 压缩方式不受支持',
  'errors.updatedsinceMustBeAValidIso8601Time': 'updatedSince 必须是有效的 ISO 8601 时间',
  'errors.useTheAdminCredentialsEndpointToChangeTheEmailOr': '请使用管理员凭证接口修改邮箱或密码',
  'errors.userNotFound': '用户不存在',
  'errors.userNotFoundOrDisabled': '用户不存在或已停用',
  'errors.userNotFoundPleaseLogInAgain': '用户不存在，请重新登录',
  'errors.userVerificationAuthorizationNotFound': '用户认证授权不存在',
  'errors.usernameAlreadyExists': '用户名已存在',
  'errors.usernameCanBeAtMost20Characters': '用户名最多 20 个字符',
  'errors.usernameContainsIllegalCharacters': '用户名包含非法字符',
  'errors.usernameEmailAndPasswordCannotBeEmpty': '用户名、邮箱和密码不能为空',
  'errors.usersInYourRegionMustBindAPhoneNumberBeforePerfo': '当前访问地区需先绑定手机号后再执行此操作',
  'errors.usersRegisteredInMainlandChinaMustBindAPhoneNumb': '中国大陆注册用户需先绑定手机号后才能发布资源',
  'errors.usersRegisteredInMainlandChinaMustBindTwoStepVer': '中国大陆注册用户需先绑定二步验证(2FA)、通行密钥或设置双层密码后才能发布资源',
  'errors.verificationApplicationNotFound': '认证申请不存在',
  'errors.verificationCategoryNotFound': '认证分类不存在',
  'errors.verificationFailed': '验证失败',
  'errors.verificationFailedPleaseTryAgainLater': '验证失败，请稍后重试',
  'errors.verificationHasExpiredPleaseLogInAgain': '验证已过期，请重新登录',
  'errors.verificationIdentifierAlreadyExists': '认证标识已存在',
  'errors.verificationTypeNotFound': '认证类型不存在',
  'errors.verifiedMustBeABoolean': 'verified 必须为布尔值',
  'errors.videoFloorNumbersHaveBeenUsedUp': '视频楼层号已用尽',
  'errors.videoSectionCannotBeEmpty': '视频分区不能为空',
  'errors.videoSectionNameAndIdCannotBeEmpty': '视频分区名称和 ID 不能为空',
  'errors.videoSectionNotFound': '视频分区不存在',
  'errors.videoZoneIdAlreadyExists': '视频分区 ID 已存在',
  'errors.videoZoneNameCannotBeEmpty': '视频分区名称不能为空',
  'errors.voteFailed': '投票失败',
  'errors.wechatPayIsNotConfiguredYet': '微信支付暂未配置',
  'errors.whenHidingTheServerAddressPleaseProvideAtLeastAQ': '隐藏服务器连接地址时，请至少填写 QQ 群、Discord 或连接申请入口',
  'errors.whenSelectingOtherPleaseFillInTheDetails': '选择“其他”时，请填写具体详情',
  'errors.whenShortLinksAreEnabledTheTemplateMustContainTh': '启用短链接时模板必须包含 {url} 占位符',
  'errors.wordFilterGroupNameCannotBeEmpty': '词库组名称不能为空',
  'errors.youAlreadyHaveAPendingApplicationWithTheSameLink': '你已有同链接的待审核申请',
  'errors.youAreAlreadyALeaderOrAdministratorOfAnotherOrga': '你已经是其他组织的会长或管理员，当前设置下不能再创建新组织',
  'errors.youAreMutedAndCannotEditMessagesInTheChatRoomFor': '你已被禁言，暂不能在聊天室编辑消息',
  'errors.youAreMutedAndCannotRecallMessagesInThisChatRoom': '你已被禁言，暂不能在该聊天室撤回消息',
  'errors.youAreMutedAndCannotSpeakInThisChatRoomForNow': '你已被禁言，暂时不能在该聊天室发言',
  'errors.youAreNoLongerInThisChatRoomOrTheChatRoomIsUnava': '你已不在该聊天室或聊天室不可用',
  'errors.youAreNotAMemberOfThisOrganization': '你不是该组织成员',
  'errors.youAreNotAMemberOfThisOrganizationSoYouCannotPos': '你不是该组织成员，不能以该组织名义发布帖子',
  'errors.youAreNotAMemberOfThisOrganizationSoYouCannotPub': '你不是该组织成员，不能以该组织名义发布找服玩',
  'errors.youAreNotAMemberOfThisOrganizationSoYouCannotPub2': '你不是该组织成员，不能以该组织名义发布资源',
  'errors.youAreNotCurrentlyInThisOrganization': '你当前不在这个组织中',
  'errors.youCanFollowTheOrganizationOnlyAfterItIsApproved': '组织审核通过后才能关注',
  'errors.youCanOnlyApplyForVerificationForOrganizationsYo': '只能为自己创建并持有的组织申请认证',
  'errors.youCanOnlyDeleteMessagesYouSent': '仅可删除自己发送的消息',
  'errors.youCanOnlyDeleteYourOwnPostsOrPostsWithinYourMan': '只能删除自己的帖子或管理范围内的帖子',
  'errors.youCanOnlyDeleteYourOwnReplies': '只能删除自己的回复',
  'errors.youCanOnlyEditYourOwnReplies': '只能编辑自己的回复',
  'errors.youCanOnlyFeatureYourOwnContentThatIsPublicAndAp': '只能精选自己已公开通过的内容',
  'errors.youCanOnlyRecallMessagesYouSent': '仅可撤回自己发送的消息',
  'errors.youCanOnlyReplyToTopLevelComments': '只能回复顶层评论',
  'errors.youCanOnlyReplyToTopLevelReplies': '只能回复顶层回复',
  'errors.youCanOnlyTransferContentYouOwnThatHasNotBeenAss': '只能转移本人名下且尚未归属工作室的内容',
  'errors.youCannotAddYourselfToTheBlacklist': '不能把自己加入黑名单',
  'errors.youCannotBanYourself': '不能封禁自己',
  'errors.youCannotChangeTheGroupOwnerSRole': '不能修改群主角色',
  'errors.youCannotChangeYourOwnGroupOwnerRole': '不能调整自己的群主身份',
  'errors.youCannotCoinYourOwnContent': '不能给自己的内容投币',
  'errors.youCannotFollowYourself': '不能关注自己',
  'errors.youCannotMoveAPostOutsideYourManagementScope': '不能将帖子移动到你的管理范围外',
  'errors.youCannotMuteThisMember': '你不能禁言该成员',
  'errors.youCannotRateYourOwnResource': '不能给自己的资源评分',
  'errors.youCannotRateYourOwnServerFinderEntry': '不能给自己的找服玩内容评分',
  'errors.youCannotRemoveThisMember': '你不能移除该成员',
  'errors.youCannotReportAnOauthAppYouManage': '不能举报自己管理的 OAuth 应用',
  'errors.youCannotReportAnOrganizationYouManage': '不能举报自己管理的组织',
  'errors.youCannotReportYourOwnContent': '不能举报自己的内容',
  'errors.youCannotReportYourself': '不能举报自己',
  'errors.youCannotStartAConversationWithYourself': '不能与自己对话',
  'errors.youCannotTakeActionOnYourOwnAccount': '不能处理自己的账号',
  'errors.youCannotUnfollowYourself': '不能取消关注自己',
  'errors.youCannotUnmuteThisMember': '你不能解除该成员的禁言',
  'errors.youCannotUseYourOwnReferralCode': '不能使用自己的推广码',
  'errors.youCannotWarnYourOwnAccount': '不能警告自己的账号',
  'errors.youCurrentlyHaveNoHomepageUrlChangeCooldownSoThi': '你当前没有主页地址修改冷却，不需要使用这张卡',
  'errors.youDoNotHaveAProfileBackgroundChangeCooldownSoYo': '你当前没有主页背景图修改冷却，不需要使用这张卡',
  'errors.youDoNotHaveAUsernameChangeCooldownSoYouDoNotNee': '你当前没有用户名修改冷却，不需要使用这张卡',
  'errors.youDoNotHavePermissionToAccessDocumentOptions': '无权访问文档选项',
  'errors.youDoNotHavePermissionToAccessTheTutorialIndex': '无权访问教程索引',
  'errors.youDoNotHavePermissionToCreateATutorialIndex': '无权创建教程索引',
  'errors.youDoNotHavePermissionToCreateDocumentGroups': '无权创建文档组',
  'errors.youDoNotHavePermissionToDeleteTheTutorialIndex': '无权删除教程索引',
  'errors.youDoNotHavePermissionToDeleteThisVideo': '无权删除该视频',
  'errors.youDoNotHavePermissionToEditTheDocumentGroup': '无权编辑文档组',
  'errors.youDoNotHavePermissionToEditTheOrganizationHomep': '你没有修改组织主页的权限',
  'errors.youDoNotHavePermissionToEditTheOrganizationProfi': '你没有修改组织资料的权限',
  'errors.youDoNotHavePermissionToEditTheTutorialIndex': '无权编辑教程索引',
  'errors.youDoNotHavePermissionToEditThisPost': '没有权限编辑此帖子',
  'errors.youDoNotHavePermissionToEditThisVideo': '无权编辑该视频',
  'errors.youDoNotHavePermissionToManageSomeOfTheSelectedC': '你没有管理部分所选内容的权限',
  'errors.youDoNotHavePermissionToManageThisChatRoom': '你没有管理该聊天室的权限',
  'errors.youDoNotHavePermissionToManageThisOrganization': '你没有管理该组织的权限',
  'errors.youDoNotHavePermissionToManageThisOrganizationSM': '你没有管理该组织成员的权限',
  'errors.youDoNotHavePermissionToOperateThisUploadSession': '无权操作该上传会话',
  'errors.youDoNotHavePermissionToPublishTheSelectedConten': '你没有以该工作室发布所选内容的权限',
  'errors.youDoNotHavePermissionToReportThisChat': '无权举报此聊天',
  'errors.youDoNotHavePermissionToSubmitVideosOnBehalfOfTh': '无权以该组织身份投稿视频',
  'errors.youDoNotHavePermissionToTakePartInThisPoll': '没有权限参与该投票',
  'errors.youDoNotHavePermissionToUseThisFeature': '无权使用此功能',
  'errors.youDoNotHavePermissionToViewThisStudioSData': '你无权查看该工作室的数据',
  'errors.youHaveAlreadyCheckedInOnThisDay': '这一天已经签到过了',
  'errors.youHaveAlreadyCheckedInToday': '今天已经签到过了',
  'errors.youHaveAlreadyLikedThis': '你已经点过赞了',
  'errors.youHaveAlreadyReportedThisTargetPleaseWaitForThe': '你已举报过该对象，请等待管理员处理',
  'errors.youHaveNotLikedAnythingYet': '你还没有点赞',
  'errors.youMustCompleteTheDeveloperExamBeforeConfirmingT': '完成开发者考试后才能确认创作者协议',
  'errors.youMustMeetTheResourceSAccessUnlockRequirementsB': '需要先通过资源的访问解锁条件后才能获取下载信息',
  'errors.yourAccountDoesNotYetMeetTheRequirementsForThisV': '当前账号尚未满足该认证的申请条件',
  'errors.yourAccountHasNoEmailForGeeIdYetBindAnEmailOrCom': '当前账号还没有可用于 Gee ID 的邮箱，请先绑定邮箱或完成 GeeID OAuth 绑定',
  'errors.yourAccountSecurityStateChangedDuringVerificatio': '验证期间账号安全状态已变化，请重新登录',
  'errors.yourCurrentPointsCannotBeUsedToTipThisTypeOfCont': '当前积分不能用于这类内容投币',
  'errors.yourOrganizationMustBeApprovedBeforeYouCanApplyF': '组织审核通过后才能申请聊天室',
  'errors.yourProfileBackgroundChangeCooldownHasAlreadyEnd': '你的主页背景图修改冷却已经结束，不需要使用这张卡',
  'errors.yourUsernameChangeCooldownHasAlreadyEndedSoYouDo': '你的用户名修改冷却已经结束，不需要使用这张卡',
} as const;

export default errors;
