import type { TranslationKey } from './dictionaries';

const enUS = {
  'common.language': 'Language',
  'common.search': 'Search',
  'common.login': 'Log in',
  'common.register': 'Sign up',
  'common.home': 'Home',
  'common.menu': 'Menu',
  'common.close': 'Close',
  'nav.forum': 'Forum',
  'nav.resources': 'Resources',
  'nav.community': 'Community',
  'nav.explore': 'Explore',
  'nav.shop': 'Shop',
  'nav.rankings': 'Rankings',
  'nav.hotTags': 'Hot tags',
  'nav.authors': 'Creators',
  'nav.collections': 'Collections',
  'nav.docs': 'Docs',
  'nav.campaigns': 'Events',
  'nav.discover': 'Discover',
  'nav.players': 'Servers',
  'nav.video': 'Videos',
  'nav.organizations': 'Organizations',
  'nav.verificationCenter': 'Verification',
  'nav.notifications': 'Notifications',
  'nav.messageCenter': 'Messages',
  'nav.latestDiscussions': 'Latest discussions',
  'nav.newPost': 'New post',
  'nav.allBoards': 'View all boards',
  'nav.resourceArea': 'Resources',
  'nav.allResources': 'View all resources',
  'nav.javaResources': 'Java resources',
  'nav.bedrockResources': 'Bedrock resources',
  'nav.universalResources': 'Universal resources',
  'nav.publishResource': 'Publish resource',
  'nav.manageMyResources': 'Manage my resources',
  'nav.premiumServers': 'Online-mode servers',
  'nav.offlineServers': 'Offline-mode servers',
  'nav.publishServer': 'Publish server',
  'nav.allServers': 'View all servers',
  'nav.videoArea': 'Videos',
  'nav.allVideos': 'View all videos',
  'nav.organizationSquare': 'Organization hub',
  'nav.createOrganization': 'Create organization',
  'nav.myOrganizations': 'My organizations',
  'nav.allOrganizations': 'View all organizations',
  'nav.publish': 'Publish',
  'nav.submitVideo': 'Submit video',
  'nav.personal': 'Personal',
  'nav.myProfile': 'My profile',
  'nav.myFavorites': 'Favorites',
  'nav.history': 'History',
  'nav.creationMessages': 'Creation & messages',
  'nav.creatorWorkbench': 'Creator workbench',
  'nav.myTasks': 'My tasks',
  'nav.abilityCenter': 'Ability center',
  'nav.messages': 'Messages',
  'nav.settings': 'Settings',
  'nav.appearance': 'Appearance',
  'nav.accountSettings': 'Account settings',
  'nav.adminPanel': 'Admin panel',
  'nav.viewProfile': 'View profile',
  'nav.logout': 'Log out',
  'nav.pending': 'Pending',
  'nav.member': 'Community member',
  'nav.admin': 'Admin',
  'nav.moderator': 'Moderator',
  'nav.resourceModerator': 'Resource moderator',
  'nav.forumModerator': 'Forum moderator',
  'nav.playerModerator': 'Server moderator',
  'search.placeholder': 'Search posts, resources, or users...',
  'search.recent': 'Recent searches',
  'search.clear': 'Clear',
  'search.empty': 'No recent searches',
  'footer.brandCopy': 'A community for Minecraft creators and players.',
  'footer.currentLanguage': 'Current language',
  'footer.sections': 'Footer navigation',
  'footer.subscribe': 'Subscribe',
  'footer.subscriptionCenter': 'Subscription center',
  'footer.sitemap': 'Sitemap',
  'footer.extra': 'Footer extra information',
  'footer.backHome': 'Back to home',
  'footer.backToTop': 'Back to top',
  'footer.poweredBy': 'Powered by',
  'footer.legal': '"Minecraft" and "我的世界" are trademarks of Mojang Synergies AB. This site is not affiliated with Mojang or Microsoft.',
  'cookie.learn': 'You can learn why cookies are needed and read',
  'cookie.rulesHere': 'the rules here',
} satisfies Record<TranslationKey, string>;

export default enUS;
